sidekiq/sidekiq

Changes.md, lib/sidekiq/api.rb, lib/sidekiq/launcher.rb, lib/sidekiq/util.rb, lib/sidekiq/web.rb, test/test_api.rb, test/test_web.rb, web/views/busy.erb
In environments with deterministic hostnames and PIDs (i.e. Heroku), the
current system for constructing a process's identity string produces
collisions (e.g. a new process can assume the identity of one that has
died). In order to address this, we add a UUID to the identity string.
This has been tested with a local sidekiq server (I ran some jobs and
verified that signaling from the UI works properly).
Issue #2071.
=> Add UUID to process identity.

lib/sidekiq/api.rb, lib/sidekiq/client.rb, lib/sidekiq/worker.rb
Note that both in this and the sidekiq-pro pull I didn't `.freeze` any hash accessors, because according to https://groups.google.com/forum/#!topic/rack-devel/SKAE_yqN8-0, it should be that in Ruby 2.2 that'll happen automatically, so I'd rather not litter the code any more than it needs to be.
=> Some more frozen strings.

Changes.md, lib/sidekiq/api.rb, lib/sidekiq/web.rb, lib/sidekiq/web_helpers.rb, test/test_web.rb, web/views/busy.erb
Also removed unused `each_with_index`. Tell me if there is any reason to keep them or if I should remove it from the PR.
:yellow_heart:
=> Add processes count to /stats

lib/sidekiq/client.rb
`Client#raw_push` always returns true now.  Therefore, there is no need to
check for a false return value and `Client#push` can only return nil if middleware stops the job.
The possible outcomes of a call to `push` are:
- a `jid` returned
- `nil` due to middleware
-  an exception raised
This change is motivated by changing the classification of a `nil` return from an error condition to a no-op that can be ignored unless the client code needs to know that the middleware interrupted.
=> Clean up logic and docs for Client#push(_bulk)

Changes.md, lib/sidekiq.rb, lib/sidekiq/api.rb, lib/sidekiq/middleware/server/retry_jobs.rb
We're going to start using the dead jobs. 10,000 jobs may be too small for us, I'd like to be able to configure it.
If this pull is merged in, I'll update the wiki.
=> Allows configuration of the Dead Job Queue.

lib/sidekiq/api.rb, lib/sidekiq/middleware/chain.rb
Hi,
As you may know `yield` construction more faster than `&block` in arguments (with `block.call`).
For example, for me `yield` faster than `block` to 5 times (ruby 2.1.5; *you can see benchmark below*).
And because that i changed `&block` method arguments on `yield` construction in all methods where `block` isn't need in other methods call.
*(all developers love benchmarks :smiley:)*
``` ruby
require 'benchmark/ips'
def yield_proc
yield
end
def block_proc(&block)
block.call
end
Benchmark.ips do |x|
x.report('yield'){ yield_proc{ 1 + 1 } }
x.report('block'){ block_proc{ 1 + 1 } }
end
```
```
Calculating -------------------------------------
yield   128.265k i/100ms
block    62.716k i/100ms
-------------------------------------------------
yield      5.821M (± 5.0%) i/s -     29.116M …
```
=> Changed &block method argument to yield construction

README.md
The png badges on a retina display start to hurt my eyes :stuck_out_tongue_closed_eyes:
from:
to:
=> Switch README badges from PNG to SVG

lib/sidekiq/worker.rb, test/test_scheduling.rb
At the moment, `MyWorker.perform_in(1.month)` always schedules a job in 30 days.
On the other hand, when added to a date, `1.month` will add 1 to the date's month count, which means that it will add 28, 29, 30, or 31 days depending on the month and year (feel free to read my blog post [Rails' `1.month` has a variable length](http://dstosik.github.io/rails/2015/02/19/rails-1month-variable-length/) for more details).
When I call `MyWorker.perform_in(1.month)`, I would expect the job to be scheduled next month, same day of the month, all the time. At the moment, it is true only four months in the year.
My pull request tries to fix this by converting the interval object to a Float at the last possible moment.
Please note that the test I wrote will pass even without my fix during months that …
=> MyWorker.perform_in(1.month) does not always schedule job in one month.

.travis.yml
Removed jruby-19mode as this is kind of the default now and added testing with jruby-head (that may fail) to help JRuby get prepped for an awesome 9k release :)
=> Travis jruby update

web/assets/stylesheets/application.css
Hello!
I found ui bug with text in footer navbar. If you open sidekiq web page on ipad or other tablet you can see something like as:
In my branch this looks like this:
_**P.S.: also I want to suggest hide header navbar on mobile or tablet screen size as well as in the [bootstrap](http://getbootstrap.com/components/#navbar)**_
=> Centered text in footer navbar [tablet view]

Changes.md, lib/sidekiq/api.rb, lib/sidekiq/middleware/server/logging.rb, lib/sidekiq/web_helpers.rb
In addition to #2248, it would be nice if the Web UI were a little smarter about showing ActiveJobs.
Before:
After:
=> Improve ActiveJob integration

web/assets/stylesheets/application.css, web/views/_nav.erb
Change current navbar to standard collapsed navbar by bootstrap *(see #2258 issue for more details)*. Also I test layout in **IPhone 4, 5, 6** and **IPad 2, retina** in iOS simulator tool.
**[Live example](http://sidekiq-history-gem.herokuapp.com/sidekiq/)**
=> Change current navbar to collapsed navbar

Changes.md, lib/sidekiq/web_helpers.rb, web/views/layout.erb
These changes will allow easily define custom tags for page `<head>` in any sidekiq plugins.
``` erb
<% add_to_head do %>
<link rel="stylesheet" href="/plugin.css" />
<% end %>
```
``` ruby
app.get '/plugin.css' do
custom_css ['/sidekiq/plugin.css']
end
```
=> Added helper which provide ability to add your html to <head> tag

lib/sidekiq/fetch.rb, lib/sidekiq/middleware/server/logging.rb
Hey Mike,
Something I noticed today while browsing through the source - there appears to be 2 times within the code where we're converting with `to_f` unnecessarily (I believe).
In ruby, anytime you do math with time objects it returns a float:
```ruby
[11] pry(main)> a = Time.now
=> 2015-04-01 10:51:21 -0400
[12] pry(main)> Time.now - a
=> 8.249527
[13] pry(main)> (Time.now - a).class
=> Float
```
From what I can tell `@down` will either be nil or a Time object and `start` will always be time object.  If I missed something let me know.  Thanks!
=> Removed unnecessary to_f invocations

lib/sidekiq/core_ext.rb
`Hash#keys.each` allocates an array of keys but `Hash#each_key` iterates through the
keys without allocating a new array.
=> Use Hash#each_key instead of Hash#keys.each

web/assets/javascripts/application.js, web/assets/stylesheets/application.css, web/locales/en.yml, web/locales/ru.yml, web/views/_nav.erb
*Completed #2274 issue.*
1. All protruding plugin links rolled to dropdown button
2. Trim navbar link weight for screen less than 979px
**Added *bootstrap dropdown.js* plugin for opening and hiding dropdown button**
*P.S.: I didn't change 'Dashbord' to 'Home' because it isn't necessary*
=> Fixed protruding links in header navbar

lib/sidekiq.rb, lib/sidekiq/api.rb, lib/sidekiq/client.rb, lib/sidekiq/redis_connection.rb, lib/sidekiq/worker.rb
I used [memory_profiler](https://github.com/SamSaffron/memory_profiler) gem with this code:
``` ruby
MemoryProfiler.report{ 100.times { HardWorker.perform_async } }.pretty_print
```
```
Total allocated 22631
Total retained 886
allocated memory by gem
-----------------------------------
318864  sidekiq
allocated objects by gem
-----------------------------------
2416  sidekiq
retained memory by gem
-----------------------------------
1280  sidekiq
retained objects by gem
-----------------------------------
11  sidekiq
Allocated String Report
-----------------------------------
307  "HardWorker"
200  /Users/anton/work/gems/sidekiq/lib/sidekiq/client.rb:217
300  "jid"
200  /Users/anton/work/gems/sidekiq/lib/sidekiq/client.rb:223
300  "enqueued_at"
200 …
```
=> Reduced by one third allocated memory for #perform_async method 

lib/sidekiq/middleware/server/retry_jobs.rb, test/test_retry.rb
Shall fix #2284. While checking whether an application error or a
sidekiq shutdown caused the exception, we keep track of the causes that
were already checked. If a cause was already checked, we can stop
because the whole transitive closure of its causes was checked as well.
=> Handle circular error causes

lib/sidekiq/web_helpers.rb, test/test_web.rb
Fixed #2295
Also I check `get_locale` web helper with `memory_profiler`. For this I use this code:
``` ruby
MemoryProfiler.report{ 100.times { get_locale } }.pretty_print
```
```
Total allocated 17626
Total retained 3145
allocated memory by gem
-----------------------------------
3033634  ruby-2.2.0/lib
12942  sidekiq
5040  other
```
```
Total allocated 1220
Total retained 182
allocated memory by gem
-----------------------------------
143025  ruby-2.2.0/lib
87608  sidekiq
240  other
```
=> Load only required locale files

lib/sidekiq/core_ext.rb
I found that my changes in Hash class (#2287) are working incorrect in ruby 1.9+ ([travis](https://travis-ci.org/davydovanton/sidekiq-history/builds/58011536)). :disappointed_relieved: This is due to the fact that with version 1.9, you have only read-only access to hash during iteration.
Same problem was in mperham/bayes_motel#1.
I'm sorry :cry:
=> Revert using #each_key in Hash class

web/views/queue.erb
If any of the job args contain a script tag it will execute when you view: `/admin/sidekiq/queues/default`
To reproduce:
`Job.perform_later("aldfkjaf", "<script> alert('hi');</script>")`
=> fix xss vulnerability in display class

web/assets/stylesheets/application.css
After looking into the footer again found that it did not take responsive into account. Here is a update to that as well as a fix to make the overflow respond to scroll so even if it gets cut off the screen you can still read what is in the footer or copy and past it onto a document that has more room.
[JSfiddle link to example fix](http://jsfiddle.net/newdark/2u1kxy55/8/)
=> Footer style fix #2205

lib/sidekiq.rb, lib/sidekiq/scheduled.rb, test/test_scheduled.rb
from https://github.com/mperham/sidekiq/issues/2317
Introduces `Sidekiq.options[:global_poll_interval_average]` and begins transitioning `Sidekiq.poll_interval=` to `Sidekiq.options[:poll_interval_average]`. The intended behavior is as follows:
* **global_poll_interval_average**: How frequently Redis should be checked by some random poller for scheduled and retriable jobs
* **poll_interval_average**: How frequently each Poller should check Redis for scheduled and retriable jobs. Will be calculated from `global_poll_interval_average` by default.
I noticed that the test coverage on Poller seems to prefer testing only the public interface. I confirmed that the logic in question is covered by the existing tests and opted not to add more specific unit coverage. Let me know if this is best …
=> make the average global poller delay configurable

lib/sidekiq/cli.rb
The command line parser validates that parameters that require integer options are integers, the configuration file validator was not doing this same type of validation.
* Ensure verbose is either true or false
* Ensure integer parameters are valid integers
=> Validate parameters in config file

lib/sidekiq/processor.rb
when i am testing SideKiq + Pro and Redis sentinels setup. i am experiencing "Error connecting to Redis on 127.0.0.1:6377 (Errno::ECONNREFUSED)" during a master failover. it will cause SideKiq admin to report the wrong stats due to exceptions in workers.
I have a proposed temp fix for the problem. i want to get SideKiq team's opinions on how to resolve the issue better.
=> exponential sleep and increase retries for retry_and_suppress_exceptions

Gemfile
Hopefully a simple one. `pry-byebug` also works under mri 2.2.
=> Make pry-byebug available on ruby 2.2.2 too

Changes.md, lib/sidekiq/api.rb, lib/sidekiq/client.rb, test/test_scheduled.rb, test/test_scheduling.rb
Based on the discussion in https://github.com/mperham/sidekiq/issues/2373, wanted to give this a try.
When a job is scheduled, it should have a `created_at` time, and get an `enqueued_at` when it's actually enqueued back into a queue.
=> Use created_at for the time schedule jobs are scheduled

3.0-Upgrade.md, Changes.md, lib/sidekiq.rb, lib/sidekiq/web.rb, test/test_manager.rb
In addition to #2381 and #2382.
[Link](https://github.com/bbatsov/ruby-style-guide#proc) from ruby style guides.
=> Use new proc syntax instead all Proc.new

web/assets/stylesheets/application.css
Looks like this was mistakenly? changed to `scroll` in 542b995
=> Web: Revert overflow for `redis-url` and `redis-namespace` to `hidden`

test/test_web.rb, web/views/_nav.erb, web/views/_poll_js.erb, web/views/_poll_link.erb, web/views/layout.erb
Previously, the JS function `updatePage()` was being called twice when polling is enabled (when the query string is `?poll=true`), creating two `setInterval` timers that each make an HTTP request every second and causing polling updates to look jittery. The polling link was rendered twice in the nav, once for desktop-sized browsers and once for mobile-sized browsers, and the function was called once during each render.
This PR breaks the `_poll` partial into two partials, one for the link and one for the JS, so that the JS can be called only once. I've added a test and have also tested this manually for all views in the web UI. Other solutions exist, too; I'm happy to rewrite this if another solution is preferred.
=> Prevent redundant polling in the web UI

Changes.md, lib/sidekiq/version.rb, lib/sidekiq/web.rb, lib/sidekiq/web_helpers.rb, myapp/simple.ru, web/views/busy.erb, web/views/dead.erb, web/views/morgue.erb, web/views/queue.erb, web/views/queues.erb, web/views/retries.erb, web/views/retry.erb, web/views/scheduled.erb, web/views/scheduled_job_info.erb
Form POSTs don't verify an authenticity token so it's possible to do bad stuff.  Fix incoming...
=> CSRF vulnerability in Web UI

web/locales/de.yml
Fixes a small typo and a missing german article in the translation for Germans.
=> Change typo in German translation

web/assets/javascripts/locales/jquery.timeago.pt-br.js
As a `Portuguese` native speaker I've always found a little bit weird the messages in the locale UI. Digging into the code, I could see that the same `pt-PT` locale matches perfectly with `pt-BR`. It is closer than the `English` version and gramatically correct.
The way it was before, e.g: `há uma hora nesse momento` (meaning `one hour from now on`) is grammatically incorrect because `há` is used only in the past and not for future sentences. `nesse momento` means more `right now` than `from now` (changed now to `a partir de agora`).
Any portuguese speaker here? :smile: 
**before**
_________________________________________________________________________________
**after**
**PS.** Since I'm here, is there any particular reason that in `English` we have: `about %d minutes`, `about %d …
=> Better pt-BR locales in web UI

web/assets/stylesheets/application.css
I've noticed that the pulsing beacon was not aligned properly and was animated using properties that are causing repaint of the element (padding):
Fixed this by properly center-aligning the `ring` and the `dot`. Also the `ring` is now animated using `opacity` and `scale` that's transforming the bitmap layer without causing repaint:
=> Fix dashboard pulsing beacon alignment

web/assets/stylesheets/application.css
This removes not needed CSS properties:
1. `animation-iteration-count` is 1 by default
2. There's no need for all prefixed `box-shadow` properties in an already prefixed `keyframes` block
Sorry for bunch of small PRs, might as well put all those changes in one.
=> Remove not needed CSS properties

web/assets/javascripts/dashboard.js, web/assets/stylesheets/application.css
Hi,
Here's a fix for a not very efficient use of the `pulse` class in the dashboard. Instead of updating two elements, updating only `.beacon`, which simplifies JS a bit.
=> Refactor pulsing beacon

bin/sidekiqctl
I wonder if there's any reason to use backticks over `Process.kill`, e.g. here:
https://github.com/mperham/sidekiq/blob/5ffac099418d833934768d08c11d4ed436791323/bin/sidekiqctl#L63
=> Changing `kill` to Process.kill

test/test_cli.rb
`existant` -> `existent` :cat:
=> Fix typo in cli test

lib/sidekiq/manager.rb, test/test_manager.rb
cocurrency 0 makes the manager just sit there and do nothing,
which is hard to debug / understand without knowing what to look for
we were passing concurrency via an ENV variable, so it was not obvious that this was the problem,
looked into queues / redis trouble first before realizing this ... since I think there is no valid usecase for 0 / negative concurrency, this would be a nice fix to prevent this in the future ...
@mperham 
@melvinram
=> prevent invalid concurrency from causing hard to debug problems

Changes.md, lib/sidekiq/fetch.rb, lib/sidekiq/scheduled.rb, myapp/Gemfile, test/helper.rb
I looked through `sidekiq` and this one line was the only thing holding back all the tests. Otherwise, everything seems correct as it is.
Closes #2397 
Closes #2420
That's happening in that one line, is that the actorsystem is allowed to initialize, which in turn populates the `Tree` who is complaining in the tests. *Then* we can set the global testing flag and go about our business, `boot` etc.
=> Resolve Celluloid 0.17.0 compatibility.

lib/sidekiq/api.rb, test/test_api.rb
#2472  
So I've done a number of things to the SortedEntry delete. 
a) Use `zrem` right away if we already have the `@value` for the job by-passing a redundant lookup.
b) Seperated SortedEntry into delete_by_jid and delete_by_score, properly the former could be a LUA Script, but Sidekiq states support for Redis > 2.4 so I didn't do that in this PR. 
I separated the single delete into `delete_by_jid`, `delete_by_score`, and `delete_by_value`. One concern is as I mentioned that a single monolithic method that does potentially different things is hard to hook into, another plus is that unlike the old `delete` -  `delete_by_score` can take a range. 
One thing I'm really not sure about is whether `delete_by_value` should be on SortedEntry or on SortedSet, although I opted for the later because …
=> Do not perform redundant job look-up on delete for SortedEntry

Changes.md
Looks like a typo in the changelog, though I think you may have coined a new term for future use.
=> Update change log to fix "typo"

lib/sidekiq/client.rb
I think this is a fairly subtle bug. Basically, in our code, the only time `Sidekiq::Client.push` gets called is from batch callbacks. I think that the memoization of the pool is causing issues. This is really subtle, I believe it has happened to 1 out of thousands of batches for me, but here's a conceptual idea of how it could happen.
```ruby
Sidekiq::Client.default
Sidekiq.redis = shard_2_pool
b = Sidekiq::Batch.new
b.on(:success, DoSomething)
b.jobs { MyWorker.perform_async }
```
Then the batch callback may run on shard 1 if this worker runs the final job, because the batch callbacks use `Sidekiq::Client.push` which uses the memoized `default`. This will then fail with "no such batch" because the batch lives on shard 2.
Basically, `default` is now dangerous because `Sidekiq::Client`'s …
=> Remove Sidekiq::Client.default since memoization can break sharding with batches

README.md
The Sidekiq homepage no longer(?) contains the setup process. Instead this link should go directly to the Getting Started wiki page.
Also, it's technically a 4-step process which sounds weird and more complicated than it actually is. Replaced '3-step' with 'setup'
=> Fixed 'Getting Started' link

myapp/config/environments/production.rb, myapp/config/environments/test.rb
In the Rails 5 `#serve_static_assets` will be deprecated in favour of `#serve_static_files`.
=> Change the deprecated serve_static_assets to serve_static_files configs

lib/sidekiq/testing.rb, test/test_testing_fake.rb, test/test_testing_inline.rb
This adds a middleware stack to `Testing` that simulates the server side stack.  This is useful for all server middleware that doesn't rely on the job structure in redis.
=> Add middleware stack to Testing

lib/sidekiq/middleware/server/retry_jobs.rb
According to [wiki](https://github.com/mperham/sidekiq/wiki/Error-Handling). The return value of the block must be an integer.
However many users like to use 1.hour / 2.days / 34.seconds syntax from `Activesupport::Duration`.  All Activesupport::Duration instances can be mapped to integer with `to_i` method. Lets map it than!
```
sidekiq_retry_in do |count|
10 * (count + 1) # (i.e. 10, 20, 30, 40)
end
```
=> Map retry_in period to integer

Changes.md, lib/sidekiq.rb, test/test_sidekiq.rb
ref: https://github.com/redis/redis-rb/issues/543
When AWS ElastiCache fails over from one node to another node, redis clients can be left connected to the original node which is now read-only. Sidekiq will then be unable to continue accepting or processing jobs until the connections are reset.
It seems that the best place to handle the exception would be within the sidekiq code as there are reasons why a general redis client might want to continue holding a connection to a read-only redis slave.
the specific error raised when this happens is:
`Redis::CommandErrorREADONLY You can't write against a read only slave.`
Ideally when this type of error occurs, sidekiq should drop the redis connection and retry the operation.
=> gracefully handle connection errors

test/test_web.rb, test/test_web_helpers.rb, web/locales/nb.yml
Browsers configured to prefer content in Norwegian Bokmål send 'nb-NO,no' in the Accept-Language header.
Updated to match the English translations.
=> Fix Norwegian Bokmål (nb) translations

web/assets/stylesheets/application.css, web/views/busy.erb
I noticed bit weird layout in Busy page and I figured out there was redundant `div` enclosing tag that was messing up the html structure. I removed it.
Also, I fixed margin on form button groups that looked bit bad because of 5px margin. It just bothered me.
=> Fix Styling Issues on Busy page

lib/sidekiq/cli.rb
Sidekiq performs ERB parsing on its config file, but it only checks for the existence of `sidekiq.yml`, not `sidekiq.yml.erb`.  Technically, this is a `.yml.erb` file, so Sidekiq should check for it.
The benefit of this change is that editors won't highlight the `sidekiq.yml` file as containing errors since it includes ERB but is not an ERB file.
=> Automatically check for sidekiq.yml.erb filename

sidekiq.gemspec
Last night I released concurrent-ruby 1.0.0.pre5. This is the last planned pre-release. Rails began using pre5 last night. There is nothing in this release that should affect Sidekiq. It's mainly performance improvements and a few small bug fixes (not related to the tools used here). We don't have any more work planned for 1.0. We're basically just waiting for Rails, Sidekiq, and a few others to upgrade to pre5 and run with it for a little bit. Please let me know ASAP if you discover any problems or bugs.
=> Latest concurrent-ruby release.

bin/sidekiqctl
On OpenBSD, you can only use getpgid(pid) if the calling process
belongs to the same session as the the process with the PID `pid'.
Otherwise getpgid() returns EPERM.
Using kill(0, pid) is a more portable way to check whether a process
exists.
=> Process.kill to check for process is more portable.

sidekiq.gemspec
Actually redis-namespace is still a dependency, move it dev dependency
* `redis-namespace` has been removed from Sidekiq's gem dependencies. If
you want to use namespacing ([and I strongly urge you not to](http://www.mikeperham.com/2015/09/24/storing-data-with-redis/)), you'll need to add the gem to your Gemfile:
```ruby
gem 'redis-namespace'
=> Set redis-namespace gem as dev dependency

lib/sidekiq/testing.rb
Fixes the issue with comparing symbol to strings caused by #2659
I have a lot of symbols in my code and so do others. This pull request ensure that testing queus and jobs (just like production) are only ever compared as strings.
=> Ensure comparison between strings

lib/sidekiq/web_helpers.rb
I noticed that there were multiple `&` showing up when clicking on pagination links in the web interface, this pr compacts all the nil params before joining by `&` to avoid that happening anymore.
=> Remove nil qparams to avoid extra & in url generation

4.0-Upgrade.md, Changes.md, lib/sidekiq/testing.rb, test/test_testing_fake.rb
When using the Sidekiq::Client API to push jobs on to the queue, it's
not ideal to assert the size of the queue from the perspective of a
worker because the worker may not exist in the application.
This API implements a testing API from the perspective of a queue. The
existing Worker-based testing API remains unchanged, but leverages the
job hash implemented through the Sidekiq::Queues class.
Examples:
assert_equal 1, Sidekiq::Queues["default"].size
assert_equal "SpecialWorker", Sidekiq::Queues["default"].first["class"]
Sidekiq::Queues["default"].clear
Sidekiq::Queues.clear_all
ref: https://github.com/mperham/sidekiq/issues/2562
There was a [regression](https://github.com/mperham/sidekiq/issues/2663) involving the `Rspec` syntax `change(Queueworker.jobs, :size).by(1)` . This has been …
=> Queue Testing API

lib/generators/sidekiq/templates/worker_test.rb.erb
On Minitest 5+ we should be extending Minitest::Test instead.
see https://github.com/seattlerb/minitest/blob/7b387128ef2de8dadf5947a02e1eb448df51c92a/lib/minitest/unit.rb#L26
=> Use minitest 5 parent class

.travis.yml
Closed #2694 since I realized we also need to test against previous stable, 2.1.7. 
Ruby 2.2 was released nearly [a year ago](https://www.ruby-lang.org/en/news/2014/12/25/ruby-2-2-0-released/). Let's test against the current stable, 2.2.3.
=> Test against latest ruby patch versions

lib/sidekiq/web_helpers.rb
:tada: 
```
==================================
Mode: cpu(1000)
Samples: 510 (100.00% miss rate)
GC: 47 (9.22%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
.............................. 
16   (3.1%)          16   (3.1%)     block in Sidekiq::WebHelpers#locale_files
..............................
```
stackprof doesn't show `Sidekiq::Web Helpers#locale_files` in output information
=> Fix object allocation and cpu usage for each web request

lib/sidekiq/fetch.rb
```
==================================
Mode: object(1)
Samples: 17460412 (0.00% miss rate)
GC: 0 (0.00%)
==================================
............... 
600001   (3.4%)      600001   (3.4%)     Sidekiq::BasicFetch::UnitOfWork#queue_name
..............
```
```
==================================
Mode: object(1)
Samples: 17366353 (0.00% miss rate)
GC: 0 (0.00%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
................. 
400001   (2.3%)      400001   (2.3%)     Sidekiq::BasicFetch::UnitOfWork#queue_name
................. 
```
:tada:
=> Reduce object allocations in to 1/3 times

web/locales/ja.yml
"再試行できません" means "It can not be retried.", so it has negative (or dangerous) nuance.
"再試行するジョブはありません" is better, it means "There is no jobs to be retried."
=> Fix Japanese translation for `NoRetriesFound`

lib/sidekiq/api.rb, lib/sidekiq/launcher.rb, web/views/busy.erb
I'd like to see a visual indicator in the web UI when a process has been quieted (or is stopping).
Our shop uses a blue/green deployment strategy, so the inactive processes are "quieted" after a deployment, but they continue to heartbeat and appear in the web UI. We'd like to be able to easily identify and confirm that they are "quiet".
=> Add "quiet" label to UI when process is quieted"

lib/sidekiq/api.rb
This PR is a minor optimization in the API.
We should avoid recomputing the range size 2 times as we already computed it for range_start.
Thanks!
=> Avoid recomputing range_size everytime in API

lib/sidekiq/testing.rb, test/test_testing_fake.rb
The queue-based testing hash (@jobs_by_queue) stores the queue name as a string. Therefore, when a worker is given a symbol as queue name, deleting the job from the @jobs_by_queue silently fails, leaving the job in @jobs_by_queue (even though deleting succeded from the @jobs_by_worker). 
Sidekiq::Worker.drain_all gets the jobs through @jobs_by_queue, but since the jobs are never removed from the queue-based hash, calling drain_all will result in an endless loop.
Without my patch in Queues.delete_for, my added test will result in the described endless loop. If my suggested patch/test needs more work, please let me know, i'm more than happy to do that.
thanks!
=> Sidekiq::Worker.drain_all loops endlessly when queue name is symbolized

lib/sidekiq/middleware/server/retry_jobs.rb, test/test_retry_exhausted.rb
Behold! I'm taking a challenge of making an **extremely** compelling case for why Sidekiq's thousands of users would want that change. :-)
1. Finally have a dead easy way to handle an exception when retries are exhausted. Currently it's doable only through global error handlers (`config.error_handlers`). A lot of custom code is needed to implement a per-job handler. Example use cases:
- Suspend account when no money could be collected after retries.
- Report to Bugsnag after the job really fails. (Instead of the default way of doing that, every job retry)
2. Backwards compatible. Block parameters are optional in Ruby. Thanks to that `sidekiq_retries_exhausted do |msg|` and `sidekiq_retries_exhausted do |msg, e|` just work.
3. No performance penalty. No extra computing is needed to create …
=> Pass exception object to sidekiq_retries_exhausted block

Changes.md, lib/sidekiq.rb, lib/sidekiq/middleware/server/retry_jobs.rb, test/test_retry_exhausted.rb
I'd like to be able to notify an on-call service like Pager Duty whenever _any_ worker exhausts all available retry attempts. 
Implementing this on each worker as a `sidekiq_retries_exhausted` block is a bit fragile and tedious. Authoring custom middleware might work, but requires a bit of job metadata parsing to determine if any retry attempts remain and is somewhat implementation-dependent.
Would love to see a support feature for registering global "dead job" handlers!
=> Implement a global retries exhausted handler

lib/sidekiq/logging.rb
Sidekiq crashes when reopening log with `uninitialized constant Sidekiq::Logging::Fcntl`
Ruby 2.3.0
Rails 4.2.5.1
Sidekiq running with `-d` `-L`
It seems that if the USR2 signal is sent to the sidekiq process and nothing else loaded has done `require 'fcntl'` yet, the `Fcntl` lookup can fail.
```
2016-02-23T08:31:55.195Z 3192 TID-ovd5cufiw INFO: Received USR2, reopening log file
uninitialized constant Sidekiq::Logging::Fcntl
/.../vendor/bundle/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/logging.rb:65:in `block in reopen_logs'
/.../vendor/bundle/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/logging.rb:63:in `each_object'
/.../vendor/bundle/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/logging.rb:63:in `reopen_logs'
/.../vendor/bundle/ruby/2.3.0/gems/sidekiq-4.0.2/lib/sidekiq/cli.rb:140:in …
```
=> require 'fcntl' in logging.rb

lib/sidekiq.rb, lib/sidekiq/cli.rb, lib/sidekiq/util.rb, lib/sidekiq/web_helpers.rb, test/test_sidekiq.rb
As discussed in #2850 this adds the method `redis_info` to `Sidekiq`, to allow easier monkey patching for servers that disable `INFO`.
-  [x] Had to use `Sidekiq.redis_info` and was not able to write it in `Utils.redis_info`, as the `Utils` are not included in the WebHelpers, okay?
One more thing, if possible I'd really like to change `self.redis_info` to the following, but I agree that having to support all crazy redis configuration variants might not really be viable.
```ruby
def self.redis_info
redis do |conn|
begin
if conn.respond_to?(:namespace)
conn.redis.info
else
conn.info
end
rescue Redis::CommandError => ex
raise unless ex.message =~ /Unknown command/
{ 'redis_version' => '2.8' }
end
end
end
```
Otherwise is it possible to add this to the wiki, or where would be the place to add …
=> Added Sidekiq#redis_info to encapsulate info calls

lib/sidekiq/logging.rb
Updated logging path to fix SystemCallError on Windows environment, as '/dev/null' will break gem loading
=> Fixed SystemCallError for Windows path

lib/sidekiq/client.rb, test/test_client.rb
this fixes the incorrect conditional statement 
`if x = Thread.current[:sidekiq_via_pool] && x != pool`
which evaluates as if it was written as 
`if x = (Thread.current[:sidekiq_via_pool] && x != pool)`
=> allow sidekiq::client.via to point to same redis

lib/sidekiq/web_helpers.rb
Updates the `display_args` method to pass the unused `truncate_after_chars` method to `truncate`
=> Truncate text in display_args based on formerly unused variable

lib/sidekiq/exception_handler.rb, test/test_exception_handler.rb
Dump the context as JSON for proper logging
=> Dump the context as JSON for proper logging

examples/upstart/sidekiq.conf
Upstart "kill timeout" is 5 seconds by default (http://upstart.ubuntu.com/cookbook/#kill-timeout). 
This will cause that when using the provided upstart/sidekiq.conf, upstart will kill the sidekiq process while is waiting for any running workers to end, and even before the process enqueue them into the retries queue, losing any running jobs.
This PR sets a higher timeout that should be safe to use with the default sidekiq "kill_timeout" which is 10 seconds.
=> Set kill timeout to 15 sec. in upstart config

lib/sidekiq/redis_connection.rb, test/test_redis_connection.rb
Fixes an edge case where a stringified `namespace` key is ignored. A `namespace` key may be a string if the Sidekiq Redis config is loaded from a yml file.
This pull request also includes minor, syntactical improvements to error messaging related to redis-namespace. 
All tests pass.
Resolves https://github.com/mperham/sidekiq/issues/2988.
=> Symbolize keys in options hash for RedisConnection.create

web/locales/de.yml
"Inaktiv" has a specific connotation in German, which I suspect is not what we're looking to convey here.
=> Fixed the translation of "idle" for the de locale

lib/sidekiq.rb, lib/sidekiq/launcher.rb, lib/sidekiq/version.rb, test/test_launcher.rb
This allows us to recover from network outages without having to restart the entire process.
=> Add event when a process has a new heartbeat

lib/sidekiq/web/action.rb, lib/sidekiq/web/application.rb
Duplicate headers hash before returning to Rack to prevent the global header responses from getting modified.  Freeze the global header objects to surface situations where the global constant headers are modified.  See #3143 for problem description and reproduction.
=> Resolve `rack.session` cookie duplication

lib/sidekiq/testing.rb
When adding the job to the Queue, it uses the value corresponding to the
"queue" key in the job hash, but for deleting that it has just processed, the
queue from the sidekiq_configuration of the Worker is used. This means that the
job is only removed from the jobs_by_worker hash in the Queue, and not the
jobs_by_queue Hash, leading to drain_all repeatedly trying to get a worker to
work on the job (as it uses jobs_by_queue), and the worker not finding a job to
work on (as it uses jobs_by_worker).
This can be fixed by deleting the job from the queue by using the queue for the
job, and not the default for the worker.
Fixes #3144
=> Prevent an infinite loop when the job queue is not the worker default

lib/sidekiq/web/application.rb
Fixes #3151
If you mount at `/sidekiq` and visit the `/sidekiq` URL, it will now redirect over to `/sidekiq/`, rather than 404ing.
=> Redirect from no trailing slash on Web UI

lib/sidekiq/processor.rb, lib/sidekiq/util.rb
When working on Sentry's Sidekiq integration, I noticed that the message provided to the exception handler can change a little depending on the context, making it difficult to pull structured data out. This makes all exceptions handle consistently.
=> Provide consistent interface to exception handlers

sidekiq.gemspec
Addresses #3145 
Tested and currently in production use.
Deals with rack-protection Sinatra version conflict by removing version constraint from gemspec.
=> Remove gemspec version constraint for rack-protection

lib/sidekiq/web/application.rb
If content_type other than json (ex. "text/css", "text/javascript"),  `NameError - uninitialized constant Sidekiq::WebAction::CONTENT_TYPE:` has occurred.
`Sidekiq::WebAction::CONTENT_TYPE` was removed.
https://github.com/mperham/sidekiq/commit/ad350433a87718ca9d83c14c50631d3bca0954f6
Restore `WebAction::CONTENT_TYPE` or set "Content-Type".
```
NameError - uninitialized constant Sidekiq::WebAction::CONTENT_TYPE:
activesupport (5.0.0.1) lib/active_support/dependencies.rb:550:in `load_missing_constant'
activesupport (5.0.0.1) lib/active_support/dependencies.rb:203:in `const_missing'
sidekiq (4.2.2) lib/sidekiq/web/application.rb:289:in `call'
newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack-protection (1.5.3) …
```
=> Fix uninitialized constant Sidekiq::WebAction::CONTENT_TYPE error

lib/sidekiq/worker.rb, test/test_scheduling.rb
We are using Sidekiq Pro with ActiveSupport.
When I passed a object which is ActiveSupport::TimeWithZone to perform_at,
`TypeError: can't convert ActiveSupport::TimeWithZone into an exact
number` has occurred.
The object of Time class can't plus a ActiveSupport::TimeWithZone object.
We can transform any Time object to float, and use it to compare and
calculate.
=> Fix the error in worker#perform_in about interval type

lib/sidekiq.rb, lib/sidekiq/cli.rb, lib/sidekiq/middleware/server/active_record.rb, lib/sidekiq/rails.rb
The new Rails reloader enables the query cache within every yield and expects to have access to the current connection that it enabled the query cache for at the end of the block to clear the cache and then release the connection. The Sidekiq ActiveRecord middleware which is added automatically releases the connection earlier, the query cache of another connection may instead be cleared, and the dirty query cache might be used by another worker.
This change makes sure that the ActiveRecord middleware cannot be used in tandem with the new Rails reloader (in case folks have added it to their middleware stacks explicitly) and removes it from the default middleware stack when the reloader is in play.
I couldn't figure out a way to raise the error from the middleware during startup. It seems …
=> Resolve Rails Reloader and ActiveRecord middleware incompatibility

lib/sidekiq/web.rb, lib/sidekiq/web/helpers.rb, test/test_web.rb
According to #3180, this pull request allows to disable session.
The pull request is not ready to be merged : the test I've added won't pass, when executed along with the full test suite.
I'm not yet familiar with rack tests and looking for isolated sessions between tests.
=> Allow to disable sessions

web/assets/javascripts/application.js
The timestamps were not updated during live polling since
cd3d18b81e9bd81fdbec440adb0d6709128c412a.
This causes the timestamps to be updated with fuzzy timestamp text when
live polling is turned on.
=> Update the fuzzy timestamps during polling

lib/sidekiq/processor.rb, test/test_processor.rb
The reloader might raise an error instead of yielding control. If this happens, the job will silently fail to run, without being reenqueued and without logging any indication of what happened. I'm pretty sure that's what was happening here: https://github.com/mperham/sidekiq/issues/3154#issuecomment-253125379.
This change doesn't prevent the job from being lost, but at least if the error handlers are called it will be possible to diagnose the problem.
=> Handle errors raised by the reloader

lib/sidekiq/processor.rb, test/test_processor.rb
Fixes https://github.com/mperham/sidekiq/issues/3223.
When I moved the reloader inside the block in https://github.com/mperham/sidekiq/pull/3212 so that any errors it raised would be handled properly, the `job` local variable was pushed into a nested scope, which meant it wasn't accessible from the rescue block any more. This changed the meaning of `job` in that rescue block from the local variable to [the `attr_reader` with the same name](https://github.com/mperham/sidekiq/blob/v4.2.5/lib/sidekiq/processor.rb#L30).
We don't need to reload the application before parsing the job payload, so we can move this work outside the reloader block so that the job hash is accessible in the rescue block again.
=> Pass job hash to handle_exception again

lib/sidekiq.rb, lib/sidekiq/processor.rb, lib/sidekiq/rails.rb
We have to release the current thread's Active Record connection after performing each job, in case another thread is waiting to use it.
On Rails 4 and earlier, this is handled with [middleware](https://github.com/mperham/sidekiq/blob/v4.2.5/lib/sidekiq/middleware/server/active_record.rb). On Rails 5 in development mode, the reloader does it by [delegating to the executor](https://github.com/rails/rails/blob/v5.0.0.1/activesupport/lib/active_support/reloader.rb#L67-L69). However on Rails 5 in production mode, we're not adding the middleware or enabling the reloader, so connections will never be released.
We can call the executor directly to have it [release the connection for us](https://github.com/rails/rails/blob/v5.0.0.1/activerecord/lib/active_record/query_cache.rb#L48) in this case. …
=> Use Rails executor if code reloading is disabled

lib/sidekiq/web/helpers.rb
Fixes the following issue:
```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/web/helpers.rb:191:in `<module:WebHelpers>': uninitialized constant Sidekiq::WebHelpers::Set (NameError)
from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/web/helpers.rb:7:in `<module:Sidekiq>'
from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/web/helpers.rb:5:in `<top (required)>'
from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.5/lib/sidekiq/web.rb:7:in `<top (required)>'
from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in …
```
=> Fix issue with Set

lib/sidekiq/rails.rb
This little PR teaches Psych how to use `constantize` in the development environment of Rails. It fixes #3171, so you don't need to remove delay extensions anymore :)
=> Monkeypatch Psych to enable Rails autoloading

lib/sidekiq.rb, lib/sidekiq/api.rb, lib/sidekiq/cli.rb, lib/sidekiq/launcher.rb, lib/sidekiq/manager.rb, test/test_retry.rb, test/test_sidekiq.rb, test/test_web.rb
In jruby 1.7.22 (1.9.3p551 compatibility mode), UTF-8 encoding is not properly
detected, because the encoding comment is not on the first line as required in ruby
1.9.
The frozen_string_literal magic comment did not come into existence until ruby 2.3,
and ruby 1.9 does not look past the first line for magic comments.
This results encoding-related syntax errors. Examples:
SyntaxError: /home/nilbus/ws/rental_express/ROOT/rails/vendor/bundle/jruby/1.9/gems/sidekiq-4.2.6/lib/sidekiq.rb:52: Invalid char `\235' ('') in expression
def self.â¨â¯Â°â¡Â°â©â¯ï¸µâ»ââ»
^
SyntaxError: /home/nilbus/ws/rental_express/ROOT/rails/vendor/bundle/jruby/1.9/gems/sidekiq-4.2.6/lib/sidekiq/api.rb:269: Invalid char `\237' ('') in expression
alias_method :ð£, :clear
^
This patch should restore …
=> Put source encoding comment as line for [j]ruby 1.9 compatibility

lib/sidekiq/testing.rb, test/test_testing_fake.rb
Implements https://github.com/mperham/sidekiq/issues/3245
Trying to emulate the real behavior, the job obtains an `enqueued_at` attribute when it's placed in a queue.
Since using `perform_in` or `perform_at` does not put the job in the queue when run, the attribute is not set for those methods.
=> Add the enqueued_at attribute when fake Testing

web/views/queue.erb
Implements [#3282](https://github.com/mperham/sidekiq/issues/3282).
Hides the initial preview line when 'Show All' button is pressed.
=> Hide the intial preview line when using Show All in the UI

lib/sidekiq/manager.rb
It seems it was feeding Processors at some point, but it is not anymore.
=> Remove incorrect part of Manager's description

.travis.yml, lib/sidekiq/middleware/server/retry_jobs.rb, lib/sidekiq/web/application.rb
Fixnum is deprecated in Ruby 2.4 so we should get rid of it.
=> Fixnum -> Integer replacement and Ruby 2.4 support for Travis.

lib/sidekiq.rb, lib/sidekiq/delay.rb, lib/sidekiq/extensions/generic_proxy.rb, lib/sidekiq/rails.rb, myapp/config/initializers/sidekiq.rb, test/test_actors.rb, test/test_api.rb, test/test_extensions.rb, test/test_testing.rb, test/test_testing_fake.rb, test/test_testing_inline.rb
The delay extensions give users a shortcut to creating jobs without explicitly defining a Sidekiq::Worker.  They have a few problems though:
1. They add several methods to Module so that calls to class methods can be delayed.  `Foo.delay.bar(args)`
2. They use YAML to marshal the arguments, allowing the user to marshal more complex arguments than Sidekiq::Worker allows.  This can accidentally lead to job payloads that are 100s of KB in size and more susceptible to network issues.  Add a warning message if the payload is over 4KB.
Do the following:
1. [x] Don't load the delay extensions by default.  The user must enable them in their initializer.
3. [x] Add a size check to the YAML marshal that warns at runtime if the args are larger than X.
=> Disable delay extensions by default, fixes #3174

Changes.md
I believe a custom handler added to `error_handlers` is supported functionality. The change in #3161 unknowingly broke some of our exception handling on retries, because we were expecting `context` to be `job`, whereas we now need to use `context[:job]` before pulling out job args.
```ruby
context["retry_count"]
context[:job]["retry_count"]
```
=> Mention the error handler context change in 4.2.3

.travis.yml, sidekiq.gemspec, test/helper.rb, test/test_web.rb, test/test_web_auth.rb, test/test_web_sessions.rb
Hey Mike, thanks for the chat today.
When you sign up to [Percy](https://percy.io), it'll do a pretty good job of guiding you through the environment variable and github integration steps.
For convenience, here's a couple of links to **Percy Docs**:
- [TravisCI](https://percy.io/docs/setup/travis-ci)
- [Capybara](https://percy.io/docs/clients/ruby/capybara)
The second commit in this PR configures Travis to only run Percy against the latest Ruby.  We got this from a reliable source, but haven't tested it.  If this doesn't "just work", let me know and I'll get it sorted.
If you strike any issues at all, let us know.  I'm on DM, or you can Mike & I via Intercom/Email.
=> Integrate Percy.io for visual regression tests

test/test_web.rb, web/views/retry.erb
Shows error class in corresponding table cell. Job's display class is still on the page, it is shown at the top of the page (in job details).
=> Show error class on retry page

lib/sidekiq/api.rb
The example for ScheduledSet was referring to the retry queue but it actually operates on the schedule queue.
=> Fix typo in API documentation

web/locales/ur.yml
Urdu locale added in sidekiq, some of the keywords like status, plugins, jobs, workers etc either didn't have exact mapping in Urdu language or their meaning doesn't make sense in the context of sidekiq so I better used them as it is in Urdu alphabets.
Thanks
=> Urdu locale added in sidekiq

web/locales/he.yml
My best crack at this.  Kudos to @M-Zuber for the Hebrew help.  Still looking for a native speaker to add a second opinion (there were some questions about singular/plural), but it'll also help to see it in Sidekiq Web and look for places these are used where I wasn't expecting.
=> Add Hebrew support

lib/sidekiq/client.rb, test/test_client.rb
I know `'at'` wasn't a documented argument for `Sidekiq::Client.push`, and maybe that was intentional.
We tried to use it passing a `Time` argument, and specs were passing but it raised at runtime with a `Redis::CommandError: ERR value is not a valid float`
```
/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/pipeline.rb:129:in `value'
/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/pipeline.rb:121:in `_set'
/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/pipeline.rb:63:in `block in finish'
/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/pipeline.rb:62:in `each'
/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/pipeline.rb:62:in `each_with_index'
/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/pipeline.rb:62:in `each'
/ruby/gems/2.4.0/gems/redis-3.3.3/lib/redis/pipeline.rb:62:in `map' …
```
=> Validate 'at' argument for Sidekiq::Client.push

sidekiq.gemspec
This removes `Timeout.timeout`: https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#333
=> Bump redis-rb to v3.3.3

lib/sidekiq/web/application.rb, lib/sidekiq/web/helpers.rb, test/test_web.rb, web/assets/javascripts/dashboard.js, web/views/_footer.erb
Hi there! First of all, thank you guys for the amazing work on Sidekiq, I really appreciate it.
I'm sending this small PR with a small change in Sidekiq Web Dashboard:
When I running my jobs, I keep an eye in dashboard to follow how it's going...and for debugging
purposes sometimes I want to know how much time a specific batch of jobs takes to run(from enquedued to processed) and
how many seconds it take...and I dont want to count the seconds by myself...So I thought updating the current time in footer would be a good ideia...even if I don't need to count the time...it's just a good thing so this reflect the current stats for current time.
I mean, this is a way to say "this stats are related to this current time"(if you let Sidekiq Dashboard opened for 1 hour for example, the date in …
=> Update footer UTC time in web dashboard polling refresh

Changes.md, lib/sidekiq/logging.rb, lib/sidekiq/processor.rb
This was previously exposed in JobLogger and Middleware::Server::Logging
but was inlined into Processor.
https://github.com/mperham/sidekiq/commit/701e06224cebfeeb1f9c84e3abd9b96263defa46
Useful, e.g. in this case:
https://github.com/mperham/sidekiq/issues/1786
=> Extract Processor#log_context to ease extending what's logged

lib/generators/sidekiq/templates/worker_spec.rb.erb
Should be two spaces instead of four.
=> Fix RSpec generated worker template indentation

Ent-Changes.md
Verified against #3471 that `until` is correct :)
=> Fixes a typo in release notes

lib/sidekiq/util.rb
In looking at some of our object space dumps, I noticed a number of these strings were being allocated and garbage collected in Ruby 2.3.3.
=> Freeze sidekiq_label string constant to prevent unnecessary allocations

lib/sidekiq/api.rb, lib/sidekiq/job_retry.rb, lib/sidekiq/processor.rb, test/test_dead_set.rb
Currently there are three different places which contain exactly the same piece of code that kills a job and cleans the morgue:
```
now = Time.now.to_f		
Sidekiq.redis do |conn|		
conn.multi do		
conn.zadd('dead', now, payload)		
conn.zremrangebyscore('dead', '-inf', now - DeadSet.timeout)		
conn.zremrangebyrank('dead', 0, - DeadSet.max_jobs)		
end		
end
```
Logic and magic words (`'dead'` for sorted set name) are spread around the codebase. Since all that code already depends on `DeadSet` class (`DeadSet.timeout` and `DeadSet.max_jobs`), we could just move the logic to `DeadSet#kill(job_payload)`.
\* I really wanted to also re-use `DeadSet#schedule` in `DeadSet#kill`, but it does `Sidekiq.dump_json(payload)` under the hood while we are already getting serialized data for all job kill …
=> Unified Job kill via Sidekiq::DeadSet#kill

lib/sidekiq/client.rb
Document the difference between using a class name string vs. a `Sidekiq::Worker`-based worker class. It wasn't obvious what the difference was without digging into the code.
I'm happy to change the wording, this was just a way to get the conversation started.
=> Add docs for the class argument of Sidekiq::Client.push

lib/sidekiq/processor.rb, test/test_processor.rb
Currently when a server middleware mutates arguments and then the job
fails, it will get re-queued with the mutated arguments, not the
original arguments.
This is unexpected and (IMO) faulty behavior as that same middleware
will now see the already-mutated arguments when the job gets executed
again.
This changes the behavior to use the pristine, unmutated jobs hash when
requeueing the failed job. It also includes a failing test case for the
old code.
=> When a middleware mutates arguments, retry with original args

Gemfile, test/test_redis_connection.rb
* Loosen Redis version dep to `>= 3.3.5, < 5`
* Bump redis-namespace for looser Redis version dep. Pending https://github.com/resque/redis-namespace/pull/136 gem release.
Use `redis.connection` where we can and fall back to `redis._client` where we need (to inspect timeout and scheme).
References #3617
=> redis-rb 4.0 support

README.md
The link to the Support page, for happy hour, is pointing to the incorrect url.
=> Fix support link in README.md

lib/sidekiq/rails.rb
Due to Sidekiq dropping support for Rails 3.2 I have added a warning to STDERR (similar to the one in testing.rb) about no longer supporting 3.2 for Server/Workers.
=> Added warning to STDERR if we detect Rails 3.x (< 4)

lib/sidekiq/api.rb, test/test_api.rb
Sorry for not having submitted and issue before, this was simple enough to explain better through code.
The current implementation of the #each method uses Redis.zrange to
paginate the iteration and use multiple lightweight calls. It performs
this pagination in descending score order, but each page is returned
from Redis in ascending order. The result is that the final iteration
through the whole set is not sorted properly. Here's an example with a
page of size 3:
Redis set: 1, 2, 3, 4, 5, 6, 7, 8, 9
JobSet.to_a: 7, 8, 9, 4, 5, 6, 1, 2, 3
This fixes it with barely no performance cost (each page is reverted in
Ruby) and all the items are perfectly sorted in descending score order.
=> JobSet#each goes through elements in descending score order

lib/sidekiq/redis_connection.rb
This is a semantic change to `verify_sizing`'s `ArgumentError` message in redis_connection.rb. 
In my mind, "must have" is more prescriptive than "really needs to have". The wording of the existing message implies that the program will continue run, but the user should do something differently in the future.
=> Change "really needs" to "must" in redis_connection.rb

Gemfile
The redis-namespace 1.6.0 released.
And gemspec allow installing 1.6.0.
https://github.com/mperham/sidekiq/blob/master/sidekiq.gemspec#L24
So there aren't necessary to lock master branch already.
=> update redis namespace

lib/sidekiq/exception_handler.rb, lib/sidekiq/processor.rb, test/test_processor.rb
Extends the `ExceptionHandler` to support multiple log levels and
additional context text in order to use it when the `Processor`
encounters an exception when fetching new work. The added options ensure
that the new behavior is fairly close to the old behavior (same log
level, same fetch error message).
Fixes mperham/sidekiq#3673
=> Use exception handler for logging for fetch exception

lib/sidekiq/exception_handler.rb, lib/sidekiq/processor.rb, lib/sidekiq/scheduled.rb, test/test_processor.rb
The change that Fixes mperham/sidekiq#3673 actually broke any existing
exception handlers due to differences in expected parameter count. This
fixes it explicitly which normally seems like it won't matter but there
are random monitoring gems that install their own sidekiq exception
handlers that I don't want to break.
Sorry I broke things. :(
=> Make error handler change fully backwards compatible

lib/sidekiq/cli.rb, test/string_config.yml, test/test_cli.rb
This ensures that keys in the Yaml file can be specified as either symbols or strings, but will always be treated as symbols after loading.
It tries to use ActiveSupport's `deep_symbolize_keys!` method if ActiveSupport is loaded, otherwise falling back to an inline version.
Closes #3672.
=> Symbolize all config.yml keys when loading

test/test_web_helpers.rb
Failure:
TestWebHelpers#test_available_locales [/home/vaibhav-dhoke/workspace/sidekiq/test/test_web_helpers.rb:96]:
--- expected
+++ actual
@@ -1 +1 @@
-["ar", "cs", "da", "de", "el", "en", "es", "fa", "fr", "he", "hi", "it", "ja", "ko", "nb", "nl", "pl", "pt-br", "pt", "ru", "sv", "ta", "uk", "ur", "zh-cn", "zh-tw"]
+["fa", "he", "it", "zh-cn", "ur", "en", "de", "uk", "ta", "fr", "ru", "cs", "sv", "hi", "ar", "da", "pt", "ja", "ko", "nl", "el", "nb", "es", "pl", "zh-tw", "pt-br"]
Ruby Version: ruby-2.4.1 [ x86_64 ]
OS: Ubuntu 16.04 LTS
rake test ran on cloned repo: https://github.com/vaibhavmdhoke/sidekiq
Bug: https://github.com/mperham/sidekiq/issues/3696
=> Sorting Of Available Locales

lib/sidekiq/processor.rb
I came across a bug where I could enqueue a Sidekiq worker from Rails, but Sidekiq couldn't load it.
There is a difference in how Sidekiq and Rails load constants - if a top level module of the same name was already loaded, then Sidekiq will use this instead of the more specific nested module.
I've made a simple fix in this PR, and here is an [example rails app](https://github.com/caffeinated-tech/sidekiq-autoload-example) where the bug can be reproduced.
Maybe the `constantize` method should be taken straight from `ActiveSupport::Inflector` as this handles even more edge cases involving inheritance (see [source](https://github.com/rails/rails/blob/e1a7260640295642108a364c2cfa56b6868d9947/activesupport/lib/active_support/inflector/methods.rb#L250)) But I think a copy-paste isn't ideal but …
=> change constantize method to match rails' version

web/locales/ja.yml
Rename `Dead`  from Hani to Kana. (Hani and Kana are [ISO 15924 ](http://unicode.org/iso15924/iso15924-codes.html))
There is no Japanese locale to match the dead.
Also, Add  `BackToApp` and `Latency`.
=> Fix japanese locale of web

Changes.md
If your changelog says "see issue for details", you should make it easy
for someone to get there.
=> Make links out of all issue numbers in the changelog

Changes.md, lib/sidekiq.rb, lib/sidekiq/api.rb, lib/sidekiq/cli.rb, lib/sidekiq/client.rb, lib/sidekiq/fetch.rb, lib/sidekiq/job_logger.rb, lib/sidekiq/launcher.rb, lib/sidekiq/logging.rb, lib/sidekiq/manager.rb, lib/sidekiq/processor.rb, lib/sidekiq/redis_connection.rb, lib/sidekiq/scheduled.rb, lib/sidekiq/util.rb, lib/sidekiq/web.rb, lib/sidekiq/web/action.rb, lib/sidekiq/web/application.rb, lib/sidekiq/web/helpers.rb, lib/sidekiq/web/router.rb, lib/sidekiq/worker.rb
Explicit freezing was required pre-Ruby 2.3.  With 2.3, `frozen_string_literal: true` is available to do the same thing without uglifying the code.
Caveat upgrader: this change will lead to increased memory usage and slower performance on Ruby 2.2.
=> Remove String#freeze calls

LICENSE
I was checking out your license and saw that link is no longer functional.
=> Fix pro version link

lib/sidekiq/cli.rb
Puts was used to push the signal name into the pipe, but puts implementation generates a "can't be called on trap context" exception on Windows.
=> Issue 3775 - Fixed Ctrl-C exception on Windows.

lib/sidekiq/job_retry.rb, test/test_retry.rb
Hi, Mike!
Want to have possibility to use default retry interval for case like this:
```ruby
class TwitterWorker
include ::Sidekiq::Worker
sidekiq_options queue: :twitter,
unique: :until_executing,
retry: 3
sidekiq_retry_in do |_count, exception|
case exception
when Twitter::Error::TooManyRequests
exception.rate_limit.reset_at - Time.now
else
raise 'Use default intervals'
end
end
def perform(project_name)
end
end
```
And defining `sidekiq_retry_in` for now does not allow to use default interval calculation (except the using ugly workaround - raise error
Will be great to have the way to say to `JobRetry` use default calculated interval, for example by returning nil:
```ruby
sidekiq_retry_in do |_count, exception|
case exception
when Twitter::Error::TooManyRequests …
```
=> Use default retry interval in sidekiq_retry_in

lib/sidekiq/redis_connection.rb, test/test_redis_connection.rb
This is a follow up to #2985 (52828e4) adding similar support for the client connection pool. For Rails servers, Sidekiq is not loaded from the CLI so the prior change to support setting the concurrency via `RAILS_MAX_THREADS` is not applied to the web server process. This means for Rails servers which do not configure a custom size through an initializer they will run with the default connection pool size of 5.
When the Rails server runs the initial Redis connection may be made through `Sidekiq::Client` (e.g. from [`ActiveJob::QueueAdapters::SidekiqAdapter`](https://github.com/rails/rails/blob/v5.1.5/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L20)). This causes the `redis_pool` to be initialized without any options, setting the pool size to the default of 5. …
=> Use `RAILS_MAX_THREADS` for client pool size

lib/sidekiq/web/helpers.rb
I was working on a middleware for the web UI that swaps the redis pool using `Sidekiq::Client.via` + `Sidekiq.redis=`. Everything appears to work correctly except the namespace in the footer.
This PR changes the web helpers namespace memoization to use an instance variable instead of class variable.
=> Memoize web helpers namespace with instance variable instead of class variable

lib/sidekiq/testing.rb
I have meet the issue in testing environment with sidekiq and https://github.com/marshall-lee/sidekiq-postpone.
There are some test to reproduce the issue https://github.com/moofkit/reproduce_sidekiq_postpone_issue/blob/master/spec/integration_testing_spec.rb#L30
```
bundle exec rspec
.F
Failures:
1) integration spec testing disabled overflows stack
Failure/Error: MyWorker.perform_async
SystemStackError:
stack level too deep
Finished in 0.00677 seconds (files took 0.14778 seconds to load)
2 examples, 1 failure
Failed examples:
rspec ./spec/integration_testing_spec.rb:28 # integration spec testing disabled overflows stack
```
the reason of this issue that both `Sidekiq::Testing` module and [sidekiq-postpone](https://github.com/marshall-lee/sidekiq-postpone/blob/master/lib/sidekiq/postpone/c …
=> change alias method to prepend in testing module

web/views/layout.erb
I have seen corrupted Web UI on Internet Explorer 11(locale: ja).
According to [MDN document](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta), `charset` must contain a [standard IANA MIME name for character encodings](https://www.iana.org/assignments/character-sets/character-sets.xhtml).
So I changed `charset`, and get correct view.
Regards.
=> fix charset attribute of Web UI meta element

web/locales/es.yml
In Spanish "queue" can be translated as "cola" or "fila". The latter translation has a meaning of "aligning some objects" (like "row" in English).
=> Update ES translation

Changes.md, lib/sidekiq/scheduled.rb
Today we add 50% to the sleep time so that processes cluster around the target time:
50% --> target <-- 150%
This works well for small clusters, e.g. less than 10 processes.
The problem is that, for large clusters, the processes will never sleep less than 50% of (process_count * poll average) which breaks the average and delays job scheduling for several minutes.
Instead, beyond 10 processes, don't add that 50% buffer.  Allow the processes to sleep anywhere within the timespan:
0% --> target <-- 200%
With many processes, the average sleep within a 200% time period should work out close enough to 100%.
=> Better scheduling for large clusters, fixes #3889

lib/sidekiq/web/application.rb, test/test_web.rb
Given that the Sidekiq admin does not define it's own Content-Security-Policy, if a parent application is using a CSP, e.g. in Rails 5.2, the parent policy will be used for the admin pages. This may cause problems with the admin pages, depending on the application policy.
=> Add CSP header to web admin to ensure it matches needs

web/views/queue.erb
=> Add queue size to web show page

Changes.md, lib/sidekiq/cli.rb, test/test_cli.rb
=> Raise error for duplicate queue names in config, fixes #3911

lib/sidekiq/redis_connection.rb, test/test_redis_connection.rb
Redis stores its loaded drivers in `Redis::Connection.drivers` and uses the
last one of them when initializing a new client. Sidekiq always uses `'ruby'`
(or `Redis::Connection::Ruby`) per default, though.
With this commit we are following redis' default by passing the last
loaded driver per default (or a given `:driver`).
Closes #3944.
=> Use redis' default driver

Changes.md, lib/sidekiq/processor.rb, test/test_launcher.rb
On jruby, the Hash implementation is not threadsafe, and leads to jobs not being
deleted from the busy list.
See #3958
=> Use a mutex to synchronize access to shared WORKER_STATE hash

web/assets/javascripts/dashboard.js
Sidekiq dashboard resets the graph on `resize` events whether it is a height change or a width change. This causes some unexpected behaviours. 
- When the direction of the scroll changes on a mobile browser say Chrome for Android, the browser automatically hides/displays the address bar. This change triggers a resize event (due to height changes), which in-turn resets the realtime graph on the main dashboard page.
- The same behaviour can be observed on desktop browsers in full screen mode on a Mac, when the menubar is hidden and then displayed on hovering over it.
- Almost all of the times, we need to reset the graphs only when the width changes. So, we can trigger the reset functionality only when the `innerWidth` of the window changes. This way we can remove the unexpected/unwanted …
=> Fix RealTime Graphs Reset on Window Height Change

sidekiq.gemspec
All changes conform require ruby version `>= 2.2.2`
- `# -*- encoding: utf-8 -*-` source encoding UTF-8 is a default since Ruby `1.9+`
- `require_relative 'lib/sidekiq/version'` is a shorter version
- `gem.test_files` spec option is not used anymore
- `gem.require_paths = ["lib"]` is a spec option [default](https://guides.rubygems.org/specification-reference/#require_paths=)
- Add `rack` gem as an explicit runtime dendency, because Web UI actually dependes on `rack` builder and `rack-protection` is only a part of that stack, which is responsible for security.
=> Cleanup Gem Spec

lib/sidekiq/web/application.rb
The current CSP policy for Sidekiq Web appears to block the inline
script that renders the history charts for bucket limits.
This change updates the script CSP rules to match the style CSP rules to
allow the chart to successfully render. In our application this change
made the bucket charts load successfully.
cc: #3913, #4030 
CSP warnings before fix:
=> Add unsafe-inline CSP to allow bucket graph to display

lib/sidekiq/cli.rb, test/dummy/config/sidekiq.yml, test/test_cli.rb
Ispired by #4047, Fixes #3735.
Parse `sidekiq.yml[.erb]` only in case:
- `:config_file` is not present as CLI argument
- `:require` is a directory (Rails application)
-  Expanded path to `config/sidekiq.yml[.erb]` against `:require` exists
Example when default config file is considered:
```
$ tree haiku
haiku
└─ config
└─ sidekiq.yml
$ sidekiq -v -r ./haiku
...
:require => "./haiku"
:config_file => "/Users/tensho/Projects/sidekiq/haiku/config/sidekiq.yml"
...
```
=> Check Config File Existence

.travis.yml, lib/sidekiq/cli.rb, test/dummy/config/sidekiq.yml, test/test_cli.rb
Fixes #4075
To find out the config file dir we make the next assumptions with the corresponding precedence:
1. CLI `:require` option is an existing dir – take it for `config/sidekiq.yml`
2. CLI `:require` option is a file – take default Sidekiq`:require` option  – `.` (current directory)
3. CLI `:require` option is ommitted – take default Sidekiq`:require` option  – `.` (current directory)
In tests we stub default Sidekiq `:require` option (`.`) with the dummy app folder (`./test/dummy`).
=> Consider Default Required Path on Config File Search

lib/sidekiq/job_retry.rb, test/test_retry.rb
When developers create custom error classes, there is potential for the `message` method to raise an error. Exception Inception!
```ruby
class BadError < StandardError
def message
"Hello World" + foo
end
end
```
Of course, this is not the fault of Sidekiq, however we do [rescue errors that an error handler may throw when logging](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/exception_handler.rb#L22). Other error handling libraries do not account for these mistakes, but Sidekiq jobs that throw errors with bad messages will end up not retrying ever.
=> Rescue StandardErrors raised from exception's message

6.0-Upgrade.md, lib/sidekiq.rb, lib/sidekiq/cli.rb, lib/sidekiq/logger.rb, test/test_logger.rb
Close #4081
It's reasonable to keep the same configuration option name as in Rails – `log_formatter`. I'd consider "format" as something like this `"%s tem %s plate"`, and "formatter" is an instance that operates on the format.
=> Pluggable Log Formatter

web/views/queues.erb
The latency time for queues when viewing /sidekiq/queues was previously listed in seconds.  This pull request formats this time in seconds, minutes, or hours, using the same code that is used elsewhere (ie. /sidekiq/busy) for formatting time.
=> Format latency

Changes.md, lib/sidekiq/job_retry.rb, lib/sidekiq/processor.rb
Under just the right conditions, we could lose a job:
- Job raises an error
- Retry subsystem catches error and tries to create a retry in Redis but this raises a "Redis down" exception
- Processor catches Redis exception and thinks a retry was created
- Redis comes back online just in time for the job to be acknowledged and lost
That's a very specific and rare set of steps but it can happen.
Instead have the Retry subsystem raise a specific error signaling that it created a retry.  There will be three common cases:
1. Job is successful: job is acknowledged.
2. Job fails, retry is created, Processor rescues specific error: job is acknowledged.
3. Sidekiq::Shutdown is raised: job is not acknowledged
Now there is another case:
4. Job fails, retry fails, Processor rescues Exception: job is …
=> Explicitly signal that we handled an exception with a retry, fixes #4138

lib/sidekiq/client.rb
I modified variable name `q` to be easy to read.
=> change to easy-to-understand variable name queue

lib/sidekiq/testing.rb
I noticed that the `Sidekiq::Worker.queue` defined by `sidekiq/testing` was using the `sidekiq_options` writer instead of the `get_sidekiq_options` reader. This could be a problem if an implementor expected to use `sidekiq_options` only as a writer.
Here's a contrived example of an implementor ensuring that a queue is always explicitly configured:
```ruby
require "sidekiq"
class MyBaseWorker
include Sidekiq::Worker
def self.sidekiq_options(**opts)
raise "always specify queue!" unless opts.key?(:queue)
super
end
end
class MyWorker < MyBaseWorker
sidekiq_options retry: 3, queue: :my_queue
end
class MyQueuelessWorker < MyBaseWorker
sidekiq_options retry: 3             # 💣 always specify queue! (expected)
end
require "sidekiq/testing"
puts MyWorker.queue                    # 💣 always specify …
```
=> Use options reader to fetch queue name in test

lib/sidekiq/worker.rb, lib/sidekiq/worker/options.rb, test/test_rails.rb
[An exception was introduced](https://github.com/mperham/sidekiq/commit/c685d6928ca6aec1f7569ff69871ef9a8dfb2738) that is raised on an attempt to include `Sidekiq::Worker` to an `ActiveJob::Base` descendant.
That was done in order to prevent options not supported by ActiveJob, specifically `queue` (also `pool` doesn't seem to make any effect). See #2424.
Support for `set` [was added later on](https://github.com/mperham/sidekiq/commit/d6538b0b4f3c419ea969dc6710c6431b76a05d2b), including the setting of `retry` from Active Job.
This change bridges the gap by allowing `ActiveJob::Base` descendants to include `Sidekiq::Options` and use `retry` option of `sidekiq_options`, and also `sidekiq_retry_in`, and `sidekiq_retries_exhausted`.
=> Allow Sidekiq retry options in ActiveJob

Changes.md, lib/sidekiq/client.rb, test/test_client.rb
This adds ability to push jobs in bulk with different delays for each.
```ruby
Sidekiq::Client.push_bulk("class" => FooJob, "args" => [[1], [2]], "at" => [1.minute.from_now.to_f, 5.minutes.from_now.to_f])
```
This was also requested before in #4187 and #4096
=> Support Client.push_bulk with different delays

lib/sidekiq.rb
I ran tests locally and encountered a lot of noise in output
<details>
<summary>click</summary>
```
.......omitted......
/Users/fatkodima/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
/Users/fatkodima/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
/Users/fatkodima/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
/Users/fatkodima/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
/Users/fatkodima/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
/Users/fatkodima/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:159:in …
```
=> Do not reset the whole logger when format changes

bin/sidekiqload
```
$ bin/sidekiqload
Traceback (most recent call last):
bin/sidekiqload:8:in `<main>': uninitialized constant Bundler (NameError)
```
And `toxiproxy` and `hiredis` are not loaded from `load_test` Gemfile group
=> Fix sidekiqload loading error

Changes.md, lib/generators/sidekiq/worker_generator.rb, test/test_worker_generator.rb
Currently, when tests generation is disabled for a rails app, sidekiq nevertheless generates ones. 
And this pr also fixes (like rails itself does) extra suffix generation for worker name.
```diff
$ rails generate sidekiq:worker stripe_worker
Running via Spring preloader in process 62280
-      create  app/workers/stripe_worker_worker.rb
+      create  app/workers/stripe_worker.rb
-      create  test/workers/stripe_worker_worker_test.rb
+      create  test/workers/stripe_worker_test.rb
```
=> Respect rails' generators `test_framework` option and gracefully handle extra `worker` suffix on generator

lib/sidekiq/logger.rb, lib/sidekiq/processor.rb
Using `bin/sidekiqload` with `memory_profiler` I got:
**Before**:
```
Total allocated: 952250916 bytes (10115468 objects)
Total retained:  12802918 bytes (2000 objects)
```
**After**:
```
Total allocated: 934688905 bytes (9715635 objects)
Total retained:  12822122 bytes (2185 objects)
```
Memory savings = `(952250916 - 934688905) / 952250916.0 * 100 ~ 2%`
Object allocations reduced by = `(10115468 - 9715635) / 10115468.0 * 100 ~ 4%`
And time savings i have seen are also `~4%`.
Those savings are a bit smaller than in previous pr, but taking into account the simple changes, I think it's worth considering. 
Also line
```ruby
constant.const_defined?(name, false) ? constant.const_get(name, false) : constant.const_missing(name)
``` 
is a bit redundant, since `const_get(name, false)` calls …
=> Reduce allocated objects

Changes.md, lib/sidekiq/api.rb, lib/sidekiq/job_retry.rb, test/test_api.rb, test/test_retry.rb, web/views/dead.erb, web/views/retry.erb
About implementation: Originally, I was thinking about implementing ability to enable/disable this feature (globally and per worker), allowing to configure threshold when to consider compressing (also globally and per worker). But this quickly became more complicated than needed. And i realized, I can't imagine real use cases when it would have benefit to disable compression or change its compression threshold instead of *always* do the compression.
So I chose the easy and simple way of always do the compression. My implementation will also handle jobs having error_backtrace in previous (array) format.
So lets firstly discuss implementation, then i would add tests and changelog entry.  
Closes #4270
=> Compress jobs backtraces

lib/sidekiq/api.rb, test/test_api.rb
Allow `score` to be a timestamp or a `Range` object. We have found this useful for helping us locate a job we know exists in a narrow time range.
=> Allow `fetch` to take a `Range` object to help narrow the search for a job

Changes.md, lib/sidekiq/api.rb, lib/sidekiq/client.rb, lib/sidekiq/job_logger.rb, lib/sidekiq/logger.rb, lib/sidekiq/web/helpers.rb, test/test_api.rb, test/test_client.rb, test/test_job_logger.rb, test/test_web.rb, web/views/_job_info.erb, web/views/busy.erb, web/views/morgue.erb, web/views/queue.erb, web/views/scheduled.erb
Honestly, I can't figure out an example of a use case, which can not be replaced (with some hacks or not) by extending job payload. But it seems dirty for me, for example, to pass unused arguments to just show them in UI. Or, if, for example, job already accepts some `tenant_id` or `client_id`, I don't want to additionally pass `name` argument to just see name (instead of raw id) on ui.
Tags can be used for different use cases: to categorizing jobs, for example, by subdomain, tenant, country, locale, application, version, user/client, "alpha/beta/pro/ent", types of jobs, teams/people responsible for jobs, additional metadata (something like "do not stop this"), etc. 
This can be used as:
```ruby
class SomeApiWorker
sidekiq_options queue: "api", tags: ["unreliable"]
...
end …
```
=> Support job tags

lib/sidekiq/cli.rb
If I want to extend/change cli options, I should monkey-patch the whole large `parse_options` method and keep it up with future versions. But by extracting OptionParser into separate method, I can now more easily extend it's behavior, like:
```ruby
module SidekiqExtension
def option_parser(opts)
super.on("-l", ...)
end
end
class Sidekiq::CLI
include SidekiqExtension
end
```
=> Extract #option_parser method in CLI for better extensibility

Changes.md, lib/sidekiq/testing.rb, test/test_testing_fake.rb
I have found this problem was discussed before in [2934](https://github.com/mperham/sidekiq/issues/2934)
I also disabled rubocop check (failing, but not relevant to this pr), because `ensure` can not be used inside curly braces. Personally, I don't see much value in that cop.
=> Easier way to test enqueuing specific ActionMailer and ActiveRecord delayed jobs

Pro-Changes.md
This fixes the fact that the 6.0 upgrade note link is broken when viewed on GitHub.com. I assume this file is meant to be read on GitHub and not somewhere else, which means that the links should work on GitHub and point to GitHub. If that's not the case, then I'm not sure what the target should be (or if it needs to be fixed at all).
=> Fix not-clickable link to 6.0 upgrade notes

lib/sidekiq/processor.rb
Profiling `bin/sidekiqload`, I got:
For cpu:
**Before**:
```
==================================
Mode: cpu(1000)
Samples: 15951 (1.51% miss rate)
GC: 1804 (11.31%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
10483  (65.7%)       10483  (65.7%)     Hiredis::Ext::Connection#read
2226  (14.0%)        2226  (14.0%)     Sidekiq::Processor#cloned
1804  (11.3%)        1804  (11.3%)     (garbage collection)
704   (4.4%)         704   (4.4%)     #<Module:0x00007fd0ae32f718>.parse
137   (0.9%)         107   (0.7%)     Sidekiq::LoggingUtils#add
75   (0.5%)          75   (0.5%)     Redis::Connection::Hiredis#write
67   (0.4%)          67   (0.4%)     Sidekiq::Processor#constantize
59   (0.4%)          59   (0.4%)     Redis::Connection::Hiredis#timeout=
10792 …
```
=> Optimize cloning of job payload

web/locales/de.yml
Added translations for strings that were present in [en.yml](https://github.com/mperham/sidekiq/blob/master/web/locales/en.yml) but not in de.yml
Changed "töten" into "vernichten", because "töten" literally means to take someone's life. As a native speaker, I think "vernichten" sounds more appropriate here.
=> Extended translations for german

lib/sidekiq/api.rb
This eliminates probability of job being lost when `delete` succeeds but `schedule` fails, and reduces redis roundtrips to 1.
=> Improve fault tolerance of rescheduling jobs using API

lib/sidekiq/processor.rb
Prefer the faster Array#map to a manual implementation
* On the benchmark from #4303 on MRI 2.6.4,
before 396657.9 i/s, after 461013.3 i/s (1.16x faster).
This is also faster on JRuby and TruffleRuby.
See for https://github.com/mperham/sidekiq/pull/4303#issuecomment-538761252 for more details.
* Use `duped` as the return value in the only branch it's needed
=> Prefer the faster and more idiomatic Array#map in json_clone

lib/sidekiq/processor.rb
Another 20% speedup.
```ruby
require "benchmark/ips"
def deep_dup(obj)
if Integer === obj || Float === obj || TrueClass === obj || FalseClass === obj || NilClass === obj
return obj
elsif String === obj
return obj.dup
elsif Array === obj
duped = Array.new(obj.size)
obj.each_with_index do |value, index|
duped[index] = deep_dup(value)
end
elsif Hash === obj
duped = obj.dup
duped.each_pair do |key, value|
duped[key] = deep_dup(value)
end
else
duped = obj.dup
end
duped
end
def deep_dup_optimized_hash(obj)
if Integer === obj || Float === obj || TrueClass === obj || FalseClass === obj || NilClass === obj
return obj
elsif String === obj
return obj.dup
elsif Array === obj
duped = Array.new(obj.size)
obj.each_with_index do |value, index|
duped[index] = deep_dup_optimized_hash(value)
end
elsif Hash …
```
=> Faster Hash duping in #json_clone

test/test_job_logger.rb
A previous commit removed usage of this helper method within the job_logger test, delete the method too.
=> Remove unused test helper.

lib/sidekiq/job_retry.rb, lib/sidekiq/processor.rb, test/test_retry.rb, test/test_retry_exhausted.rb
These are the easiest changes that I figured out. But I'm wondering, won't we broke something changing `#dispatch` method's signature?
**Cpu**
**Before**:
```
==================================
Mode: cpu(200)
Samples: 59013 (1.43% miss rate)
GC: 0 (0.00%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
26104  (44.2%)       26104  (44.2%)     Hiredis::Ext::Connection#read
6377  (10.8%)        6377  (10.8%)     #<Module:0x00007f882c32be58>.parse  <==========
34450  (58.4%)        4886   (8.3%)     Redis#_bpop
3218   (5.5%)        3218   (5.5%)     Redis::Connection::Hiredis#write
2788   (4.7%)        2788   (4.7%)     Sidekiq::Processor#json_clone <===========
2585   (4.4%)        2585   (4.4%)     Sidekiq::Processor#constantize
40383  (68.4%)        2292 …
```
=> Refactor Processor to avoid costly json cloning

lib/sidekiq/api.rb, lib/sidekiq/job_retry.rb, test/test_api.rb
**For not so large backtrace**:
```
bin/sidekiqload:33:in `perform'
/Users/mikeperham/src/sidekiq/lib/sidekiq/processor.rb:193:in `execute_job'
/Users/mikeperham/src/sidekiq/lib/sidekiq/processor.rb:161:in `block (2 levels) in process'
/Users/mikeperham/src/sidekiq/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/mikeperham/src/sidekiq/lib/sidekiq/processor.rb:160:in `block in process'
/Users/mikeperham/src/sidekiq/lib/sidekiq/processor.rb:133:in `block (6 levels) in dispatch'
/Users/mikeperham/src/sidekiq/lib/sidekiq/job_retry.rb:107:in `local'
/Users/mikeperham/src/sidekiq/lib/sidekiq/processor.rb:132:in `block (5 levels) in dispatch'
/Users/mikeperham/src/sidekiq/lib/sidekiq.rb:37:in `block in <module:Sidekiq>'
/Users/mikeperham/src/sidekiq/lib/sidekiq/processor.rb:128:in `block …
```
=> Dump error backtraces as json before compressing

lib/sidekiq/cli.rb
Make is clearer that the redis version error message refers to the version of the server, not the redis gem.
=> Make the redis server version error clearer

lib/sidekiq/job_retry.rb
As discussed in the [Global death_handler called before job is sent to morgue](https://github.com/mperham/sidekiq/issues/4362) issue.
=> send job to morgue before calling death handlers

lib/sidekiq/redis_connection.rb
Use SafeNavigation for possible missing value
Context: CI was failing because of StandardRB Rules
```
#!/bin/bash -eo pipefail
bundle exec rake
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
standard: Run `rake standard:fix` to automatically fix some problems.
lib/sidekiq/redis_connection.rb:106:9: Style/SafeNavigation: Use safe navigation (`&.`) instead of checking if an object exists before calling the method.
```
=> Fixes CI build

lib/generators/sidekiq/worker_generator.rb, test/test_worker_generator.rb
Verifying that `RSpec` is defined assumes that the library is loaded on
the same environment that the generator is running.
It is often common to not have the rspec gem required on development,
which is the default environment to run the generator from.
Following the configured generator removes the assumption and works as
expected without breaking expectations.
=> Follow generator configuration to determine the resulting test file

lib/sidekiq.rb, lib/sidekiq/api.rb, lib/sidekiq/web/application.rb, test/test_web.rb, web/locales/en.yml, web/views/queues.erb
Considering sidekiq web UI allow to perform complex tasks with ease.
Having the ability to pause a queue during an emergency (or operational intense)
scenarios would come in quite handy.
This PR introduces a new button to under the "Actions" column on `sidekiq/queues` pages,
right next to the `Delete` button. Depending on the state of the queue, it will according
show the `Pause` or `Unpause` text, with appropriate form element that `POST`s to the same
endpoint. The endpoint logic is updated to handle the new cases. Added some relevant unit tests.
Adding mock `Sidekiq::Queue#pause!` and `Sidekiq::Queue#unpause!` functions to
the API, which I believe will be overridden by sidekiq pro.
Original request: https://github.com/mperham/sidekiq/issues/4343
**Examples**
**Open questions**
- Maybe …
=> Introduce the ability to pause queue from the UI

lib/sidekiq/logger.rb, test/test_logger.rb
Since you can pass kwargs to Logger.new, you need to explicitly handle them in the subclass otherwise you get a warning.
=> Silence Ruby 2.7 warnings

lib/sidekiq/web.rb
=> Fix Rack::File deprecation

examples/systemd/sidekiq.service
With `Type=simple` systemd marks the service as started immediately.
Together with instant restart, it may fool monitoring tools and deployment scripts in case of a problem with sidekiq, resulting in all workers being considered as deployed, but actually failed.
Add a comment describing an alternative configuration with `Type=notify` and a reference to configuration that will notify systemd when sidekiq workers have actually started and are ready to process jobs. With this configuration `systemctl start sidekiq` command will actually wait for sidekiq worker to be able to process jobs.
@mperham WDYT?
=> Type=notify alternative in sidekiq.service systemd example

Changes.md, lib/sidekiq/api.rb, lib/sidekiq/launcher.rb
This makes deleting/clearing large queues much faster.
=> Use `unlink`, not `del`, for performance

lib/sidekiq/ctl.rb
With the refactoring done in the commit 4d883194350cf9202ff5c1650730dfa5ee3d2e06, the `sidekiqctl` command was crashing with the error `NameError: uninitialized constant Sidekiq::Ctl::Sidekiqctl` which this commit solve.
This PR solves the issue #4456.
=> Fixes regression after refactoring (Closes #4456)

lib/sidekiq/logger.rb, test/test_logger.rb
The `LoggingUtils` module has incorrect implementations of the level inspection methods.
These should return true if the current level is *lower* than the checked level (e.g. `info?` returns true if the current level is `Logger::DEBUG`).
=> Fix logger level query methods

Changes.md
Hello,
First of all, thanks so much for Sidekiq; it's a wonderful piece of software.
Unfortunately upgrading from `6.0.4` to `6.0.5` was a breaking change for us. We, regrettably, vary `APP_ENV` between Staging & Production environments as a basic feature-flag, but not `RAILS_ENV` (which is always production).
This is a foible in our codebase, however we didn't spot this the changlog section when updating via Dependabot, so I've added it to hopefully save someone else the same potential issue.
Thanks again 😃
=> Document APP_ENV changes in 6.0.5

web/locales/lt.yml
I was inspired by the Russian OSS community when I saw the Sidekiq dashboard localized in Russian. 
Hence I decided to provide locales for my fellow Lithuanian colleagues working with Sidekiq.
Adding a screenshot too:
=> Add Lithuanian locale

Changes.md, lib/sidekiq/launcher.rb
A fix for https://github.com/mperham/sidekiq/issues/4498 introduced a callback that is executed at ruby VM exit and tries to connect to redis.
This callback is also executed in CI runs and in all other cases where sidekiq is loaded but not used with real redis.
As a work-around, keep the at_exit hook but communicate to redis only if there is something to send, i.e. the number of processed or failed jobs is greater than zero
=> Do not connect to redis at exit if not needed

examples/systemd/sidekiq.service
I'm not 100% sure if my comment in `sidekiq.service` is right but in my case (I'm using Sidekiq 5.x) my Sidekiq process kept getting restarted every 5 seconds until I removed the `WatchdogSec=5` line. Assuming that removing that line is the right move for Sidekiq < 6.0.6, it seems like it would be nice if there were instructions saying so.
=> Add suggestion to remove WatchdogSec=5 line for Sidekiq < 6.0.6

Changes.md, lib/sidekiq/redis_connection.rb, test/test_redis_connection.rb
In 3f9c4bf9 the Redis connection options began to be cloned (via dumping
and re-marshalling) to avoid issues with password redaction in logging
altering the connection options and breaking authentication with Sentinels.
Unfortunately, this change caused an exception on boot for users of
Redis over SSL. The `OpenSSL::X509::Store` object used for SSL certs is
not yet dumpable in the bundled OpenSSL wrapper for current Rubies
(although it does in master as of ruby/openssl#281).
The fix here prunes the `ssl_params` options out of the Redis
configuration options before the dumping and marshalling. It's probably
better not to include those in logging anyway for privacy purposes.
Fix #4531
=> Remove SSL parameters from Redis connection logging to avoid exception

Changes.md, lib/sidekiq/web.rb
6.0.5 removed `Sidekiq::WebApplication`'s own Content-Length header calculation, expecting Rack to do it instead via some middleware (https://github.com/mperham/sidekiq/commit/675e40c32684a7e89987673b82b5241545763fcb). This was to fix an issue where New Relic would inject content into Sidekiq's Web UI after the hand crafted content length was calculated (#4440). While such middleware exists, it's not enabled by default (at least in a Rails app) and so the HTTP response doesn't have the header at all.
The absence of the header has caused unexpected behaviour in an nginx and HAProxy setup we use in production systems, causing each page load to take exactly 20 seconds. The suspicion is that, without the Content-Length response header, HAProxy waits a preset amount of time before deciding the …
=> Ensure Rack::ContentLength is loaded as middleware

Changes.md, web/assets/stylesheets/application-dark.css, web/assets/stylesheets/application.css
* "Polling Interval" slider not visible in Safari / Firefox
* Dark background not full height in Firefox
(add color to html tag, use !important since default is !important)
* "Success" banner not visible
* Graph vertical bars (both static and hover bars) not visible
* Make UI a little more consistent with light mode
* Slightly lighten background, for a differing color between
header/footer and body.
* Add shadow and different color to "status" bar
_Note: The slider on light mode subtly changed, to support dark mode consistently_
=> Dark mode fixes

lib/sidekiq/redis_connection.rb
In dd0a8476 we started filtering out SSL params from the Redis options
cloning for logging purposes to prevent an undumpable
`OpenSSL::X509::Store` from raising an exception. The fix used
ActiveSupport's `Hash#except` to exclude the `:ssl_params` key from the
hash before cloning the options hash by dumping and reloading.
As ActiveSupport is not a requirement for Sidekiq, we need a more
generally-available solution. This change removes the key using
`Hash#slice` by including every top-level options key _except_
`:ssl_params`.
See https://github.com/mperham/sidekiq/pull/4532#issuecomment-620894721
cc: #4532
=> Exclude :ssl_params from Redis options clone without ActiveSupport

test/test_cli.rb
This change adds (missing) test cases for `Sidekiq::CLI` when
1. An invalid (`<=0`) value for `concurrency` is supplied.
1. An invalid (`<=0`) value for `timeout` is supplied.
=> Add tests for invalid concurrency and timeout setting

Changes.md, lib/sidekiq/cli.rb, test/test_cli.rb
This change has been made because:
By default, sidekiq sets a `default` queue when no queue has been specified via `-q` or the `config.yml` file.
To set this `default` queue, we currently a`.empty?` check on `opts[:queues]` after performing a `.nil?` on the same object.
But, this `.empty?` check is redundant, because according to the current code and its execution flow, `opts[:queues]` cannot be `empty`, it can only be `nil`
In the beginning: There was only a `.empty?` check: 
Eg: https://github.com/mperham/sidekiq/blob/v5.0.0/lib/sidekiq/cli.rb#L278
Here, `.empty?` was a valid check, because the queues specified via `-q` or the `config.yml` file was already merged with the [default sidekiq options](https://github.com/mperham/sidekiq/blob/v5.0.0/lib/sidekiq.rb#L19) (which has `queues` set …
=> Remove a redundant`.empty?` check before setting `default` queue

Changes.md, lib/sidekiq.rb, lib/sidekiq/cli.rb, test/config_queues_without_weights.yml, test/test_cli.rb
In sidekiq, the queues specified via `-q` takes precedence over the queues mentioned via the `config` file.
> Options passed on the command line will also override options specified in the config file.
Also, Sidekiq follows "strict ordering" for queues, if the queues are specified without weights. This means that jobs in the next queue are processed only if the previous queues are empty. This is tracked internally using `Sidekiq.options[:strict]`
> If you want queues always processed in a specific order, just declare them in order without weights: As arguments...
> sidekiq -q critical -q default -q low
In a scenario where the config file contains weighted queues, but non-weighted queue names are specified via the `-q` option, Sidekiq currently does not set the value of …
=> Fix: Ensure `strict` order is followed when queues without weights are specified via the `-q` option

lib/sidekiq/cli.rb, test/config_with_internal_options.yml, test/test_cli.rb
Sidekiq allows to set config options via the `config.yml` file. However, presently any `key` present in the config file will be parsed and it's value will be set while reading the config file.
While this is harmless for the most part, there are some options which are set internally, based on internal logic - these options should not be allowed to be set via the `config` file, as the value specified via the config file could be different from what would have been set via Sidekiq's internal logic.
One such option is `strict` - which specifies whether Sidekiq should follow strict ordering for the queues when processing jobs.
In a scenario where we specify non-weighted queues, `strict` is supposed to be set to `true`.
Currently, it is possible to set `strict` via the `config` file. As an …
=> Do not allow to set  internal options via the config file

lib/sidekiq/rails.rb
If the application has already been loaded before this file is required, the `after_initialize` callback runs immediately, but the Reloader class isn't defined yet.
In our case, this happens because we're preloading our application code before invoking Sidekiq Enterprise's sidekiqswarm command, to maximise the copy-on-write memory savings.
Also remove a comment about `cache_classes` that has been irrelevant since https://github.com/mperham/sidekiq/pull/3235.
=> Define Reloader class before callback that uses it

sidekiq.gemspec
[[CVE-2020-8161] Directory traversal in Rack::Directory](https://groups.google.com/d/msg/ruby-security-ann/T4ZIsfRf2eA/h32aSPjcBAAJ)
=> Allow newer rack version due to directory traversal security bug

lib/sidekiq/extensions/active_record.rb, lib/sidekiq/extensions/class_methods.rb, lib/sidekiq/sd_notify.rb
This PR improves a small part of the documentation using YARD annotations.
- use the Example functionality for syntax highlighting
- use backticks for code in Markdown
- fix a typo which made the `return` disappear
=> (docs) YARD annotations

lib/sidekiq/redis_connection.rb, lib/sidekiq/web/helpers.rb, lib/sidekiq/worker.rb
We were debugging something when found this piece of code in the `Sidekiq::Worker` class:
```ruby
item.keys.each do |key|
item[key.to_s] = item.delete(key)
end
```
Since the oldest supported version now is Ruby v2.5 and this version added the `Hash#transform_keys` method, we considered changing it to use the standard method, easier to read. Also, it looks like it brings some performance improvements, from 0 to 20% depending on the execution.
Here the benchmark code:
```ruby
require "benchmark/ips"
def stringify(item)
item.keys.each do |key|
item[key.to_s] = item.delete(key)
end
end
def stringify_optimized(item)
item.transform_keys(&:to_s)
end
item = {:queue=>"low", "class"=>"RandomWorker", "args"=>["foo", "bar"], "at"=>1590166226.951523}
10.times do |i|
puts("Report ##{i}")
Benchmark.ips …
```
=> Optimize stringify item before pushing it

Gemfile, Gemfile.lock
SimpleCov 0.18+ is not yet supported by CodeClimate
https://docs.codeclimate.com/docs/configuring-test-coverage#supported-languages-and-formats
=> Fix SimpleCov

lib/sidekiq/client.rb, test/test_client.rb
Sidekiq allows to bulk push jobs into Redis via the `push_bulk` methods. One of the requirements for using this feature is that the job arguments being passed to this method call should be an "Array of Arrays".
For some reason, the validation being done to make sure that the argument is an Array of Arrays was only checking if the first element of the array was an array. 
It is currently not checking if the `2nd` to `nth` element are arrays too.
This change adds:
- Validation that all elements of the array are of `Array` datatype.
- Tests to make sure that the new validation works as expected.
=> Validate that job arguments being passed to `push_bulk` is an Array of Arrays

test/test_client.rb
I noticed that one of the tests that validate that `ArgumentError` is thrown, does not throw the error because of the nature of arguments passed in the test case. It fails with the same error, but for a different reason.
```ruby
Sidekiq::Client.push('queue' => 'foo', 'class' => MyWorker, 'args' => [1, 2], 'at' => [Time.now.to_f, :not_a_numeric])
```
This throws `ArgumentError`, but not because all the elements of `at` is not `Numeric`, it is because `at` for `push` cannot be anything other than `Numeric`(it is an `Array` here.). It feels like this test case does not reveal the true reason for the error being raised.
I think this was originally intended as a test for `push_bulk`, but it ended up being a test for `push`, and since the same type of error was thrown, it did not reveal itself …
=> Refactor some tests

bin/sidekiq
**Problem**
Sometimes, the sidekiq workers of our app fail to launch by the Redis connectivity issue, and if that happens, it spits multiple lines of stack trace, regardless of configured `Sidekiq.error_handlers`. This patch will use the error handlers, if it's configured.
=> Use error handler(s) from CLI launch failure

Changes.md, Gemfile.lock, lib/sidekiq/web.rb, lib/sidekiq/web/authenticity_token.rb, sidekiq.gemspec
=> Vendor rack-protection/authenticity_token middleware

lib/sidekiq/client.rb, test/test_client.rb
In `Sidekiq::Client.bulk_push`, now 'at' size must be the same size as 'args' (or just be a single numeric).
Fixes #4601
=> raise ArgumentError if 'at' size is wrong

Changes.md, Pro-Changes.md, lib/sidekiq/fetch.rb, lib/sidekiq/launcher.rb, lib/sidekiq/manager.rb, lib/sidekiq/processor.rb, test/test_actors.rb, test/test_cli.rb, test/test_fetch.rb, test/test_manager.rb, test/test_middleware.rb, test/test_processor.rb
The existing fetch API grew organically to its current state but is less than optimal: you pass a class reference via the global options, making it hard to configure a fetcher instance and requiring some test gymnastics to set up that global config.
I'd like to change the fetch API to be instance-based. `bulk_requeue` will become an instance method. Feedback welcome.
=> Fetch API refactor, WIP

lib/sidekiq/fetch.rb
Within #4602 this method was changed from a class- to instance-method. The comment should be removed as the method is not a class-method anymore.
=> Remove wrong comment on instance method

lib/sidekiq/cli.rb
We're trying to use SIGUSR2, but currently the handler is being overridden by sidekiq. In particular, it is overridden _after_ the app is loaded.
As far as I can tell, this signal is only used by sidekiq pro ([source](https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts)).
It would be great to free up this signal for other use when it is not being used. I guess an alternative workaround would be to hook into the `startup` event, so that we can set up our own handler later. But I figured I'd propose this nevertheless.
=> Only trap USR2 on sidekiq pro

lib/sidekiq/web/csrf_protection.rb, test/test_csrf.rb
`Sidekiq::Web::CsrfProtection.valid_token?` now checking if the session hash is not empty.
Fixes #4671
=> Check if session hash not empty in csrf token validation

Changes.md, lib/sidekiq/middleware/chain.rb, test/test_middleware.rb
I noticed that our application has several middleware that wrap the job in a method that yields:
```ruby
class TaggedLoggingMiddleware
def call(*)
Rails.logger.tagged("my cool job") { yield }
end
end
```
To save a stack frame, I rewrote them to pass the given block directly to the method:
```ruby
class TaggedLoggingMiddleware
def call(*, &block)
Rails.logger.tagged("my cool job", &block)
end
end
```
I even made a change to RuboCop (https://github.com/rubocop-hq/rubocop/pull/8455) so that they could be rewritten automatically.
When I deployed the change, every job started to fail with:
> ArgumentError: wrong number of arguments (given 1, expected 0)
😩 
This happened because [lambdas have strict argument checking](https://ruby-doc.org/core-2.6.6/Proc.html#class-Proc-label-Lambda+and+non-lamb …
=> Allow middleware to yield arguments

Changes.md, web/assets/stylesheets/application-dark.css, web/assets/stylesheets/application.css, web/views/busy.erb, web/views/morgue.erb, web/views/queues.erb, web/views/retries.erb, web/views/scheduled.erb
Add a lot more contrast to various UI elements. This is a lot more usable to my old eyes.
=> Improve dark Web UI

5.0-Upgrade.md
Method name is `delay_for`, not `delay_in`.
This is somewhat confusing for those who upgrade and grep their code for these calls.
=> Fix typo in 5.0 upgrade manual, method name is `delay_for`

lib/sidekiq/web/csrf_protection.rb, test/test_csrf.rb
The previous fix for #4671 added a guard for a completely empty session. However, it seems that even if you delete the `rack.session` cookie, the session will still contain `session_id`, thus its not actually `empty?`. This changes the guard to actually check for the csrf token.
=> Fix handling of no csrf session token

lib/sidekiq/cli.rb, test/test_cli.rb
This PR proposes logging a warning when the CLI boots if the maxmemory policy is not 'noeviction'.
Inspired by [Nate Berkopec's tweet the other day](https://twitter.com/nateberkopec/status/1333863949238931464) (I've also had clients who had this misconfiguration):
> Running Sidekiq from a Redis datastore with a volatile eviction policy is probably the most common Sidekiq error I see in the wild w/clients. Switch to noeviction, you want Sidekiq to fail very loudly when you run out of memory, not silently drop jobs.
=> Warn on boot if maxmemory policy is not 'noeviction'

lib/sidekiq/logger.rb, test/test_logger.rb
If using `with` to add logging context, any context that has the same
keys as existing context will disappear after the with block completes,
instead of reverting back to the original context.
This fixes that by restoring the original context directly instead of
just deleting the keys from the `with` context.
=> Fix logger with from deleting existing context

web/assets/stylesheets/application-dark.css, web/assets/stylesheets/application.css, web/views/busy.erb
3b5ae30c4e5e9e760268243ab5c14664a2f8d236 added a process RSS column to the table on the busy page. The red badge beside column header is useful for linking users to more information, but it's quite eye-catching. Since the badge doesn't indicate a notification or status change, it would be nice if it stood out a little less from the background.
This PR changes the background colour to light grey in normal mode and dark grey in dark mode. I also changed the class name from "circled" to "info-circle" since, with the more discreet colouring, I feel like it's less generally useful.
Before:
After:
=> Change the background colour for the RSS info badge to be less eye-catching

Changes.md, lib/sidekiq/api.rb, lib/sidekiq/web/helpers.rb, web/assets/stylesheets/application.css, web/views/busy.erb
Sadly my design skills are minimal so it's not very attractive. CSS help appreciated if anyone wants to polish.
=> Add process/thread count summary to Busy page

web/views/busy.erb
.btn-group uses :first-child and :last-child to determine which buttons should have rounded corners and which ones should have square corners. The "Quiet" button had a square left corner, because the first child was a CSRF hidden field tag.
Keeping only .btn elements inside the .btn-group means that the 1 or 2 buttons are rounded as expected. When there's no "Quiet" button, the "Stop" button has 4 round corners. When both buttons are present, the corners between the buttons are square.
Fixes #4858
I traced this problem to this diff. https://github.com/mperham/sidekiq/commit/f0ddebc7406fe4b78333fbc5f14488a38b9ccebc#diff-d68d7f0b05d0be529c7d2493225a3cd8e5358f0c6327b7dfc8ead5f2927a1ba1L50-L59
The buttons now look like this:
When both buttons are present
When only Stop is present
=> Fix incorrect button rounding

web/locales/lt.yml
As you can see from the translation of `Stop`, the correct spelling should be `Sustabdyti`. There is no such word as `Sustbadyti` (also `badyti` means `stabbing` :dagger: , which is kind of funny)
=> Fix a typo in lt locale file

web/locales/en.yml, web/locales/es.yml
This PR adds some missing translations for Spanish language:
Also adds three words (Utilization, Process and Name) that were missing from locale files.
=> Add updated translations for spanish language

web/locales/fr.yml
Hello @mperham 
I saw some missing french locales today.
To help me identify missing I used https://github.com/glebm/i18n-tasks with this config
```yml
base_locale: en
locales: [fr]
data:
read:
- web/locales/%{locale}.yml
```
Then `i18n-tasks health`
=> Add missing french locales

lib/sidekiq/api.rb
There was an `is` still left in the change here  https://github.com/mperham/sidekiq/commit/53999adc2c3d9a0109d12abeee4b601d11a780bf#diff-25f829140be25a886134933b537d356dddb12234ca85319e50b381f9edb6b74dR913
=> Minor text change to make the description correct.

examples/systemd/sidekiq.service
RVM has option to run commands in specific directory, and if this directory has `.ruby-version` (with optional `.ruby-gemset`) or `.rvmrc` files in it, this version is automatically used.
Thanks to this, you no longer need to update systemd service configuration on Ruby version change.
=> Updated sidekiq service configuration with automatic ruby/gemset version pick

web/assets/stylesheets/application-dark.css
In our usage of sidekiq, we've added some custom tabs to the UI and we're using `alert-danger` and `alert-info` on those pages. The css for these does not look great in dark mode, this PR offers a dark-mode friendly style for those tags.
Here's an example of an `alert-danger` with the proposed style:
Here's an example of an `alert-info` with the proposed style:
=> Add alert-danger and alert-info support for dark mode

lib/sidekiq/api.rb, test/test_api.rb, web/views/busy.erb
I wanted to customize the way the queues are displayed in the web UI, but there was no way I could see to do so. This PR adds a `Process#queues` method, replacing the array access and matching similar methods `Process#identity` and `Process#tag`. I can redefine this method when the gem is required, which isn't great, but better than nothing.
=> Add Sidekiq::Process#queues method

web/views/morgue.erb
**Issue:** Tags on morgue classes do not properly apply filters when clicked. They redirect to a route that Sidekiq does not service.
**Steps to reproduce:**
1. Create an app running Sidekiq.
1. Kill a job with a tag.
1. Click on the tag in the web UI.
1. Observe that the tag does not redirect to a route serviced by Sidekiq Rack app. Depending on how host app is configured, route will 404, redirect, or do something else as it falls through.
**Root cause:**
- It looks like Sidekiq Pro mounts the routes `/filter/dead` but the `display_tags` method links to `/filter/morgue`.
**Notes:**
- There might be other ways of fixing this problem, like change the `/filter/dead` to `/filter/morgue`. 
Let me know if there's any other info needed or test cases we can provide!
=> Fix a Sidekiq Pro tagging bug

lib/sidekiq/api.rb, test/test_api.rb
follow on from https://github.com/mperham/sidekiq/pull/4935
This api seems simpler (I can just call `Sidekiq::Stats::QuickStats.new.fetch_stats!` for my usecase, and we reduce duplication with the main `Stats` api, since there's an overlap).
What do you think?
=> Quick stats api.

examples/systemd/sidekiq.service
You recommend the use of capistrano-sidekiq. This uses a user service (which is likely a good idea for most users from a security perspective). In order to get it to work, changes need to be made to the Sidekiq.service file (and location).
I describe the challenges I had in [this gist](https://gist.github.com/narath/060f01f3866a1b83d1db6f8cff4c054b) which can give you more context if needed.
=> Update Sidekiq.service to reflect the more common use case of a user service

lib/sidekiq/web/action.rb, lib/sidekiq/web/application.rb
This PR replaces the default `Cache-Control` for the Web UI to be `no-store` instead of `no-cache`. See [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#cacheability).
This seems like a saner default to use - tell servers that we don't want the page cached _anywhere_. Using `no-cache` says that the page can still be cached by intermediates as long as the page is revalidated. We ran into this issue with the Web UI behind Fastly - since the Web UI doesn't support Etags/If-Modified-Since, it seems like cache validation is just being performed by looking at the content length. This means that we were getting cached responses (such as stat data) that were clearly stale but matched the content length of the previous request.
Similarly, it's not uncommon to put the …
=> Use no-store for web UI to prevent intermediate caching

lib/sidekiq/web/action.rb, lib/sidekiq/web/application.rb
As a follow up to #4966, I realized it's also important to add `private` to the Cache-Control header as well to prevent [request collapsing](https://developer.fastly.com/learning/concepts/request-collapsing/). Even with `no-store`, Fastly (and I assume other places) can still collapse requests.
Note that this is only important if the Web UI is behind some form of authentication, since it provides the possibility of sending authenticated data to non-authenticated users under very specific circumstances.
This matches the example [here](https://developer.fastly.com/solutions/examples/prohibit-browser-caching) that fastly shows to prevent downstream caching + request collapsing.
=> Add private to Web UI Cache-Control to prevent request collapsing

lib/sidekiq/fetch.rb, test/test_fetch.rb
At a quick glance, figured the `sleep(2)` call here should be using the same `TIMEOUT` value being passed to the `brpop` call. Also added a test for the "no active queues" code path.
=> Use TIMEOUT constant instead of hardcoded 2 second sleep

lib/sidekiq/web/helpers.rb, test/test_web.rb, test/test_web_helpers.rb, web/assets/javascripts/application.js, web/assets/javascripts/dashboard.js, web/assets/stylesheets/application.css, web/views/_poll_link.erb, web/views/layout.erb
For reference:
This PR changes the way that the live polling feature is implemented so that the status (i.e. whether polling is enabled or disabled) is persisted across sessions and through page changes. Currently, if live polling is on but you navigate to a different Sidekiq tab (e.g. from "Busy" to "Enqueued"), live polling becomes disabled and you have to manually turn it back on. By leveraging the browser's `localStorage` property similarly to how the live polling interval is already handled, the status can be persisted.
I considered building on the existing `?poll=true` strategy, but I thought tacking that parameter on to every link on the page would be less elegant than just using `localStorage`.
I've added comments in the files view in case the diffs alone are insufficient to …
=> Persist live poll status in browser localStorage

test/helper.rb
This PR disables the new minitest parallelism environment variable
`MT_CPU` that is meant to take over from `N`.
https://github.com/seattlerb/minitest/blob/f4f57afaeb3a11bd0b86ab0757704cb78db96cf4/lib/minitest.rb#L25-L27
=> Disable new minitest parallelism

test/helper.rb
This PR fixes the faulty environment value that was introduced in #4980,
where you cannot set an environment variable as an integer but it must
instead be a string.
=> Fix faulty environment variable value

lib/sidekiq.rb, test/test_sidekiq.rb
Thanks a lot for Sidekiq!
In our setup with a Redis cluster, we are having regular failovers,
which is fine. We are currently improving the way our application
handles these situations and stumbled across a possible improvement
in Sidekiq itself.
By far the most frequent error in our error monitoring system is the
following:
UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)
These errors can occur during Sidekiq's long-running job fetching
command. This uses Redis' blocking BRPOP primitive. On failover in a
cluster setup, these commands are interrupted by the server.
This error causes the worker threads to be restarted, but as they are
bubbled up to the top, they cause a lot of spam in our error logging
systems. As related errors from other …
=> Reconnect on "UNBLOCKED force unblock" errors

lib/sidekiq/middleware/current_attributes.rb, test/test_current_attributes.rb
Implicit context via thread-local variables can be a powerful tool for things like multi-tenancy, logging, i18n, etc. Rails has ActiveSupport::CurrentAttributes, there's also gems like RequestStore. It would be excellent if Sidekiq included helper middleware that knows how to de-hydrate and re-hydrate variables between client and server so jobs can preserve this implicit context for their execution.
For example, one possible API:
```ruby
Sidekiq.configure_client do |config|
config.client_middleware do |chain|
chain.add Sidekiq::Context::Save, with: Myapp::Current
end
end
class Sidekiq::Context::Save
def call(_, job, _, _)
end
end
```
=> Helper middleware to preserve implicit context?

Changes.md, lib/sidekiq/cli.rb
Using a technique I learned from the fantastic [Working With Unix Processes](https://www.amazon.co.uk/Working-Unix-Processes-Jesse-Storimer-ebook/dp/B0078VSRUE), this allows other signal handlers to coexist with sidkiq. Simple example:
```ruby
trap('INT') do
puts "TRAPPED!"
end
end
```
Before this PR, this will never run. With the PR, this will run before the sidekiq behavior runs.
I tried writing a test in test_cli.rb and spent longer than I'd care to admit before I realized the tests there don't send signals, they just invoke the method.
Are there any other tests in the suite which do run processes and send signals? If so I'll try to put something in there.
Let me know what you think!
=> coexist with other signal handlers

lib/sidekiq/client.rb, test/test_client.rb
Ruby version: 2.7.4
Rails version: 6.0.3.4
Sidekiq / Pro / Enterprise version(s): 6.2.1, 5.2.2, 2.2.2
Sidekiq::Client.push_bulk uses the Ruby Enumerable#all? to ensure the 'at' is valid. The problem is all? incorrectly evaluates an array of ActiveSupport::Duration as not being all Numeric. 
Sidekiq::Client.push_bulk is using the following check for at validity
```ruby
raise ArgumentError, "Job 'at' must be a Numeric or an Array of Numeric timestamps" if at && (Array(at).empty? || !Array(at).all?(Numeric))
```
These are all valid values for 'at' but some would fail the above check
```ruby
1.is_a?(Numeric)                                                      #=> true
1.seconds.is_a?(Numeric)                                              #=> true # Fails the all? check …
```
=> Sidekiq::Client.push_bulk fails because Enumerable#all? doesn't understand ActiveSupport::Duration is Numeric

lib/sidekiq/api.rb
Preserve behaviour of previous `fetch_stats!` call.
While `fetch_stats!` might be better private, I think the api as-is is a bit cleaner if we make this change and preserve the previous behaviour.
I completely understand if you want to close instead though given your previous comment. Just thought I'd throw out the solution here so it's an easy option.
Follow on from https://github.com/mperham/sidekiq/pull/4936#issuecomment-924378724
=> Preserve behaviour of fetch_stats! returning stats.

Changes.md, lib/sidekiq/worker.rb, test/test_worker.rb
`SomeJob.set(wait_until: 1.hour).perform_later`
Sidekiq::Worker supports `set` to make it easy for people to convert from one API to another but does not know about `wait_until`. Implement it.
=> Support ActiveJob’s wait_until

.github/workflows/ci.yml
We use bundler-cache: true which does bundle install.
=> CI: Avoid double bundle install

lib/sidekiq/client.rb, test/test_client.rb
We don't need the commands here to be atomic so we use command pipelining instead
to save us some overhead from `MULTI`.
https://github.com/mperham/sidekiq/commit/ac69c7ee5e42357a0f87957d17d38e5512ed66bb references Sidekiq Pro so I don't know if this affects Sidekiq Pro's atomic batches. But maybe this could be overridden in Pro to use `multi`?
We have been running with this patch on GitLab.com for a week: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/72473
Effects on Redis CPU were inconclusive but I think it's a good change to make anyway?
=> Use Redis.pipelined instead of Redis.multi when pushing jobs

Changes.md, lib/sidekiq/worker.rb, test/test_client.rb, test/test_worker.rb
This is the code implements #5041.
We've got a monkey-patch into `Sidekiq::Worker::ClassMethods` and `Sidekiq::Worker::Setter` that we have been getting a lot of mileage out of that might be worth upstreaming. 
Background: We do a lot of batch processing, needing to enqueue 1000's or 100's of K's of jobs at once. We were using [`Sidekiq::Client.push_bulk`](https://www.rubydoc.info/github/mperham/sidekiq/Sidekiq%2FClient:push_bulk) with an `each_slice` to create chunks of 1000. 
Enter what we call `.perform_bulk`. It's an implementation of `Sidekiq::Client.push_bulk` that encodes the best practice of 1000 jobs at a time. This allows clients to enqueue many jobs without the sharp edge of forgetting to slice their batch up into smaller chunks.
Downside here is that the `.push_bulk`-based …
=> Implement `Sidekiq::Worker.perform_bulk`

lib/sidekiq/scheduled.rb
This allows us to pop jobs atomically so that we remove redundant ZREMs
from multiple processes trying to process the same job.
When we (GitLab) upgraded to Sidekiq 6, [we saw that the number of ZREM operations on our Redis server increased significantly](https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/1179#note_695764650). This had a negative effect on Redis CPU.
We tracked this down to https://github.com/mperham/sidekiq/commit/9b75467b33759888753191413eddbc15c37a219e. That change fetches 100 jobs, then tries to remove them one at a time. This change makes sense for setups with a few number of processes since the maximum number of overlapping processes would be low.
In our case, we added logging and found out that [~44% of ZREM operations were …
=> Change scheduler to use Lua-based script

lib/sidekiq/cli.rb, test/config__FILE__and__dir__.yml, test/test_cli.rb
This enables the use of `__FILE__` and `__dir__` in ERB config files by setting [`ERB#filename`](https://ruby-doc.org/stdlib-3.0.2/libdoc/erb/rdoc/ERB.html#filename) before computing its `results`. This allows `__FILE__` to provide a useful value, and `__dir__` works automatically if `__FILE__` is set correctly.
While in production it may be useful to have granular workers, in development it may be convenient (and less expensive) to have a worker capable of processing all queues, so as not to require starting up all workers individually.
Furthermore, it may be desirable to dynamically read in queue names from the other configs, so as not to have to worry about "drift" in the development config file (e.g. if a new queue is added).
Having access to `__FILE__` and `__dir__` allows such code …
=> Make `__FILE__` and `__dir__` behave as expected in ERB configs

lib/sidekiq/worker.rb, test/test_client.rb, test/test_worker.rb
Because `.perform_bulk`'s job is to enqueue Sidekiq jobs, it can bit a little surprising to not have jobs enqueued when it is called with a lazy enumerator until the returned JID enumerable has `.to_a` or `.force` called on it.
This PR changes the behavior of `.perform_bulk` to evaluate a lazy enumerable to ensure jobs are enqueued as soon as `.perform_bulk` is called and not some indeterminate time in the future (or never).
More background here: https://github.com/mperham/sidekiq/issues/5058
=> Make `.perform_bulk` immediately evaluate lazy enumerators.

lib/sidekiq/rails.rb
See https://github.com/mperham/sidekiq/discussions/5021#discussioncomment-1613079 for the full-context
When `::ActiveSupport::Logger.logger_outputs_to?(::Rails.logger, $stdout)` is false because `Rails.logger` is outputting to a file, and `Sidekiq.logger == Rails.logger`, a stack level too deep error was thrown, because `Rails.logger` was broadcasting to itself.
=> Fix stack level too deep when Sidekiq.logger == Rails.logger

lib/sidekiq/scheduled.rb
We need to call the `script` command on the raw redis connection because
passthrough for administrative commands has been deprecated and will be
removed in redis-namespace 2.0
Sample deprecation message:
```
Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /data/cache/bundle-2.7.4/ruby/2.7.0/gems/sidekiq-6.3.1/lib/sidekiq/scheduled.rb:45:i
n `zpopbyscore')
```
=> Fix deprecation warning when using redis-namespace

lib/sidekiq.rb, lib/sidekiq/job_util.rb, lib/sidekiq/worker.rb, test/test_client.rb
This PR implements a runtime type check for arguments as a follow-up from the discussion here: https://github.com/mperham/sidekiq/issues/5070. The idea is to provide some safeguards in non-production environments for folks about to do something dangerous (i.e. use arguments in a job that cannot (de)serialize reliably to/from JSON).
Open Questions:
- Is `#validate` or `#normalize_item` the right place for this logic?
- Are there other types we'd like to include in the allow list?
- This check is relatively strict as written (no symbols, no hashes). Do we want to instead take the approach explored in #2870?
Notes:
- It looks like this idea has been considered before and has been commented out for some time: https://github.com/mperham/sidekiq/issues/2870 and ...
- …
=> Implement strict argument checking

Changes.md, lib/sidekiq/extensions/action_mailer.rb, lib/sidekiq/extensions/active_record.rb, lib/sidekiq/extensions/class_methods.rb, lib/sidekiq/extensions/generic_proxy.rb, test/test_extensions.rb
This PR allows the delay extension to support keyword arguments.
I know the extensions will be deleted in 7.0 but it would be a nice addition in the meantime.
=> Add keyword arguments support in extensions

lib/sidekiq/worker.rb
Fixes #5126 
If merged, `perform_bulk` uses the pool specified by...
- The thread local one if present,
- The worker option's pool if present
- The default one otherwise
=> Fix the pool used by perform_bulk

lib/sidekiq/api.rb, lib/sidekiq/launcher.rb, sidekiq.gemspec, test/test_api.rb, test/test_web.rb
Incorporating changes from https://github.com/mperham/sidekiq/commit/6a334042ee567acb24a1b6ab31a4cca759795282 into the 5.x version
=> Migrate 5.x version to Redis 4.2.0

lib/sidekiq/api.rb, lib/sidekiq/client.rb, lib/sidekiq/fetch.rb, lib/sidekiq/launcher.rb, lib/sidekiq/paginator.rb, test/test_api.rb, test/test_client.rb, test/test_web.rb
Context: https://github.com/redis/redis-rb/pull/1059
The following is deprecated
```ruby
redis.pipelined do
redis.get(key)
end
```
And should be rewritten as:
```ruby
redis.pipelined do |pipeline|
pipeline.get(key)
end
```
Functionally it makes no difference.
=> Fix deprecated uses of `Redis#pipelined` and `Redis#multi`

lib/sidekiq/cli.rb, test/config_with_alias.yml, test/test_cli.rb
This PR allows config files to contain aliases in Ruby 3.1 and beyond by explicitly allowing aliases.
Pre-Psych 4 behavior is unchanged
=> Load aliases for Psych 4 (included in Ruby 3.1)

web/assets/stylesheets/application.css
Addresses #5054 
The nav bar jumps because the status span did not have a width, and therefore grew to the width of the enclosed string. 
Changed display to `inline-block` and set the width to `75px`
=> Fixing width of status span to be large enough for 'active' 

test/test_scheduling.rb
While working on https://github.com/mperham/sidekiq/issues/5158 I noticed an inconsistency with how `enqueued_at` is being handled with `push_bulk`.
I'm submitting this PR with a new failing test to demonstrate this inconsistency. The reason for it is [here](https://github.com/mperham/sidekiq/blob/cd553fa14cefe789684f3cf35b0f61e4e22b6305/lib/sidekiq/client.rb#L106). `push_bulk` always adds `enqueued_at`. `push` only adds it [conditionally](https://github.com/mperham/sidekiq/blob/cd553fa14cefe789684f3cf35b0f61e4e22b6305/lib/sidekiq/client.rb#L209).
I'm not 100% sure what's expected here, but it prevents me from unifying `push` and `push_bulk` 😅
=> Add failing test for scheduling in bulk and enqueued_at

lib/sidekiq.rb, lib/sidekiq/client.rb
This PR targets the discussion in https://github.com/mperham/sidekiq/discussions/4990.
In a Redis cluster setup, failovers will happen. In these cases,
a `Redis::CommandError` can be raised for different reasons, 
for example, when the server becomes a replica, when there 
is a "Not enough replicas" error from the primary, or when a 
blocking command is force-unblocked.
<details>
<summary>Sample stacktrace</summary>
```
Redis::CommandError: READONLY You can't write against a read only replica.
from vendor/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:216:in `call_pipelined'
from vendor/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:170:in `block in call_pipeline'
from vendor/ruby/2.7.0/gems/redis-4.2.5/lib/redis/client.rb:313:in `with_reconnect'
from …
```
=> Reconnect on known errors after failover when pushing jobs to Redis

lib/sidekiq/launcher.rb
Related to #5139 . Redis was still throwing deprecation warnings for the
`conn.expire` call. I also changed the `conn.hset` call since my assumption is any commands called directly on the Redis instance are undesirable.
=> Fix lingering command pipelining to Redis instance

lib/sidekiq/delay.rb
For consideration: 
This allows disabling the console output via RUBYOPT, etc. in certain contexts where it's desirable to keep console output clean without having to change log level. (e.g. large projects with parallel builds in CI).
Thanks for Sidekiq!
=> Use Kernel.warn for deprecation of delay extension.

web/assets/stylesheets/application.css
When using Sidekiq web console in Japanese, the `アクティブ` characters in the navigation status bar are wrapped.
https://github.com/mperham/sidekiq/blob/dce4b747f7d86e38d8be3879e359b376786c9804/web/locales/ja.yml#L54
Removed the fixed width of the navigation status bar and changed `display: inline-block;` to `display: inline;`.
This will prevent characters from being wrapped.
=> Do not fix the width of the navigation status bar

lib/sidekiq/monitor.rb
Closes #5195. Exit monitor with status code 1 if an exception is raised and sidekiq status isn't able to be displayed.
=> Exit sidekiqmon with non-zero exit code if an error occurs

.gitignore
I can't let go of #5183. It takes 10 minutes of my time to compile new Ruby version when I use rbenv and 10 seconds when it's done via Docker. Could we add these to `.gitignore` so that I can use it for my development without having dirty directory?
=> Ignore Docker config in git

web/assets/javascripts/application.js
This re-initializes the event listeners after the DOM is updated from polling.
Fixes #5184
=> Add event listeners after reload

lib/sidekiq/job_util.rb, test/test_client.rb
Follow up to https://github.com/mperham/sidekiq/issues/5228
I couldn't get the ActiveJob test working, but here's a draft for fixing the message.
=> Surface exact job class name in complex argument error message

web/assets/javascripts/application.js
If the polling response is not `.ok`, raise the response error and allow the `.catch()` to then show the error.
I tested this locally by changing the 
```ruby
get "/busy" do
raise "foo" if [true, false].sample
erb(:busy)
end
```
Should it show an error if `/busy` returns a 500? Or just silently move on? Right now I'm just logging to `console.error`
=> Recover web UI on 500 errors

web/assets/javascripts/application.js
Related to: https://github.com/mperham/sidekiq/pull/5230
When adding event listeners to elements, Javascript will generally prevent duplicating the listener if the callback function is named. Anonymous functions aren't tracked the same way. Javascript will continue to add an event listener every time the polling happens. This commit names those functions where the listeners are added to elements outside of the "page" `div`.
The duplicate event listeners caused some odd behavior:
1. Clicking in the "Stop Polling" caused a single GET call to the server for each event listener on the element. This will be problematic if someone leaves the polling on for an extended period of time.
2. It would some times cause the "Stop Polling" functionality to not stop polling.
1. Open the page inspector …
=> Prevent stray polling interval from running and prevent duplicate event listeners

examples/systemd/sidekiq.service
I'm running Sidekiq 6.4.1 on an Ubuntu 20.04 system with Ruby 3.1.1 installed via Snap for a Rails 7 application.
Using this systemd template, I noticed something odd when deploying with Capistrano. When my cap script ran `sudo systemctl restart sidekiq`, the Sidekiq process would restart, briefly go active, then go inactive and stop running. I would need to SSH in and manually do a `systemctl restart sidekiq` in order to get the process back up and running.
With some experimentation, I found that changing the `Restart` configuration from `on-failure` to `always` seems to do the trick. Now, when the Sidekiq process goes inactive, it properly restarts and stays restarted.
I'm not 100% sure of the "why" behind what's going on, but this change seems to be effective and I have not noticed any …
=> Change systemd restart method to "always"

lib/sidekiq.rb
As part of Sidekiq v.4.6.2, the way the log level is set when Sidekiq's logger is explicitly set to `nil` broke compatibility with gems like RailsSemanticLogger.
If a Rails app uses RailsSemanticLogger and sets `Sidekiq.logger = nil` in an initializer the app would not be able to load due to an undefined method error. This was caused by the fact that
* RailsSemanticLogger sets Sidekiq's logger to a SemanticLogger instance
* Setting Sidekiq's logger later on would trigger a call to logger.fatal!
SemanticLogger does not implement `fatal!` and this would be the cause of the error.
This PR fixes the isssue by reverting the way the log level is set.
(fixes #5297)
=> Restoring logger compatibility upon logger being set to nil

Gemfile, lib/sidekiq/transaction_aware_client.rb, lib/sidekiq/worker.rb, test/test_transaction_aware_client.rb
Yet another attempt at https://github.com/mperham/sidekiq/issues/5239
=> Add transaction-aware client

lib/sidekiq.rb
As I mentioned in https://github.com/mperham/sidekiq/commit/fdfb7a5211fbe2c29cfcca84aabd868004a4eb57#r73562100. I wanted to test `TransactionAwareClient` in https://github.com/adamniedzielski/sidekiq-staged_push-demo/pull/6. That's what I needed to change.
=> Require TransactionAwareClient

lib/sidekiq/testing.rb, test/test_testing_fake.rb
`jobs_by_queue` saves the queue name of enqueued jobs as strings. When
`clear` is called for a worker that has it's queue name defined as a
symbol `clear` calls `Queues.clear_for` using a symbol. As a result
`jobs_by_queue` is not cleared, while `jobs_by_class` is. Calling
`drain_all` then runs into an infinite loop because of the mismatch of
the two state hashes.
=> Fix drain_all infinite loop after clearing worker with symbolized queue

test/test_csrf.rb, test/test_current_attributes.rb, test/test_job.rb, test/test_job_logger.rb, test/test_logger.rb, test/test_systemd.rb, test/test_web_helpers.rb
Migrate test suite to 100% describe format
% git grep Minitest::Test test/
test/test_csrf.rb:class TestCsrf < Minitest::Test
test/test_current_attributes.rb:class TestCurrentAttributes < Minitest::Test
test/test_job.rb:class TestJob < Minitest::Test
test/test_job_logger.rb:class TestJobLogger < Minitest::Test
test/test_logger.rb:class TestLogger < Minitest::Test
test/test_systemd.rb:class TestSystemd < Minitest::Test
test/test_web_helpers.rb:class TestWebHelpers < Minitest::Test
relates to #5350
=> Update last of spec files to use it and describe, instead of minitest

_includes/header.html, _site/404.html, _site/about.html, _site/index.html, _site/products/enterprise.html, _site/products/pro.html, _site/support.html
Hiding the tagline on `md` yields the following result:
https://user-images.githubusercontent.com/178448/171727899-03bec94b-8c5c-4f9a-945d-5c7f0ca1f5d7.mp4
Fixes #5351
=> Hide tagline on md viewports

lib/sidekiq/client.rb, test/test_client.rb
Fix: https://github.com/mperham/sidekiq/issues/5381
`redis-rb`'s `zadd` argument parsing is particularly strict and doesn't make it easy to have transparent compatibility.
The bug only happens if there is more than two elements being added, hence why we missed it.
I'll be improving the `zadd` signature in `redis-rb` as well to make the transition easier.
cc @mperham @christos
=> redis-client: Fix `ZADD` compatibility

lib/sidekiq/web/helpers.rb, test/test_web_helpers.rb, web/views/busy.erb
Hi @mperham and thanks for this essential tool!
I noticed that the UI sorts processes by comparing hostnames as strings and, because Heroku just adds a number after the process name (`worker.1`, `worker.2`…), it results in processes named like `worker.10` ranking above `worker.1`:
This PR tries to address it without adding dependencies or too much unmaintainable cruft, so I thought a helper would contain this logic toward the frontend code.
The new helper `sorted_processes` sorts processes by hostname following the **natural sort order** so that
```rb
'worker.1' < 'worker.2' < 'worker.10' < 'worker.20'
'2.1.1.1' < '192.168.0.2' < '192.168.0.10'
```
Another approach would be to add or modify a `<=>` method in the `ProcessSet` class, whichever is preferable.
What do you think?
=> Sort processes in UI

lib/sidekiq/job_retry.rb, test/test_processor.rb, test/test_retry.rb
Allow `sidekiq_retry_in` to return either an Integer of seconds OR :kill OR :discard. The latter two symbols tell Sidekiq to send it directly to the morgue or throw the job away. Any other returned value will result in the default retry processing.
Fixes #5406
=> Enable `sidekiq_retry_in` to signal :kill or :discard dynamically

lib/sidekiq.rb
This will allow the default error handler to be easily removed if needed via `error_handlers.delete(DEFAULT_ERROR_HANDLER)` without having to depend on an internal implementation detail
I'm not sure where you might want this constant to be defined as it has to be after the method `self.default_error_handler` is defined.  So I thought right after the method might be okay or maybe at the end of the module?
Closes: https://github.com/mperham/sidekiq/issues/5391
=> define DEFAULT_ERROR_HANDLER

lib/sidekiq/api.rb, test/test_api.rb
I know that I did this wrong, but the redis commands for setting, getting and deleting the flag are correct (I think). I just don't think I implemented the best solution or understood the problem well enough.
Closes #5435
=> Create a timeout that happens before cleanup

lib/sidekiq/logger.rb
ruby 2.7.0 now honors Logger#level overrides, and since sidekiq 7 will require ruby version >= 2.7, we can remove the patch.
Ref:
https://github.com/ruby/ruby/commit/eb18cb3e476db3bc44d489e090e1535237c4c6c9
https://github.com/rails/rails/pull/44247
=> Remove Sidekiq Logger#add patch

web/assets/javascripts/metrics.js
Just a couple small color tweaks for the metrics charts in dark mode.
Here's light mode:
Dark mode before this change:
Dark mode with this change:
=> Improve metrics chart colors for dark mode

web/locales/el.yml
Hi @mperham, thank you for this amazing gem!
I noticed that some Greek translations were missing, so I added them and improved some of the existing ones.
Did not translate keys: Kill, KillAll & Context and it is better to stay as is. I added them as comments, to be  in sync with en.yml and easier to update the file in the future.
=> Sync & Improve greek translations

lib/sidekiq/worker.rb
- Update reference from `RetryJobs middleware` to `JobRetry`.
- Mention that class options are serialized into job when enqueued by the client (refs #5499).
=> Update comments around job class options

lib/sidekiq/web/helpers.rb, test/test_web_helpers.rb
=> fix 5514 - handle consecutive delimiters in hostnames while sorting them

myapp/config/initializers/sidekiq.rb, web/assets/javascripts/metrics.js, web/assets/stylesheets/application.css, web/locales/el.yml, web/locales/en.yml, web/views/metrics.erb, web/views/metrics_for_job.erb
=> UI tweaks for metrics pages

test/test_web.rb
Test was failing because "1003" showed up in a timestamp on the page:
=> Fix flaky test

sidekiq.gemspec
That release contain a fairly important fix for people who abuse `Timeout.timeout` or `Thread.kill`
Ref: https://github.com/redis-rb/redis-client/commit/5f82254583c75b1f914590ae6a3e159ed07c0ac9
=> Bump redis-client to 0.8.1

web/assets/javascripts/metrics.js, web/locales/en.yml, web/views/metrics.erb, web/views/metrics_for_job.erb
All of the highlighted words below are now coming from `en.yml` instead of hardcoded in the JS.
=> Internationalize copy on metrics charts

web/locales/zh-cn.yml, web/locales/zh-tw.yml
While working on #5531, I found there are some missing and weird translations. This PR improves existing `zh` translations.
=> Add missing and improve existing translations for zh locales

lib/sidekiq/cli.rb, test/cfg/config_capsules.yml, test/cli.rb
I figured I would throw this together really quick, as it would be beneficial for cases like ours where we use multiple sidekiq config files and would like to configure a capsule for a single one of them.
=> Add ability to parse capsules from a config file

examples/por.rb
When showing a junior how to explore how Sidekiq works, we noticed that if you’re running from the source directory, you’ll need to use bundle exec to get the gem on the load path.
Co authored by @musakurel.
=> Use bundle exec to run example files

lib/sidekiq/paginator.rb, lib/sidekiq/web/application.rb, web/views/busy.erb
Closes #5555.
The pagination is slower (compared to `/retries` etc pages), because we need to get all of the entries to sort them (by `run_at`) before returning. But now this loads with no problems.
Seems like it is also problematic to add mass actions like "Kill"/"Delete", because we will need to inefficiently iterate over the large list `list` (compared to `/retries` page where we can efficiently remove from the `zset`).
You mentioned filtering in the issue. This is Pro/Ent feature, right? So I have not access to it. Better to be implemented by you or someone else who has access.
=> Add pagination to "Busy" page

lib/sidekiq/cli.rb
These options were deprecated in version 6.0.0.
I think it fine to remove them now.
=> remove deprecated cli options

bin/sidekiqload, lib/sidekiq.rb, lib/sidekiq/testing.rb, lib/sidekiq/worker_compatibility_alias.rb, myapp/app/sidekiq/exit_worker.rb, myapp/app/sidekiq/hard_worker.rb, myapp/app/sidekiq/lazy_worker.rb, myapp/config/initializers/sidekiq.rb, test/client.rb, test/middleware.rb, test/processor.rb, test/retry.rb, test/testing_fake.rb, test/web.rb
The worker naming was deprecated in sidekiq 6.3. 
In version 7, we can use directly Sidekiq:Job in tests.
Application that depend on Sidekiq::Worker can require "sidekiq/worker_compatibility_alias" in their  application.rb or sidekiq initalizer.
=> Remove deprecated worker reference.

lib/sidekiq/web/helpers.rb, test/web_helpers.rb
The processes sorting was not correct for hostnames with `_` in it.
Ref: #5585 
This changes it so that all cases work.
Kudos to `shurikk` on Stackoverflow:
https://stackoverflow.com/a/15170063/575547
=> Fix natural sorting for processes

test/job_generator.rb
The purpose of this PR is to suppress cluttering/undesired stdout log output like the following in tests:
```
2022-10-29T10:59:39.023Z pid=66755 tid=1hg3 INFO: ------------------------------------------------------------------
2022-10-29T10:59:39.024Z pid=66755 tid=1hg3 INFO: JobGeneratorTest: test_respects_rails_config_test_framework_option
2022-10-29T10:59:39.024Z pid=66755 tid=1hg3 INFO: ------------------------------------------------------------------
```
Assigning `Rails.logger.level = Logger::WARN` in the test `setup` block of the `JobGeneratorTest`, as we were doing before, is too late to suppress the undesired log output in tests; by then, some unwanted log output will already have been written to stdout.
`before_setup` runs early enough to suppress the undesired log output …
=> Change Rails log level to WARN in `before_setup` rather than `setup`

myapp/config/environments/development.rb, myapp/config/environments/production.rb, myapp/config/environments/test.rb
The railtie for ActiveStorage is not included in the myapp/config/application.rb, so the configuration fails.
=> myapp: Removes activestorage config

web/assets/stylesheets/application-dark.css
Of the 4 types of [Bootstrap alerts](https://getbootstrap.com/docs/3.4/components/#alerts-examples), `alert-warning` was missing an override background color for dark mode which made it difficult to read. Although `alert-warning` is not used anywhere in the existing pages our organization has built some custom pages that uses it and it's difficult to read as is.
Current:
New:
=> Adds a color override for alert-warning to make it readable in dark mode

lib/sidekiq/web.rb, web/views/_job_info.erb
This PR adds a hook into the job info output to allow appending custom rows. For example this could be used to generate links to external log providers such as Datadog.
To use, a class must implement `show_row`, `row_name` and `row_contents`, for example:
```ruby
class CustomJobInfoRowLink
class << self
EXTERNAL_LOG_LINK = 'https://example.com/logs/job_id='
def show_row(job)
true
end
def row_name
"Logs"
end
def row_contents(job)
"<a href='#{EXTERNAL_LOG_LINK}#{job.jid}'>External logs</a>"
end
end
end
```
Then during setup of the Sidekiq web component, pass in to `custom_job_info_rows`:
```ruby
Sidekiq::Web.custom_job_info_rows << CustomJobInfoRowLink
```
=> Adds a hook into job info output to allow custom rows like links to external logs

web/assets/javascripts/application.js, web/views/morgue.erb, web/views/retries.erb, web/views/scheduled.erb
Any interest in something like this to allow you to shift-click ranges of checkboxes on the retries/scheduled-jobs pages?
=> Allow shift-clicking to select ranges of jobs

lib/sidekiq/api.rb, lib/sidekiq/launcher.rb, lib/sidekiq/monitor.rb, test/api_test.rb, web/views/busy.erb
It is backwards compatible in a way that sidekiqmon and Sidekiq UI will work during rolling deployments.
You can have one process in the previous version and another one in the new version and sidekiqmon/Sidekiq UI will work on both versions (legacy and new).
Before:
```
$ bundle exec sidekiqmon
Sidekiq 6.4.2
2022-11-17 18:28:14 UTC
---- Overview ----
Processed: 0
Failed: 0
Busy: 0
Enqueued: 0
Retries: 0
Scheduled: 0
Dead: 0
---- Processes (2) ----
Gabriels-MacBook-Pro.local:60533:888acdb733ff []
Started: 2022-11-17 15:16:46 -0300 (11 minutes ago)
Threads: 2 (0 busy)
Queues: critical, default, low
Gabriels-MacBook-Pro.local:62268:20c6394c86a7 []
Started: 2022-11-17 15:25:21 -0300 (2 minutes ago)
Threads: 50 (0 busy)
Queues: critical, default, low
---- Queues (0) ----
NAME    SIZE  LATENCY …
```
=> Add weights and version to queues on sidekiqmon and Sidekiq UI

lib/sidekiq/deploy.rb
I noticed this when discussing https://github.com/mperham/sidekiq/issues/5632#issuecomment-1320451422
now
```ruby
Sidekiq::default_configuration.redis_pool.with {|c| c.call("PING") }
=> "PONG"
```
was
```ruby
Sidekiq::RedisConnection.create.with {|c| c.call("PING") }
/app/vendor/bundle/ruby/3.1.0/gems/redis-client-0.11.1/lib/redis_client/ruby_connection.rb:62:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=IP:PORT state=error: certificate verify failed (self signed certificate in certificate chain) (RedisClient::CannotConnectError)
```
=> Use configured Redis pool in Sidekiq::Deploy

docs/capsule.md
Changes `Sidekiq.global_configuration` to `Sidekiq.default_configuration`
=> Update doc with correct method name for retrieving global config

lib/sidekiq/rails.rb
Rails 7.1 (in alpha) adds a [`source` keyword argument](https://edgeguides.rubyonrails.org/error_reporting.html#:~:text=source%3A%20a%20String,aren%27t%20interested%20in.) to its ErrorReporter interface. By default, [this is set to `application.active_support`](https://github.com/rails/rails/blob/32af4cd969834c9ec5ff4409f42a59d1c99acaad/activesupport/lib/active_support/execution_wrapper.rb#L87), which is misleading for errors raised from Sidekiq. We should set this correctly for maximum framework compatibility. At the very least, we need this at Honeybadger so we can ignore errors from Sidekiq and let the SIdekiq error handler handle it.
Couldn't find a way to add Rails 7-specific tests, but I tested this with my Rails 7 installation.
=> Set error source on Rails 7.1+

lib/sidekiq/job_retry.rb
Details in #5704 
@mperham I'm not quite sure if it's fine for you to just remove the outdated instructions or if you would prefer to replace it with a specific explanation taking the new "configuration strategy" into account. Feel free to change it again. Thanks.
=> Remove comment with outdated instructions for max_retries config option

web/views/metrics_for_job.erb
`titleize` is an ActiveSupport method and causes errors when using a standalone sidekiq/web. 
https://apidock.com/rails/String/titleize
Replace with proper call to localization:
https://github.com/mperham/sidekiq/blob/74f4b93ad44db6120de3fb9d3981a10f3ab7482b/web/locales/en.yml#L93
=> Remove titleize / use localization

lib/sidekiq/job_util.rb
While reading sources I noticed variable initialization outside of scope of it's usage. It seems like it was introduced at https://github.com/mperham/sidekiq/commit/b0fd83f5fc2d5d24bee1bfc002173f83b2e71155#diff-e3d2ada183fa5b2ce66ab380c5c6d3c97d9a7aa3c7a3e91a142b47e81f50356bL16-R21
Not a big deal, but nice to have I think
=> Tiny memory and performance tweak

lib/sidekiq/capsule.rb, test/capsule_test.rb
This PR fixes wrong weights value of Sidekiq process with implicit queues list.
If you do not provide `queues` in configuration explicitly, the default Sidekiq capsule initializes with `default` queue, but the `weights` stays `nil`, so the process's `weights` is `[nil]` instead of `[{"default"=>0}]` with explicit `queues` configuration. And it breaks Sidekiq web UI busy tab.
_Explicit_ queues list:
```ruby
sidekiq = Sidekiq.configure_embed do |config|
config.queues = %w[default]
config.concurrency = 2
end
Sidekiq::ProcessSet.new.to_a
```
_Implicit_ queues list:
```ruby
sidekiq = Sidekiq.configure_embed do |config|
config.concurrency = 2
end
Sidekiq::ProcessSet.new.to_a
```
=> Capsule default weights

bin/sidekiqload
When I run `bin/sidekiqload`, I get an error:
```
bin/sidekiqload:66:in `block in configure': undefined local variable or method `latency' for #<Loader:0x00007f86916c2ea0 @iter=500, @count=1000> (NameError)
```
=> Fix a missing local variable error in `bin/sidekiqload`

lib/sidekiq/component.rb, lib/sidekiq/job_util.rb, lib/sidekiq/metrics/tracking.rb, lib/sidekiq/processor.rb
1. I measured memory allocated by whole `bin/sidekiqload` script to process 100k jobs using 1 thread:
```
Total allocated: 953.37 MB (7861488 objects)
Total retained:  1.18 MB (1004 objects)
allocated memory by gem
-----------------------------------
387.22 MB  json-2.6.2
244.71 MB  sidekiq/lib
176.20 MB  redis-client-0.12.1
119.38 MB  connection_pool-2.3.0
21.58 MB  other
4.15 MB  lib
129.17 kB  concurrent-ruby-1.1.10
3.94 kB  rubygems
2.86 kB  toxiproxy-2.0.2
120.00 B  activesupport-7.0.4.2
allocated memory by file
-----------------------------------
387.22 MB  /Users/fatkodima/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/json-2.6.2/lib/json/common.rb
111.21 MB  /Users/fatkodima/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/connection_pool-2.3.0/lib/connection_pool.rb
107.05 …
```
=> Performance improvements

lib/sidekiq/middleware/chain.rb
Follow up to https://github.com/mperham/sidekiq/pull/5768
I noticed, that `redis-client` consumes quite some memory and was able to optimize it - https://github.com/redis-rb/redis-client/pull/90. Hope the PR will be merged.
But I also noticed that we can optimize traversing middleware chain, which allocates a proc each time the job is enqueued/performed.
Ran on 100k jobs:
```
$ THREADS=1 LATENCY=0 PROFILE=1 bundle exec ruby-memory-profiler --scale-bytes --out tmp/memory_profiler.txt bin/sidekiqload
```
```
Total allocated: 600.07 MB (5626286 objects)
Total retained:  2.57 MB (22682 objects)
allocated memory by gem
-----------------------------------
231.46 MB  json-2.6.2
194.04 MB  sidekiq/lib
78.64 MB  redis-client/lib
50.74 MB  connection_pool-2.3.0
22.96 MB  other
9.69 MB  lib
3.32 MB …
```
=> Optimize traversing middleware chain

lib/sidekiq/web/helpers.rb, test/helper.rb
~once in 5-10 test runs I get an error regarding too many opened files.
Something like:
```
Error:
Sidekiq::CLI::#parse::#run#test_0001_prints rails info:
Errno::EMFILE: Too many open files
lib/sidekiq/cli.rb:49:in `pipe'
lib/sidekiq/cli.rb:49:in `run'
test/cli_test.rb:383:in `block (6 levels) in <top (required)>'
rails test /Users/fatkodima/Desktop/oss/sidekiq/test/cli_test.rb:380
``` 
or 
```
Traceback (most recent call last):
25: from /Users/fatkodima/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:83:in `block in autorun'
24: from /Users/fatkodima/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:159:in `run'
23: from /Users/fatkodima/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest.rb:18 …
```
=> Reduce # of opened files in tests

lib/sidekiq/api.rb
In all other places `Sidekiq.load_json/dump_json` is already used (so users can monkey patch these methods with other json implementations if they will).
=> Use `Sidekiq.load_json` everywhere

lib/sidekiq/job_util.rb, test/client_test.rb
=> Improve error message when checking arguments for json safety

lib/sidekiq/job_util.rb, test/client_test.rb
I apologize, I realized that I made a mistake in https://github.com/sidekiq/sidekiq/pull/5786.
Code like 
```ruby
when Array
item.find { |e| !json_unsafe_item(e).nil? }
```
incorrectly returns *the child* of an array if it is not valid or has invalid children, instead of the innermost child - see the updated test case. The code became a little more uglier, but this time should work as expected.
=> Fix detecting json unsafe item within job arguments

lib/sidekiq/client.rb, test/client_test.rb
Previously we only returned the JIDs that were succesfully pushed but there was no way for the caller to determine which payloads, if any were not successfully pushed.
Now we return both nils and JIDs. If you push 5 jobs, you will get 5 results even if all five did not get pushed. This change is helpful for the upcoming ActiveJob bulk enqueue helper method so AJ can know which jobs pushed successfully.
See rails/rails#46603
=> Adjust push_bulk return value

lib/sidekiq/job_util.rb, test/client_test.rb
Fixes #5789.
HWIA is correctly detected as unsafe, but there is a problem in detecting the culprit. We can not use a `case-when`, because it checks for instances of classes (*or subclasses*), which is not correct in this case 🤦 We need to do exact comparison.
Am I missing any other test cases, so this won't happen again? 🤔
=> Handle correctly subclasses when finding json unsafe item

lib/sidekiq/config.rb, lib/sidekiq/job_retry.rb, lib/sidekiq/rails.rb, test/exception_handler_test.rb, test/helper.rb, test/rails_test.rb, test/retry_test.rb
Closes #5589.
Backtrace cleaning applies to exception logging and backtraces stored within the jobs.
=> Exception logging with Rails backtrace cleaner

lib/sidekiq/rails.rb, test/rails_test.rb
By wrapping the `Rails.backtrace_cleaner` with a proc/lambda and call `clean` ourselves, we can avoid the monkey-patch/extension to alias the method in the backtrace cleaner implementation so that it conforms to the `call` API.
Ref: https://github.com/sidekiq/sidekiq/pull/5794#discussion_r1109767123
/cc @fatkodima
=> Wrap the Rails backtrace cleaner to avoid aliasing method

lib/sidekiq/fetch.rb
`false` means no timeout, so if for some reason the server never respond the client will be stuck forever.
This may mitigate https://github.com/redis-rb/redis-client/issues/96
=> Pass a timeout to blocking_call

lib/sidekiq/api.rb, test/api_test.rb
[Rails 5.1](https://guiarails.com.br/5_1_release_notes.html#parameterized-mailers) added the ability to pass data to mailers as params, which is also the current recommended way in [the guides](https://guides.rubyonrails.org/action_mailer_basics.html#calling-the-mailer).
Most of the time, emails are delivered immediately, so they exit the queue pretty quick, but sometimes you want to schedule a sending in the future (with `deliver_later(wait: ...)`) and the job might stay around for a while.
It'd be helpful to be able to see the params that are associated to the job, as at the moment it only shows the args, which might be empty most of the time (if you use params instead).
This changes it to show both of them.
=> Show ActionMailer params as the job arguments

lib/sidekiq/client.rb, lib/sidekiq/job_util.rb, test/client_test.rb
Fixes #5814.
Example of usage:
```ruby
push_bulk('class' => 'MyJob', 'args' => (1..100_000).to_a) # will push into redis in batches of size 1000
push_bulk('class' => 'MyJob', 'args' => (1..100_000).to_a, batch_size: 10_000)
```
[Nicer diff without whitespace changes](https://github.com/sidekiq/sidekiq/pull/5827/files?diff=split&w=1)
=> `Sidekiq::Client.push_bulk` works in batches

sidekiq.gemspec
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/
---
Ref: mperham/connection_pool#171
=> Opt-in for MFA requirement

test/retry_test.rb
Minor update in test suite.
Test suite runs from Ruby >=2.7  so this check should not be needed
=> Remove Ruby 2.1 version check

lib/sidekiq/metrics/query.rb, test/metrics_test.rb, web/views/metrics_for_job.erb
Fixes #5865
Before:
Tooltips items were sorted from fastest to slowest, while on the chart the fastest bubbles are on the bottom.
After:
Tooltip items are sorted from slowest to fastest, matching the bubbles on the chart.
=> Histogram tooltip sort order should match the bubbles on the chart

test/web_test.rb, web/views/busy.erb
Switch buttons to input attributes, so they get the JS listener that provides the confirmation dialog.
Fixes https://github.com/sidekiq/sidekiq/issues/5878
=> Use input attribute over button on busy view

lib/sidekiq/cli.rb
This is mostly as a developer convenience - ERB in Rails is configured this way by default, and I was _assuming_ it was the default, generally speaking. But it's not. And so I spent many confused minutes thinking I was holding Sidekiq wrong. 😆
This is particularly helpful when trying to generate a list of queues, but not wanting extra new lines (which the YAML loader will ignore, but my dumb human brain doesn't want to ignore).
```yaml
:queues:
<% DEFAULT_JOB_QUEUES.each do |name, weight| -%>
- ["<%= name %>", <%= weight %>]
<% end -%>
```
=> Enable trimming trailing newlines in ERB with -%>

lib/sidekiq/job_util.rb
GitHub actions sends users to https://github.com/sidekiq/sidekiq/wiki/Best-Practices. instead of https://github.com/sidekiq/sidekiq/wiki/Best-Practices
=> Remove dot at the end of URL

web/views/metrics_for_job.erb
After installing [Sidekiq 7.0.9](https://github.com/sidekiq/sidekiq/blob/main/Changes.md#709) I noticed that the histogram totals chart was displaying the data in the wrong order:
I've confirmed in the logs that the data present in the bubble chart is the correct data.
Looking at recent changes I noticed this regression was introduced in https://github.com/sidekiq/sidekiq/pull/5868 while trying to improve the order in the tooltip for the bubbles chart.
After applying the fix we can verify we get the expected graphs:
I've opted to do the change inside the view since that is the smallest change to fix this issue. @adamlogic Let me know if you have suggestions on how to address the issue.
Thank you @adamlogic and @mperham for the awesome metrics dashboard 💚
=> Fix order in histogram totals chart

lib/sidekiq/api.rb
Noticed high CPU usage in Redis when aggressively calculating queue latency for large queues (1M+ jobs). According to Redis docs on LRANGE:
> Time complexity: O(S+N) where S is the distance of start offset from HEAD for small lists, from nearest end (HEAD or TAIL) for large lists; and N is the number of elements in the specified range.
However, the above is only true for Redis >= 7.0. On versions 4 to 6, it doesn't find the nearest end so using offset -1 means it goes through the entire list. Benchmarks below:
```
Redis 4 => 4.0.14
Redis 5 => 5.0.14
Redis 6 => 6.2.12
Redis 7 => 7.0.11
Warming up --------------------------------------
Redis 4 | LRANGE | S     1.556k i/100ms
Redis 5 | LRANGE | S     1.442k i/100ms
Redis 6 | LRANGE | S     1.582k i/100ms
Redis 7 | LRANGE | S     1.439k …
```
=> Use LINDEX for consistent performance when calculating queue latency

lib/sidekiq/middleware/current_attributes.rb, test/current_attributes_test.rb
Currently, when calling `Sidekiq::CurrentAttributes.persist(...)` for multiple current attributes, the middleware doesn't correctly load the serialized data in the server middleware. In fact, it fails because the attributes from the first current attribute are used for "rehydrating" the second one.
The backwards compatible solution in this PR allows for a hash argument to be passed to the aforementioned method, with a key that is used in the `jobs` hash.
```ruby
Sidekiq::CurrentAttributes.persist({
cattr: "Myapp::Current",
cattr_other: "Myapp::OtherCurrent"
})
```
=> Support multiple current attributes in middleware

lib/sidekiq/config.rb, test/exception_handler_test.rb
A follow up to #5943 and #5920.
As @stevenharman suggested in the [comment](https://github.com/sidekiq/sidekiq/issues/5920#issuecomment-1552296080) I think that we should be super safe calling `@options[:error_handlers]` cause they can raise anything. After this change, if anything like #5920 comes up again it should be clearly visible in the logs, saving people debugging time.
=> Make error handlers processing Exception prone

lib/sidekiq/web.rb, myapp/config/environments/development.rb, myapp/config/environments/test.rb
This avoids "Rack::Lint::LintError: uppercase character in header name: Cache-Control".
=> Made all cache-control headers lowercase.

.github/workflows/ci.yml
Redis 7 was released about 1 year ago, and it's already available on, e.g. AWS Elasticache.
I'd feel more confident upgrading (or launching new apps) to Redis 7 when Sidekiq would run CI against this version. Sidekiq is an integral part of all the apps I'm working on :-)
Redis 7 has a few breaking changes; see https://raw.githubusercontent.com/redis/redis/7.0/00-RELEASENOTES
-- Thanks for maintaining and open-souring Sidekiq 🙇
=> Run CI with Redis 6 and 7

test/client_test.rb, test/processor_test.rb, test/web_test.rb
Minitest 5.19.0  removed the "ancient MiniTest compatibility layer" that aliased `Minitest` as `MiniTest`. CI runs without a lock file so tests are failing due to this new release.
This commit fixes all usages of MiniTest to use Minitest instead.
=> Fix Minitest constant name in tests

docs/capsule.md, docs/internals.md
Hello, this is my first time contributing to the project, to OSS in general. I was reading through the internals.md and capsule.md in the docs directory and found myself jumping from place to place as I was going to the code that the doc files referred to `lib/sidekiq/cli.rb` and the like. There was no real need to test these changes as they have no functional change other than they may help those who go back and forth between files jump to the place they were at in the given file. No worries if these changes are not viewed as necessary, just trying to help. Thanks for the feedback and your hard work for this cool project.
=> Docs Refactoring -> small changes

lib/sidekiq/web.rb, lib/sidekiq/web/action.rb, lib/sidekiq/web/application.rb, lib/sidekiq/web/csrf_protection.rb
Fixes #5988
Response headers were previously downcased in order to support Rack 3. However, this led to an issue where the content-security-policy header was not found by the Rails 7 (Rack 2) ContentSecurityPolicy middleware and the middleware would add its own (conflicting) header.
This commit restores compatibility with Rack 2 by making the casing of response headers conditional on the Rack version. A few of these are able to use the constants from Rack itself, and those not included in Rack were added as constants under Sidekiq::Web.
=> Restore compatibility with Rack 2

web/views/_job_info.erb
Fixed a non-issue. Closing tag of anchor element tag was missing in file: "_job_info.erb"
I am brand new and have a passion to learn. Viva la Sidekiq!
=> fixed end of element closure

lib/sidekiq/job_retry.rb, test/retry_exhausted_test.rb, test/retry_test.rb
Hello 👋 
Trying to make the `sidekiq_retries_exhausted` and `sidekiq_retry_in` works with ActiveJob.
There some issue describing this behavior: https://github.com/sidekiq/sidekiq/issues/4496, and some workaround existing (for `sidekiq_retries_exhausted`), but none (as far as I know) for `sidekiq_retry_in`.
It is also written in the Sidekiq Wiki as currently not supported: https://github.com/sidekiq/sidekiq/wiki/Active-Job#customizing-error-handling, but it would be a huge bonus for us
Open to suggestions, other idea I had was to modify the [ActiveJob Adapter](https://github.com/rails/rails/blob/main/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb) to keep it in sync and modify the Job Instance on the fly, but thought it would be better to keep the current support as much as …
=> Add support for sidekiq_retry_in and sidekiq_retries_exhausted_block for ActiveJob

docs/7.0-Upgrade.md
Redis.com added support for 7.2 which I've confirmed with support has RESP3 support.
=> Redis.com added support in 7.2

Changes.md, lib/sidekiq/client.rb, lib/sidekiq/job_retry.rb, lib/sidekiq/job_util.rb, test/retry_test.rb
Allow time-based retry windows `sidekiq_options retry_for: 3.days` rather than the existing `retry` count. `retry_for` provides a simpler mental model for long a job will retry, and so can be a little more developer friendly. The drawback is that you don't have any sense for how many times Sidekiq will retry during that window.
One impl detail: existing `retry` values still have effect. If you say `retry: 1, retry_for: 1.year`, your job will still quickly die because you're only allowing one retry. The default `retry` count of 25 will last for approximately three weeks. If you want to `retry_for` longer than that, you will also need to increase the `retry` value.
=> Implement retry_for, fixes #6029

lib/sidekiq/job_util.rb
Coercing to int is making it so whenever the arg is not passed in, it assumes the value 0, which prevents all jobs from ever retrying.
=> Default retry_for to nil, not 0

lib/sidekiq/config.rb, test/exception_handler_test.rb
When the error_handler is like `proc { |_ex, _ctx, _cfg = nil| }`, false-positive DEPRECATION message was shown (#6051).
This is because arity of lambda and non-lambda proc differs as below:
```
proc_handler = proc { |x, y, z = nil| }
proc_handler.arity #=> 2
proc_handler.parameters.size #=> 3
lambda_handler = lambda { |x, y, z = nil| }
lambda_handler.arity #=> -3
lambda_handler.parameters.size #=> 3
```
I changed the code to use `#parameters.size` instead of `#arity` for ~~proc~~ all error_handler.
---
non-lambda-proc error_handler is used in bugsnag integrations for example.
https://github.com/bugsnag/bugsnag-ruby/blob/bdfbf3972f2137b3b9b95194a6bedf9c8edf6555/lib/bugsnag/integrations/sidekiq.rb#L53
=> Fix false-positive DEPRECATION message when the error_handler is non-lambda proc

Changes.md, lib/sidekiq/web/application.rb, test/web_test.rb, web/assets/javascripts/dashboard-charts.js, web/assets/javascripts/metrics.js, web/views/dashboard.erb, web/views/metrics.erb, web/views/metrics_for_job.erb
This hardens the Web UI against any future attacks which might inject JavaScript into the page.
Fixes #5992
=> Remove inline JS from pages

lib/sidekiq/testing.rb, test/testing_test.rb
Hello!
With the upgrade from version `7.1.1` -> `7.1.6`, I started seeing failures on having nested `Sidekiq::Testing.inline!` blocks.  This behavior change seemed to be introduced in e9f212902185591831af514df6313f8ae2cce31a.
As discussed on #6076, I've added code to raise an exception in this situation so it doesn't silently fail. I've included a test that fails on `main` but passes with my change.
I'm a bit of a Ruby noob so happy for whatever stylistic changes :)
=> Raise exception on nested Sidekiq::Testing modes

lib/sidekiq/web/helpers.rb, test/web_helpers_test.rb, web/assets/javascripts/application.js, web/assets/javascripts/dashboard-charts.js, web/assets/javascripts/dashboard.js, web/assets/stylesheets/application.css, web/views/_summary.erb, web/views/busy.erb, web/views/metrics.erb, web/views/queues.erb
Hi @mperham,
I finally got around to updating to Sidekiq 7, great work!
I dig the new metrics tab, but it got me thinking about numbers in tables. The idea here is to make numbers more scannable by:
- Right aligning
- Using a monospace font
- Forcing precision (i.e `1.4 -> 1.40` so everything aligns within the column)
- Adding delimiters
- Moving units to the table header
If you prefer the way this looks, I could finish up this PR by formatting every numeric column the same way.
Here's a before and after example:
Thanks!
=> Metrics formatting.

lib/sidekiq/job_retry.rb, test/retry_exhausted_test.rb
Provides the same functionality to `sidekiq_retries_exhausted` as `:discard` for `sidekiq_retry_in` of not sending these jobs to the dead set or calling global death handlers. This is useful for jobs that have retries disabled, which as a result means `sidekiq_retry_in` is never called.
Note: this is slightly different than the existing behavior of jobs with `dead: false`, in which case those jobs skip the dead set, but global death handlers are still called. Added tests to document/confirm that behavior, but didn't change it as part of this.
=> Support :discard return value in sidekiq_retries_exhausted block

lib/sidekiq/rails.rb
I might be the only one with this problem, but here it goes: There are Rails commits (between 7.0 and 7.1) where `Rails.logger` is not yet a `ActiveSupport::BroadcastLogger`, but in these commits the `Rails::VERSION::STRING` is `7.1.0.alpha`. (For other reasons, I'm currently stuck at one of those commits). In this case sidekiq will try to use the `broadcast_to` method of the `ActiveSupport::BroadcastLogger` which it expects from a 7.1 rails version, but it's not there, so it fails. My suggestion would be to test the logger capability rather than to assume it from the version string.
=> Use `Rails.logger.respond_to?(:broadcast_to)`  to determine if `ActiveSupport::BroadcastLogger` is available

docs/capsule.md
* https://github.com/sidekiq/sidekiq/issues/5886#issuecomment-1531676249 updated the internal pool size from 5 to 10.
* Prior to Sidekiq 7.0, `concurrency + 5` was used: https://github.com/sidekiq/sidekiq/blame/v6.5.12/lib/sidekiq/redis_connection.rb#L93
=> Fix actual pool sizes in capsule docs

lib/sidekiq/api.rb, lib/sidekiq/job_retry.rb, lib/sidekiq/web/csrf_protection.rb
This avoids a warning with Ruby 3.3
Closes #6150
=> Remove dependency on base64 gem

Changes.md, Ent-Changes.md, lib/sidekiq/api.rb, test/api_test.rb, test/web_test.rb, web/views/busy.erb
Today, the third parameter in `Sidekiq::WorkSet#each {|process_id, thread_id, work| ... }` is a raw Hash which makes it difficult to change data formats and storage. Introduce a new type `Sidekiq::Work` which represents a job in progress.
Sidekiq 7.0 introduced a slight change in the data format. It was optimized to reduce unnecessary JSON serialization of the "payload" attribute but this changed the data type.
```ruby
Sidekiq::WorkSet.new.each do |pid, tid, work|
work["payload"]["jid"]
Sidekiq.load_json(work["payload"])["jid"]
work["payload"]["jid"]
work.job["jid"]
end
```
This restores compatibility with 6.x but does break compatibility with 7.0 -> 7.2. Any opinions?
See #6145
=> Add new Sidekiq::Work type

lib/sidekiq/testing.rb
In test environment
1、Sidekiq::Extensions::DelayedClass.perform_one
2、Sidekiq::Queues.jobs_by_worker is empty，but Sidekiq::Queues.jobs_by_queue has the job yet
=> fix: invoke perform_one, but Queues not delete the job

bin/multi_queue_bench
Hello, 
I added a new benchmark based on `bin/sidekiqload` that:
* spawns multiple sidekiq processes each consuming from their respective queue 
* configurable workloads (how many jobs per queue to push)
* removed latency logic, benchmark should be used in production
The following env variables can be used to run the benchmark(they are explained in the source file)
* QUEUES
* PROCESSES
* ELEMENTS
* ITERATIONS
* PORT
* IP
This benchmark is particularly useful when sidekiq uses Dragonfly as backend.  Dragonfly’s shared-nothing, multi-threaded architecture fits more naturally to a multi-queue benchmark since each of the queues can be consumed by sidekiq processes in parallel as opposed to Redis which is single threaded. 
p.s. I am not fluent in Ruby, so any improvements are very very welcome …
=> feat: add multi-queue multi-process benchmark

lib/sidekiq/redis_connection.rb
Unit tests fails when a different REDIS_URL is defined since the provider string `p` could be an empty string (effectively returning `ENV['']` or `nil`). This causes all `Sidekiq::RedisConnections` to use the default `redis://127.0.0.1:6379` as the connection parameters.
This PR proposes a fix by doing a boolean `||` on the `ENV` value rather than on the key.
**To replicate:**
When using `localhost:6379`, the specs pass. 
1. Run `docker run -p 6379:6379 -d redis:6.2-alpine`
2. Run `bundle exec rake`
When using a different redis address, the specs fail
1. Run `docker run -p 6380:6379 -d redis:6.2-alpine`. Be sure to stop previous docker container running with exposed port `6379`.
2. Run `REDIS_URL=redis://localhost:6380 bundle exec rake`
```
rails test …
```
=> fix: fix determine_redis_provider test behaviour

examples/systemd/sidekiq.service
When rebooting the system, the user service was not launched automatically.
=> Fix sidekiq.service for use as user service

lib/sidekiq/rails.rb
Rails enhances `Object` with `#as_json` that either uses `#to_hash`, or builds Hash of instance variables to their values. During boot process Sidekiq sends debug event with context that includes `:reloader`. As Reloader class has `@app = Rails.application` that causes stak level too deep one-off failure.
=> fix: Avoid JSON dump on Rails.application

Changes.md, lib/sidekiq/api.rb, test/api_test.rb
Closes #6211.
Example:
```ruby
work = WorkSet.find_work_by_jid("abcde")
```
=> Add ability to find a currently running work by jid

lib/sidekiq/web/action.rb, lib/sidekiq/web/application.rb, lib/sidekiq/web/helpers.rb, test/web_helpers_test.rb, test/web_test.rb, web/assets/javascripts/application.js, web/assets/stylesheets/application-rtl.css, web/assets/stylesheets/application.css, web/views/_footer.erb
This pull request introduces a language selector to the footer of the web UI. Additionally, it ensures that the selected locale persists throughout the current session. If the user doesn't choose a language, it will default to their preferred one.
**Desktop**
**Mobile**
=> Add language selector and session language persistance

lib/sidekiq/redis_client_adapter.rb, lib/sidekiq/version.rb
This will allow to avoid Ruby deprecation warnings on Ruby 2.7
```
gems/sidekiq-7.2.2/lib/sidekiq/redis_client_adapter.rb:36: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
gems/redis-client-0.21.1/lib/redis_client.rb:275: warning: The called method `call' is defined here
```
Testing env: 
```ruby
Warning[:deprecated] = true
def call(*command, **kwargs)
puts command, kwargs
end
def wcall(*args); call(*args);end
def wcall2(*args, **kwargs); call(*args, **kwargs);end
```
Testing: 
```
irb(main):019:0> wcall(1,2,3, foo: 'bar')
(irb):15: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
(irb):12: warning: The called method `call' is defined here
1
2
3
{:foo=>"bar"}
=> nil …
```
=> Add **kwargs to dynamic redis client method definition

lib/sidekiq/redis_connection.rb, test/redis_connection_test.rb
[The docs says](https://github.com/sidekiq/sidekiq/wiki/Using-Redis#using-an-initializer)
> Keys can be strings or symbols and will be unified before being passed on to the Redis client.
But it doesn't work with nested keys in the options.
```ruby
config.redis = {
"name" => "mymaster",
"sentinels" => [
{ "host" => "redis-node-1", "port" => 26379 },
{ "host" => "redis-node-2", "port" => 26379 },
{ "host" => "redis-node-3", "port" => 26379 }
]
}
end
```
We're parsing the configuration from a YAML file and the hash comes out naturally with string keys. It would be nice to handle the conversion automatically.
=> Convert Redis options nested keys to symbols

lib/sidekiq/job_logger.rb, lib/sidekiq/processor.rb, test/job_logger_test.rb
This PR adds a new configuration knob, :skip_default_job_logging, to disable job logging out of the box, see #6199.
The user can choose when and where to disable the logging. I would recommend leaving it enabled for a reasonable developer experience but in environments like a high-volume production setup, logging output can be significant. This allows the user to opt-out of the logging if it becomes an issue.
```ruby
config[:skip_default_job_logging] = (config[:environment] == "production")
config[:skip_default_job_logging] = true
end
```
=> Allow user to disable default job logging

test/web_test.rb
The Sidekiq Web UI test attempts to test that the latency shown in the queues page is 0.0. However, if there is some slowness in the test the latency could tick up to a second, causing the test to fail.
Avoid this flakiness by stubbing `Time.now` so that we guarantee that the latency will always remain at 0.
=> Make Sidekiq Web UI test less flaky

lib/sidekiq/web/application.rb, test/web_test.rb
Followup to https://github.com/sidekiq/sidekiq/pull/6270#discussion_r1594433193
A nonce doesn't work with `unsafe-inline`, so just go back to how it was previously. Keep this as a task for later instead.
=> Relax CSP for `style-src`

lib/sidekiq.rb
`terminate` method is not defined.
=> Fix `Embedded` example

examples/config.yml
This updates the example config to use default values for most things (like concurrency) and provide examples of how to customize.
It also includes some of the Rails default job queues for a more complete example.
=> Update example config

Changes.md, Gemfile, lib/sidekiq.rb, lib/sidekiq/config.rb, lib/sidekiq/job.rb, lib/sidekiq/job/iterable.rb, lib/sidekiq/job/iterable/active_record_enumerator.rb, lib/sidekiq/job/iterable/csv_enumerator.rb, lib/sidekiq/job/iterable/enumerators.rb, lib/sidekiq/job/iterable/nested_enumerator.rb, lib/sidekiq/job_retry.rb, lib/sidekiq/processor.rb, test/fixtures/products.csv, test/iterable/active_record_enumerator_test.rb, test/iterable/csv_enumerator_test.rb, test/iterable/iterable_jobs.rb, test/iterable/iterable_test.rb, test/iterable/nested_enumerator_test.rb, test/processor_test.rb, test/transaction_aware_client_test.rb
This is a native implementation of the https://github.com/fatkodima/sidekiq-iteration pattern.
Closes https://github.com/fatkodima/sidekiq-iteration/issues/6.
At a high level, the API will look something like:
```ruby
class NotifyUsersJob
include Sidekiq::Job
include Sidekiq::Job::Iterable
def build_enumerator(cursor:)
active_record_records_enumerator(User.all, cursor: cursor)
end
def each_iteration(user)
user.notify_about_something
end
end
```
=> Add iteration support for long-running jobs

Changes.md, examples/webui-ext/lib/sidekiq-redis_info.rb, examples/webui-ext/lib/sidekiq-redis_info/web.rb, examples/webui-ext/readme.md, examples/webui-ext/sidekiq-redis_info.gemspec, examples/webui-ext/web/assets/redis_info/css/ext.css, examples/webui-ext/web/assets/redis_info/js/ext.js, examples/webui-ext/web/locales/en.yml, examples/webui-ext/web/views/redis_info.erb, lib/sidekiq/redis_client_adapter.rb, lib/sidekiq/redis_connection.rb, lib/sidekiq/web.rb, lib/sidekiq/web/action.rb, lib/sidekiq/web/helpers.rb, myapp/Gemfile, myapp/config/routes.rb
In order to lock down JS and CSS for better security, we need to provide a first-class API for web extensions so they can opt into better asset security while maintaining compatibility with existing versions.
Please see the content under `examples/webui-ext` and specifically the new `register` API:
```ruby
Sidekiq::Web.register(SidekiqExt::RedisInfo::Web,
name: "redis_info",
tab: ["Redis"],              # The name on your Tab(s)
index: ["redis_info"],       # The path to the root page(s) of your extension within the Web UI, usually "/sidekiq/" + index
root_dir: SidekiqExt::RedisInfo::Web::ROOT, # root directory for all web ui content
asset_paths: ["css", "js"],  # Paths within {root}/assets/{name} to serve static assets
cache_for: 86400            # Enable http caching for one day of …
```
=> New registration API for web extensions

lib/sidekiq/client.rb, test/client_test.rb
It appears that when jobs are scheduled with the default client, in case the Redis client raises an error that is then subsequently retried, the jobs get pushed into the queue itself, not the sorted set. This happens because `atomic_push` deletes the `at` key from every payload, which triggers the other branch of the method on the next retry, which `lpush`es the payloads directly into the original queue.
Here's a short reproduction script that displays the problem, should be run in the current main branch:
```ruby
#!/usr/bin/env ruby
require "bundler/inline"
require "prettyprint"
gemfile do
source "https://rubygems.org"
gem "sidekiq", path: "."
end
AGGREGATOR = Hash.new do |hash, key|
hash[key] = Hash.new do |inner_hash, inner_key|
inner_hash[inner_key] = []
end
end …
```
=> Make scheduled jobs be correctly scheduled in case the Redis client raises an error that is then retried successfully

lib/sidekiq/middleware/current_attributes.rb, test/current_attributes_test.rb
Ensure CurrentAttributes are restored to their original values, rather than cleared.
Fixes #6306
=> Retain CurrentAttributes after inline execution

Changes.md, sidekiq.gemspec
Sidekiq uses this and it's getting the same treatment like `base64`, `mutex_m`, etc. Starting in Ruby 3.4 a warning will be emitted, and Ruby 3.5 will error
Closes #6319
=> Add `logger` as an explicit dependency

Changes.md, lib/sidekiq/middleware/current_attributes.rb, test/current_attributes_test.rb
Fixes #6341.
I can't think of an easy way of safely removing the CurrentAttributes value without breaking the existing job 🤔. And it forces people to always remember about this gotcha.
I think we can just ignore non-existing attributes when restoring.
=> Ignore non-existent CurrentAttributes attributes when restoring

web/assets/stylesheets/application.css
Closes: https://github.com/sidekiq/sidekiq/issues/6327#issue-2346777247
Resolves the bottom nav bar overlap by removing the media query and keeping the nav bar fixed to the bottom of the page.
=> fix bottom nav bar overlap on large screen devices

docs/Pro-7.0-Upgrade.md
We ran into an error when trying to upgrade Sidekiq gems to v7 without first upgrading `dogstatsd-ruby` from v4 to v5.
```rb
NoMethodError
undefined method `host' for #<Datadog::Statsd:0x00007f29c1c5bc40 ...
...
sidekiq-pro (7.2.1) lib/sidekiq/pro/metrics.rb in block in location at line 81
```
Adding a note for others that may run into the same issue.
=> Add note about required dogstatsd-ruby gem version

lib/sidekiq/web/helpers.rb, test/web_helpers_test.rb
On Ruby 2.7 (and earlier), when a frozen magic comment is encountered, interpolated strings are frozen as well.
Closes #6371
=> Fix `script_tag` and `style_tag` on Ruby 2.7

Changes.md, lib/sidekiq/client.rb
Closes #6376
@mhenrixon is correct in his assesment that this method is loaded through activesupport. I'm not sure if there is a good solution so that this doesn't happen again in the future. There would need to be some isolation so that rails specific tests don't polute.
For example, these are the extra methods available when running tests, through activesupport, on a Hash with Ruby 2.7:
```rb
m = {}.methods
require "active_support"
{}.methods - m
```
=> Don't use `Hash#except` which only got added in Ruby 3.0

web/locales/tr.yml
Ruby version: 3.3.0
Rails version: 7.1.3.4
Sidekiq / Pro / Enterprise version(s): 7.3.0
The error caused by ignoring the need to use quotation marks when the interpolation variable in the translation for the **AreYouSureDeleteQueue** keyword is at the beginning of the sentence has been fixed.
=> Fix yaml syntax problem in tr.yml

lib/sidekiq/redis_connection.rb, test/redis_connection_test.rb
redis-client does support providing sentinels via urls, but when trying to use such config in sidekiq and having logging enabled, it errors
> TypeError: no implicit conversion of Symbol into Integer
> lib/sidekiq/redis_connection.rb:74:in `[]'
Funny point is that it does not error, when sidekiq's logger level is filtering `info` thus it did not show up in my tests at first, only in production 🙈 
This PR fixes `RedisConnection::scrub` so that it does not choke on strings in sentinels.
=> Fix startup error when redis sentinel is provided as an url

lib/sidekiq/api.rb, test/api_test.rb
Was trying this out on the latest release and there was a typo: `opt` should have been `opts` 🤦 
Also corrected the yardoc to render the options correctly.
=> Fix bug in Deadset#kill ex param

web/assets/stylesheets/application.css
Closes: https://github.com/sidekiq/sidekiq/issues/6409
Reverting https://github.com/sidekiq/sidekiq/pull/6350 while providing a new fix for [the original issue](https://github.com/sidekiq/sidekiq/issues/6327) of the nav bar overlapping content in the body of the page.
Reducing the max-width of the `redis-url` will prevent the wrapping of elements in the footer and the overlap on the body contents.
Before (buttons are not visible):
After:
=> Reduce max-width for redis-url elements

test/sidekiqmon_test.rb
Ruby 3.3.5 warns when requiring `ostruct` from the standard library (as opposed to requiring it as a gem). Such a warning can be seen in the Ruby 3.3 build in CI [here][1], since `test/sidekiqmon_test.rb` has `require "ostruct"`, but `ostruct` is not specified in the Gemfile or gemspec as a gem dependency.
[1]: https://github.com/sidekiq/sidekiq/actions/runs/10710835954/job/29698382673#step:6:7
This is the warning:
> /home/runner/work/sidekiq/sidekiq/test/sidekiqmon_test.rb:4: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
>
> You can add ostruct to your Gemfile or gemspec to silence this warning.
In order to get rid of that warning when running tests, this change removes all usage of `OpenStruct` from …
=> Replace usage of OpenStruct with Struct

lib/sidekiq.rb, lib/sidekiq/capsule.rb, lib/sidekiq/processor.rb, lib/sidekiq/testing.rb
Changed the variable name "inst" to "instance" for readability.
=> Renamed inst to instance

web/locales/en.yml, web/locales/fr.yml, web/locales/gd.yml, web/locales/ja.yml, web/locales/pt-br.yml, web/locales/tr.yml, web/locales/zh-cn.yml, web/locales/zh-tw.yml
It was added in https://github.com/sidekiq/sidekiq/commit/0b3751bf29088cb703d40787bb52f0cb6aa6e74f#diff-4868d859ec62d1b0e36a0f14cba4c81c045b9738117c11bbe53adae8b7871772R92 but is not used.
=> Remove 'Bucket' localization

lib/sidekiq/web.rb, lib/sidekiq/web/action.rb
Fixes #6407.
Backtrace after:
```
/sidekiq/web/views/morgue.erb:7:in `_erb_morgue'
/sidekiq/lib/sidekiq/web/action.rb:99:in `_erb'
/sidekiq/lib/sidekiq/web/action.rb:68:in `erb'
/sidekiq/lib/sidekiq/web/application.rb:160:in `block in <class:WebApplication>'
/sidekiq/lib/sidekiq/web/application.rb:416:in `instance_exec'
/sidekiq/lib/sidekiq/web/application.rb:416:in `block in call'
/sidekiq/lib/sidekiq/web/application.rb:414:in `catch'
/sidekiq/lib/sidekiq/web/application.rb:414:in `call'
/sidekiq/lib/sidekiq/web/csrf_protection.rb:51:in `admit'
/sidekiq/lib/sidekiq/web/csrf_protection.rb:40:in `call'
```
=> Show template filename in ERB error backtraces

lib/sidekiq/job/iterable.rb, test/iterable/iterable_jobs.rb, test/iterable/iterable_test.rb
Add  `arguments` accessor method to IterableJob so callbacks can easily access job arguments, see #6453
=> Access arguments in iteration callbacks

docs/7.0-API-Migration.md
Noticed this small typo while reading through the doc.
=> Fix typo in Sidekiq 7.0 migration doc

lib/active_job/queue_adapters/sidekiq_adapter.rb
When Ruby parses the expression
```ruby
defined?(:ANY_SYMBOL_IMAGINABLE)
```
it recognizes the symbol `:ANY_SYMBOL_IMAGINABLE` and adds it to its list of known symbols. Therefore the expression
```ruby
defined?(:ANY_SYMBOL_IMAGINABLE)
```
will always be truthy.
If we use
```ruby
module ActiveJob
module QueueAdapters
remove_const(:SidekiqAdapter) if defined?(SidekiqAdapter)
```
This checks for the existence of `::ActiveJob::QueueAdapters::SidekiqAdapter`, but would also give a false positive if `::ActiveJob::SidekiqAdapter` or `::SidekiqAdapter` are defined.
What we really want is
```ruby
module ActiveJob
module QueueAdapters
remove_const(:SidekiqAdapter) if defined?("::#{name}::SidekiqAdapter")
```
=> Fix check whether SidekiqAdapter is defined or not

lib/sidekiq/rails.rb
Fixes https://github.com/rails/rails/issues/53460 (cc @zzak)
We have a circular require error
https://github.com/rails/rails/blob/e6429269fd5a8a7d728557f4e7d7f82c0ad1478c/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L4
https://github.com/sidekiq/sidekiq/blob/bd3604909687bb0a0f4e71e087eb5a75e69fdf83/lib/sidekiq/rails.rb#L8
=> Fix circular require for ActiveJob integration

web/assets/stylesheets/application.css
With Sidekiq Pro and Enterprise installed and a long redis URL, the footer nav overflows onto two rows at multiple breakpoints, including large screens. The double-height footer can make it hard to access the elements at the bottom of some pages, like the buttons at the bottom of the Retries page.
The wrapping is caused by the 15px margin added by `.nav-text`, which reduces the responsive container’s width by 30px. When the combined text items are long enough, the elements start to wrap.
Removing the extra margin on the edges allows the nav element to fill the container so the items fit on one row at all screen sizes.
**Before:**
**After:**
=> Allow footer nav to fill container

Changes.md, lib/sidekiq/api.rb, test/api_test.rb, test/dead_set_test.rb
Instead of a paginated cursor, fixes #6481.
=> Rewrite retry_all and kill_all APIs to use ZPOPMIN 

lib/active_job/queue_adapters/sidekiq_adapter.rb
Followup #6474. cc @leoarnold 
`defined?` for a string literal is always truthy, same as for symbols. `defined?(ActiveJob::QueueAdapters::SidekiqAdapter)` would work as an alternative.
```rb
module ActiveJob
module QueueAdapters
end
end
module ActiveJob
module QueueAdapters
remove_const(:SidekiqAdapter) if defined?("::#{name}::SidekiqAdapter")
end
end
```
`test.rb:10:in 'remove_const': constant ActiveJob::QueueAdapters::SidekiqAdapter not defined (NameError)`
=> Correctly remove the buildin rails adapter

lib/sidekiq/web/application.rb, test/filtering_test.rb, test/web_test.rb, web/views/filtering.erb, web/views/metrics.erb
This tackles a small paper cut I've been feeling on Sidekiq's useful Web UI: Applying filters, e.g. to the "Metrics" tab, changes the URL, which breaks reloads. Also, it's not possible to share a permalink to a pre-filtered list.
On the web, filtering a list is usually done with GET requests, using query string parameters. Such an operation does not have side effects, so it can be considered [safe](https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP).
---
Previous, related changes:
- 1b9f7db4c5d0dc41b6eac2682710715eed5aadce
- #6440
---
To test the waters, I only applied this change to the "Metrics" tab. If you like the idea, I will happily and quickly expand the scope to all other tabs with filtering.
=> Sidekiq Web: Apply filters on GET requests

lib/sidekiq/job_retry.rb
I noticed the way the random retry jitter logic was currently set up, there are really only 11 possible values at each retry step.  Even once the `count` has grown and the possible range of jitter values is large, they are still being bucketed into one of the 11 possible values.  I'd like to see a wider range of possible outcomes so that if a large number of jobs all fail at the same time they won't be as clumped together when retrying.
I read your caution about bike shedding in the retry logic, but this just seems like it would produce better results for everyone.  I'm struggling to come up with a scenario where anyone would prefer the current logic of clustering the jitter into 11 distinct buckets at each retry step.
One note, this change would slightly change the average jitter numbers …
=> Change jitter logic to allow full range of possible choices

lib/sidekiq/config.rb, lib/sidekiq/logger.rb, lib/sidekiq/processor.rb, test/exception_handler_test.rb, test/helper.rb
Adjust default error reporter to use newer Ruby APIs and provide the full error backtrace in :debug.
With log level `:info`, Sidekiq will display the exception's message and any detailed context. For instance a JSON::GeneratorError will include the invalid object which triggered the error.
With log level `:debug`, Sidekiq will also include the backtrace of the error. Unfortunately because the backtrace is formatted in `Exception#full_message`, we lose the ability to clean/prune the error's backtrace, a la Rails. In my experience it's better to see the full trace anyhow.
The backtrace cleaner will still be available to trim the `error_backtrace` element stored within retries.
Fixes #6518
=> Better error logging

lib/sidekiq/api.rb, test/api_test.rb
According to the documentation, `#latency` returns Float.
> Returns:
> (Float) — in seconds
> https://www.rubydoc.info/github/mperham/sidekiq/Sidekiq%2FQueue:latency
But, it returns integer 0 when there's no job entry.  
This behavior is problematic when you want to send `#latency` to somewhere that require type definition.
I have faced this problem when I tried to send latency to [Google Cloud Metrics](https://cloud.google.com/monitoring/api/metrics_gcp)
This PR makes `#latency` to send float 0.0 even if there's no job entry.
=> Make queue latency always float even if there's no job entry

lib/sidekiq/capsule.rb, lib/sidekiq/component.rb, lib/sidekiq/config.rb, test/actors_test.rb, test/processor_test.rb
Ruby's default 100ms timeslice can cause significant delays in threading if the user has configured high concurrency with CPU heavy jobs (e.g. the old Sidekiq default of 25 threads). Worst case, each of those 25 threads can wait 2.5 seconds before they get back on the CPU. Now imagine an IO timeout set for 1 second -- it's quite possible to see random TimeoutErrors due to timeslice starvation.
This PR adjusts the default Thread.priority for all Sidekiq threads to be -1, or a 50ms timeslice. -2 would use a 25ms slice.
The user can adjust the priority like so:
```ruby
Sidekiq.configure_server do |cfg|
cfg.thread_priority = 0
end
```
See also https://github.com/bensheldon/good_job/issues/1554
=> Change Sidekiq's default thread priority to -1

lib/sidekiq/client.rb, test/client_test.rb
This PR changes the way `atomic_push` chooses the queue to send payloads. Instead of taking the first one, it regroups payloads by queue and dispatch them. Fix #6546
=> push bulk with dynamic queues

lib/sidekiq/paginator.rb, lib/sidekiq/web/helpers.rb, sidekiq.gemspec
I found a few bits of (very) low hanging fruit.
1. The code was not caching the locale strings in `web/locales`. Maybe this was a memory optimization from long ago but the performance hit is huge.
2. Add a cache for key type when paginating to avoid a Redis roundtrip. We don't paginate dynamic keys so this cache should be limited in growth/size.
10,000 requests to `/queues`
Before: 107 sec
After: 6 sec
=> Web UI Tuning

lib/sidekiq/job_retry.rb, test/profiling_test.rb
I just saw: https://bugs.ruby-lang.org/issues/20966
`String#b` is the most convenient method to create a mutable binary string.
I also replaced encoding strings by the actual constants.
=> Use String#b to create a mutable binary string

web/views/morgue.erb, web/views/retries.erb
Resolves #6581 
From a UX perspective, it is not immediately intuitive to click on this time information to get error details.
Add a second link to the Error column.
Ran locally.
https://github.com/user-attachments/assets/c4357d44-670e-4f35-aa44-ebecadf0db0f
https://github.com/user-attachments/assets/ef28b4be-3d4e-4cc8-b589-0cf3f63aade5
=> Add second link to error details from morgue and retries list

lib/sidekiq/api.rb
`WorkSet#find_work_by_jid` is not consistent in naming with other methods to find by jid, for example `Queue#find_job` and `JobSet#find_job`.
=> Add alias for `WorkSet#find_work_by_jid` method

lib/sidekiq/job/iterable.rb
Currently, cancelling an iterable job works only when the job was interrupted and it starts again. In this case the cancellation flag is checked correctly.
When the job is running, the flag's value is checked incorrectly, because it is set to a timestamp in the codebase.
https://github.com/sidekiq/sidekiq/blob/6a360285c146628d6332bf4a68d85c419330c27d/lib/sidekiq/client.rb#L68
I haven't added tests, because looks like it will be particularly hard to test this case (the test case should at least use a new interrupting thread).
=> Fix iterable jobs cancellation

web/assets/javascripts/dashboard-charts.js, web/assets/javascripts/dashboard.js, web/assets/stylesheets/style.css, web/locales/en.yml, web/views/dashboard.erb
This adds another accessibility improvement, following on from my previous PR.
When there is an update in the dashboard, if the user is using a screen reader, they should be informed about the update.
This PR makes it so the screen reader will say "Latest poll: Processed: 16. Failed: 0." each update if there is a change (the polling frequency is the same as for the graph, and can be updated the same way).
This works thanks to the `role="status"` attribute. The text will only be read when the user is idle. It will not interrupt other activity.
I added back the `sr-only` CSS class that I removed in the previous PR, since it is now needed for the screen reader update span.
As this was a more involved change than the previous change I made, I asked for a review from a Senior Frontend …
=> Accessibility polling updates

Changes.md, lib/sidekiq/job/iterable.rb
I need to have access to the current cursor inside the iterable job, to store it externally (basically a db table row with some metadata about the iterable job). Currently, can access it only via an instance variable.
=> Expose current cursor inside iterable jobs

web/assets/stylesheets/style.css, web/views/_nav.erb, web/views/layout.erb
Fixes two minor accessibility issues. Violations:
- `<html> element must have a lang attribute`
- `<li> elements must be contained n a <ul> or <ol>`
- `Elements must meet minimum color contrast ratio thresholds`
`ul` can't have the `role` navigation but it's parent can. It is expected that the contained `<li>`'s are on a `role="list"` but it has `role="navigation"` set. We can easily solve this violation by moving the `role` to the parent `div`.
See also this example here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/navigation_role#examples
The language (`lang`) attribute is missing on the `html` tag. Adding the `lang` attribute to the `html` element will fix this small issue.
This is only fixable if you would change your primary color in darkmode. A possible …
=> Fix accessibility issues

.github/workflows/ci.yml, README.md
Dragonfly does publish tags to docker builds:
https://github.com/dragonflydb/dragonfly/discussions/3233
Add the minimum supported version to CI - `1.13+` as per README.
=> Add dragonfly version tags to CI

.github/workflows/ci.yml
This PR follows 03c654ebe2538cca526d121478106ab89f783a04, where Sidekiq
lowered the Redis dependency requirement from 7.2 to 7.0, this time
ensuring that CI follows suit.
=> Drop Redis to 7.0 on CI

lib/sidekiq/config.rb, lib/sidekiq/launcher.rb, myapp/config/initializers/sidekiq.rb
This pull request proposes to introduce another hook called `:exit`, that will be triggered in the end of the shutdown cycle, and allow users to perform final cleanup, such as flushing and closing Karafka producers. It essentially works similarly to `at_exit` Ruby hook, but wrapped in a more idiomatic (from Sidekiq perspective) way of defining hooks.
```ruby
config.on(:exit) do
::Karafka.producer.close
end
end
```
When producing Karafka events from Sidekiq, we occasionally receive `WaterDrop::Errors::ProducerClosedError`. We tracked down the issue to [this recommendation from Karafka docs](https://karafka.io/docs/Producing-Messages/#closing-producer-used-in-sidekiq):
```ruby
config.on(:shutdown) do …
```
=> Added :exit event that will be triggered after all workers exited during shutdown

lib/sidekiq/embedded.rb
This PR fixes Redis version requirement in embedded mode.
https://github.com/sidekiq/sidekiq/blob/68b5462fb0a0a1a0299acb2edc0c7cff11e60f71/README.md?plain=1#L13-L16
https://github.com/sidekiq/sidekiq/blob/68b5462fb0a0a1a0299acb2edc0c7cff11e60f71/lib/sidekiq/cli.rb#L79
=> fix: Redis version requirement in embedded mode

lib/sidekiq/web/application.rb
Seems like they are debugging leftovers giving as this warning:
```
WARN  2025-03-21T13:27:39.832Z pid=201290 tid=2fga: Route parameter `mike` should be accessed via Symbol, not String
(at ruby/3.3.7/lib/ruby/gems/3.3.0/gems/sidekiq-8.0.1/lib/sidekiq/web/application.rb:243:in `block in <class:Application>')
```
=> Remove obsolete "mike" params in `retries` action

lib/active_job/queue_adapters/sidekiq_adapter.rb, lib/sidekiq.rb, lib/sidekiq/rails.rb
Remove the assumption that Rails will be installed from the meta gem or granular with ActiveJob.
- A script could be using ActiveJob in standalone and won't need Rails initialization
- A Rails application could have Sidekiq and not use the ActiveJob wrapper to reduce dependencies
This change wraps relevant code in `if defined?` checks to ensure Sidekiq only loads what's needed based on the actual environment dependencies.
Fixes #6668
=> Conditionally load ActiveJob and Rails integrations

lib/sidekiq/middleware/current_attributes.rb, test/current_attributes_test.rb
~Instead of waiting for an error and then filtering out any current attributes, only attempt to set the ones that currently exist.~
If we have successfully set the current attributes, we don't retry if we catch an error.
The `NoMethodError` that was being rescued from also applied to the job that was being wrapped. This caused errors to be silently hidden and the job retried without going into the retry queue, or alerting any bug tracking tools that have been set up.
This recently bit us in a worker calling a third party API because of a bug in our code after the response was received. A NoMethodError was raised, and we retried the API call without being alerted to the failure. The API responded differently the second time (because we'd already made that request), and the second time the …
=> Don't swallow NoMethodErrors in jobs setting current_attributes

lib/sidekiq/web/helpers.rb
In Ruby 3.5, most of the `cgi` gem is removed. Only methods relating to escaping/unescaping are retained.
Those are the only thing that's being used, so use the more specific require and avoid the warning that would otherwise be emitted. Doing it like this works since Ruby 2.4.
https://bugs.ruby-lang.org/issues/21258
=> Only require what is necessary from `cgi` for Ruby 3.5

lib/sidekiq/web/helpers.rb, test/web_helpers_test.rb
- Matching is case-insensitive
- Exact matches are done in order of quality value first
- Fallback to base language is attempted next, "es-CO" => "es"
- If no matches, then fallback to "en"
Fixes: #6717
https://www.rfc-editor.org/rfc/rfc9110.html#section-12.5.4
https://www.rfc-editor.org/rfc/rfc4647.html#section-3.4
=> Update Accept-Language header locale matching

lib/active_job/queue_adapters/sidekiq_adapter.rb, lib/sidekiq/rails.rb, test/dummy/bin/rails, test/dummy/config/application.rb, test/dummy/config/boot.rb, test/dummy/config/initializers/active_job.rb, test/dummy/config/initializers/sidekiq.rb, test/rails_test.rb
This is an extension of @seuros's PR #6689
Referencing ActiveJob::Base during the Rails initialization process can cause it to load too soon, which results in app-level config (eg `config.active_job.logger`) being ignored.  (These settings are only copied onto ActiveJob::Base once, the first time it loads at https://github.com/rails/rails/blob/fcf01b8820b6e4c3bd70ae3cc653229bbe5a1fba/activejob/lib/active_job/railtie.rb#L80-L82).
This broke in Sidekiq 8.0.3 due to https://github.com/sidekiq/sidekiq/pull/6669.
I've tried to demonstrate that in a new test case here - https://github.com/jdelStrother/sidekiq/blob/16c2f8589e3022fdc081ebd0196ad4a8b31e4774/test/rails_test.rb#L51-L59 - which passes on 8.0.2 and fails on 8.0.3. The test case itself is kind of hacky, open to better suggestions.
I …
=> Don't load ActiveJob::Base during initialization

lib/sidekiq/middleware/current_attributes.rb
We use CurrentAttributes (with the related sidekiq middleware enabled) and rails sharding.
We have a custom client middleware that does some logic depending on the shard value in our `Current` instance. All is good and works correctly until the job is failed and enqueued for a retry. Because when sidekiq's scheduler retrieves the job from the retry queue (to push it to a regular queue), it runs the client middleware again before pushing. https://github.com/sidekiq/sidekiq/blob/d70ef9bf1e5b7b9d39838b2a9b9acc5f468a5ec5/lib/sidekiq/scheduled.rb#L39
The job has a `Current` stored from the first try, but it is not restored when pushing by the scheduler, so the logic in our custom client middleware is incorrect now.
=> Load CurrentAttributes inside client

web/locales/uk.yml
🔄 Replaced harsh terminology: Killed → Stopped
This pull request updates the Ukrainian translations related to job termination in the UI. Specifically, we’ve replaced the word "вбиті" (translated from "Killed") with "зупинені" ("Stopped") to make the interface more user-friendly and emotionally neutral.
✅ What was changed:
"Dead" → "Зупинені"
"DeadJobs" → "Зупинені задачі"
"NoDeadJobsFound" → "Зупинених задач не знайдено"
"Kill" → "Зупинити"
"KillAll" → "Зупинити все"
🧠 Rationale:
The word "вбиті" ("Killed") sounds unnecessarily violent or aggressive in Ukrainian, which can be jarring to users — especially non-technical audiences.
"Зупинені" ("Stopped") conveys the same technical meaning (a job that was terminated and won’t be retried), but in a more neutral, professional, and …
=> Update uk.yml to be more polite

web/assets/stylesheets/style.css
The selection color had too little contrast and overriding the browser default harms accessibility.
See https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#accessibility:
> Don't override selected text styles for purely aesthetic reasons — users can customize them to suit their needs. For people experiencing cognitive concerns or who are less technologically literate, unexpected changes to selection styles may hurt their understanding of the functionality.
When selecting everything on the page (cmd+A), this is the result (last row in the table hovered):
=> Remove custom CSS ::selection color

lib/sidekiq/rails.rb
As per https://apidock.com/rails/ActiveSupport/Logger/broadcast/class ActiveSupport::Logger.broadcast is no longer supported after rails v7.0.0
=> Handle ActiveSupport::Logger.broadcast deprication

lib/sidekiq/job_retry.rb, test/retry_exhausted_test.rb, test/retry_test.rb
This allows death handlers to distinguish between jobs were discarded and jobs that were not.
Refer to https://github.com/sidekiq/sidekiq/issues/6741#issuecomment-3315046721 for context.
=> Track discarded_at in job payload when job is discarded.

lib/sidekiq.rb, lib/sidekiq/api.rb, lib/sidekiq/loader.rb, test/api_test.rb, test/loader_test.rb
Relevant #6823.
The new api to the loader is like:
```ruby
Sidekiq.loader.on_load(:component) do
end
Sidekiq.loader.run_load_hooks(:component)
```
A similar API to what Rails uses https://github.com/rails/rails/blob/main/activesupport/lib/active_support/lazy_load_hooks.rb
The loader is currently accessible via `Sidekiq.loader`, but can change to `Sidekiq::Loader` only if we want for it to be a private API and less discoverable.
=> Add ability to extend sidekiq/api when it is loaded
