sidekiq/sidekiq

- web/locales/ru.yml
> add missing russian translations

- Changes.md
- lib/sidekiq/web.rb
- test/test_web.rb
- web/views/dashboard.erb
> Add /stats, /stats/queues, & /stats/queues/:name json endpoints to web

- lib/sidekiq/api.rb
- lib/sidekiq/web.rb
- test/test_api.rb
My attempt to load the stats in pipeline. This was the simplest way I could think of.
Comment are welcome :smile:
> Load stats with pipeline

- test/test_api.rb
1. Fix `failed` method call
2. Delete excess comments
> Update API test file

- lib/sidekiq/middleware/server/retry_jobs.rb
```
➜  git:(master) ✗ cat config/initializers/sidekiq.rb
config.server_middleware do |chain|
chain.add Middleware::Server::RetryJobs, :max_retries => 3
end
end
➜ git:(master) ✗ bundle exec sidekiq
uninitialized constant Middleware
/web/config/initializers/sidekiq.rb:5:in `block (2 levels) in <top (required)>'
```
> documentation update

- web/assets/stylesheets/application.css
- web/views/dashboard.erb
> Fix charts position on dashbord page [web UI]

- Changes.md
- web/assets/javascripts/application.js
- web/views/_poll.erb
For more information you can see mperham/sidekiq#2266 issue
> Change page reload on ajax request in livepoll mode

- web/assets/stylesheets/application.css
*You can check this changes on your devices on [this link](http://sidekiq-history-gem.herokuapp.com/sidekiq/)*
> Fix displaying navbars for tablet devises

- web/locales/hi.yml
Adding hindi locale for sidekiq web UI
> Add Hindi locale.

- lib/sidekiq.rb
- test/test_sidekiq.rb
Lunch conversation expectations, satisfied.
> Remove sexism

- lib/sidekiq/scheduled.rb
from https://github.com/mperham/sidekiq/issues/2317
This makes the Poller's randomness more reliable by reducing the worst case outliers: polling too much (unnecessary load on Redis) or too little (undesired gaps in scheduling). The statistical average should remain the same.
> calculate each poll interval in a tighter range with the same average

- web/assets/javascripts/application.js
> Call timeago() for new <time> tags during live pull

- lib/sidekiq/testing.rb
> Set Worker's bid when using Sidekiq::Testing

- web/assets/stylesheets/application.css
- web/views/_job_info.erb
- web/views/busy.erb
- web/views/dead.erb
- web/views/morgue.erb
- web/views/queue.erb
- web/views/queues.erb
- web/views/retries.erb
- web/views/retry.erb
- web/views/scheduled.erb
> Create table containers with overflow is overlay

- lib/sidekiq/manager.rb
- test/test_manager.rb
This allows other code to add elements to the proctitle.
> Refactor proctitle creation

- lib/sidekiq/manager.rb
> Use new proc syntax instead Proc.new

- examples/upstart/manage-one/sidekiq.conf
It works better without the tooth marks.
> Don't mange sidekiq

- test/test_retry.rb
We want to use retry => 0 for tasks that we don't want to retry but still should go to the dead queue (monitoring these, possibly manually restarting if needed / acceptable)
Good thing is that it's already supported. So I'm just adding a test case for that.
> Adding test case for retry => 0

- Changes.md
Sometimes it's the little things in life that count !
> Fix typo "Vulenerability"

- lib/sidekiq/web.rb
> Enable sessions so Rack::Protection will work

- lib/sidekiq/middleware/server/logging.rb
@mperham was about to do another PR and then realized that that would not work ... this is still a good change I guess ... do you want it ?
> small refactor for Logging middleware

- css/global.css
- index.html
- Fixed nojs issue for purchase bar
- Tweaked buy button on product matrix to work with narrower screens (see img)
> Styling Fixes

- lib/sidekiq/api.rb
- test/test_api.rb
- web/locales/en.yml
- web/views/_job_info.erb
> Have enqueued_at time be nil for jobs that have yet to be enqueued

- lib/sidekiq/processor.rb
- test/test_processor.rb
This fixes #2531. 
Tests required a lot of setup, but the actual fix is simple. This should have the exact same behavior as before except for the case where the middleware raises an exception before yielding. In that case, we didn't actually perform the job, so don't ack.
> Don't ack unless we attempted to start working on the job

- css/global.css
- index.html
> Fix money back text overlay

- test/test_api.rb
- test/test_cli.rb
- test/test_client.rb
- test/test_extensions.rb
- test/test_logging.rb
- test/test_manager.rb
- test/test_processor.rb
- test/test_rails.rb
- test/test_redis_connection.rb
- test/test_retry.rb
- test/test_scheduled.rb
- test/test_scheduling.rb
- test/test_sidekiq.rb
- test/test_testing.rb
- test/test_testing_fake.rb
- test/test_testing_inline.rb
- test/test_util.rb
- test/test_web.rb
- test/test_web_helpers.rb
Remove Redis mocking.  Minimize Redis flushing where possible.
> Test suite overhaul

- lib/sidekiq/middleware/server/retry_jobs.rb
- test/test_retry.rb
Sample implementation of allowing exception to dictate retry interval behavior .. eg. for coupling with OverLimit behavior from the enterprise rate limiting primitive
> Make exception available in #sidekiq_retry_in

- lib/sidekiq/api.rb
`while true` is used throughout the project and it is two times faster than kernel loop
> Replace kernel loop with while loop

- web/assets/stylesheets/application.css
- web/views/_footer.erb
Also added title attributes so on-hover shows full string.
> Using percentage sizes for footer information with ellipses overflow.

- 4.0-Upgrade.md
- Changes.md
- lib/sidekiq/testing.rb
- test/test_testing_fake.rb
ref: https://github.com/mperham/sidekiq/issues/2663
> Remove Queue Testing API due to incompatibility with Rspec

- lib/sidekiq/web.rb
> add absolute namespace for Rack::Protection

- .travis.yml
> Test against ruby 2.3

- index.html
Fix footer for #2735 
I will look at other parts later.
> Center text for footer

- css/global.css
- index.html
Fixed #2735
I didn't check this layout on windows, linux and android. If you can - do it please.
> Update table layout on index page

- web/locales/ja.yml
I added Japanese translation entries to the locale file.
> Add Japanese translations

- web/locales/ja.yml
I updated Japanese translations for the locale file.
I think that it became more natural to the native speakers.
Thanks.
> Improved Japanese translations

- test/test_scheduled.rb
Reference https://github.com/rails/rails/pull/22890
> Improve schedule test speed

- lib/sidekiq/api.rb
Same optimization as the queue class.
Compute the range size once.
> Apply range_start optimization in SortedSet class

- _includes/footer.html
- css/global.css
> Create new design for subscribe email form

- products/enterprise.html
- products/pro.html
- support.html
> Delete unnecessary footer layouts

- css/global.css
> Center contribsys logo and change sidekiq for white in footer

- web/locales/fr.yml
Hi!
Just a few changes on current French translations. 
I added the missing keys as well.
Best
> Additions / changes in French locales

- index.html
> Add links for each feature on wike page

- .travis.yml
> Fix JRuby build

- web/views/busy.erb
I've accidentally hit these buttons quite a few times stopping/quieting my workers.
> Add confirmation when quieting and stopping all workers

- lib/sidekiq/api.rb
- lib/sidekiq/middleware/server/retry_jobs.rb
It's not really that important but I think it will be a little more clear.
> Very minimal changes on paragraphs and spaces.

- web/locales/ru.yml
> Update russian locale

- Pro-Changes.md
> Fix incorrect version number within Pro-Changes.md

- web/assets/stylesheets/application.css
- web/views/_footer.erb
- web/views/busy.erb
- web/views/morgue.erb
- web/views/queue.erb
- web/views/queues.erb
- web/views/retries.erb
- web/views/scheduled.erb
Based on this [pull request ](https://github.com/mperham/sidekiq/pull/3079) this replaces the inline CSS with classes.
> Removing Inline CSS

- lib/sidekiq/processor.rb
Followup to https://github.com/mperham/sidekiq/pull/3224.
The Processor class has a `#job` method which was being shadowed in `#process` by a local variable. The `#process` method is complex, and I recently moved some code around in a way that accidentally resulted in the instance method being used instead of the local variable: https://github.com/mperham/sidekiq/issues/3223
By using a different name for the variable, making that same mistake again will result in a `NameError` instead of doing the wrong thing.
> Don't shadow job method in Processor

- lib/generators/sidekiq/templates/worker_test.rb.erb
I am getting this error:
```
/Users/ceritium/work/sidekiq_example_require_relative/test/workers/hard_worker_test.rb:1:in `require_relative': cannot load such file -- /Users/ceritium/work/sidekiq_example_require_relative/test/workers/test_helper (LoadError)
```
This is a simple demo of the error: https://github.com/ceritium/sidekiq_example_require_relative
> Fix test generator

- web/locales/ar.yml
The current Arabic translation is incorrect and I wanted to help improving it.
> improving Arabic translation

- lib/sidekiq/testing.rb
> Ensure Rails module has #env

- web/locales/he.yml
Incorporating [input](https://github.com/mperham/sidekiq/pull/3405) from @rantav, thanks!
> Improve Hebrew Support

- lib/sidekiq/web/helpers.rb
- test/test_web_helpers.rb
See: https://github.com/mperham/sidekiq/pull/3448 and https://github.com/mperham/sidekiq/issues/3437
cc @natematykiewicz @mperham 
I continued on @natematykiewicz's work. This PR passes all tests. It borrows some code from https://github.com/iain/http_accept_language/blob/master/lib/http_accept_language/parser.rb.
> Improve parsing of HTTP_ACCEPT_LANGUAGE (continue Nate's work)

- lib/sidekiq/api.rb
> Fix race condition in Sidekiq API

- Changes.md
> Fix typo on Changes.md

- lib/sidekiq/client.rb
Was wondering if enterprise-specific features worked here.
> Document that anything in sidekiq_options can also be sent to push

- Changes.md
- lib/sidekiq/worker.rb
- test/test_retry_exhausted.rb
- test/test_testing.rb
- test/test_testing_fake.rb
> Fix overriding `class_attribute` core extension from ActiveSupport

- lib/sidekiq/processor.rb
- test/test_middleware.rb
- test/test_processor.rb
This PR implements #3501 
@mperham this is the first time I contribute Sidekiq, maybe it's not perfect this PR, if not, can you give me some guidelines or tell me what you think.
> Custom job_logger_class

- Changes.md
I spent some time finding out about issue. I think it would be better if changelog has it.
> Update changelog for section 5.0.4

- lib/sidekiq/delay.rb
- test/test_extensions.rb
> Ensure Sidekiq.enable_delay! does not break Psych.

- web/locales/en.yml
- web/locales/es.yml
- web/views/queues.erb
In order to improve the visibility of our queues, we would like to get more details in the UI.
> Add queue latency to the dashboard

- lib/sidekiq/cli.rb
sidekiq no longer supports rails 3.
> Fix message when require file could not be found

- lib/sidekiq/launcher.rb
This change adds a 5 years TTL on redis keys containing daily stats. See #3905 for more details
> Add TTL for stats keys

- lib/sidekiq/api.rb
- lib/sidekiq/web/application.rb
- web/locales/ar.yml
- web/locales/en.yml
- web/views/retries.erb
> Add Kill All button to the retries page

- web/assets/stylesheets/application.css
- web/views/_nav.erb
Fixed up css, and removed duplicate nav element.
> Fixed mobile navigation.

- lib/sidekiq/job_retry.rb
Prior to this commit `death_handlers` are only called if a job's retries are exhausted. Consequently, there was different behavior between specifying `retry: false` or `retry: 0` in `sidekiq_options`. 
This PR corrects the issue by ensuring the _global_ handler calls the `death_handlers`. If a job has a non-`false` value for `retry`, then the existing behavior is unaffected i.e. the local handler delegates to `attempt_retry` and when it's finished raises `Sidekiq::RetryJob::Skip`, which informs `global` not to handle the error, thus `death_handlers` are only ever called once.
> Ensure death_handlers are called on jobs with retry: false

- web/views/_nav.erb
Localize the "Back to App" string
> Localize String in _nav.erb

- lib/sidekiq/cli.rb
- lib/sidekiq/launcher.rb
- test/test_launcher.rb
> Move Proctitle from CLI to Launcher

- lib/sidekiq/middleware/i18n.rb
ref: https://github.com/contribsys/faktory_worker_ruby/pull/22
> Fix i18n middleware fallback

- web/locales/ja.yml
- add entries for `Kill` / `KillAll`
- remove the entry for `Batches`
> Update Japanese translations for web

- 6.0-Upgrade.md
- Fix wrong link to Logging page
> Fix wrong link

- lib/sidekiq/middleware/chain.rb
Since many applications are using bare oss sidekiq without any middlewares, this pr can help to save time and memory.
I have tested using `bin/sidekiqload`.
**Before**:
```
Total allocated: 999716276 bytes (10908573 objects)
Total retained:  12844675 bytes (1634 objects)
```
**After**:
```
Total allocated: 951803096 bytes (10109336 objects)
Total retained:  12826021 bytes (1330 objects)
```
Speed up in memory = `(999716276  - 951803096) / 999716276.0 * 100 ~ 5%`
**Before**:
```
["/Users/fatkodima/Desktop/oss/sidekiq/lib/sidekiq/middleware/chain.rb",
81,
:T_ARRAY]=>[2, 0, 0, 0, 0, 0],
["/Users/fatkodima/Desktop/oss/sidekiq/lib/sidekiq/client.rb",
216,
:T_ARRAY]=>[300009, 0, 0, 0, 0, 0],
["/Users/fatkodima/Desktop/oss/sidekiq/lib/sidekiq/middleware/chain.rb",
118,
:T_IMEMO]=>[200007, 0, 0, …
```
> Allocate Chain entries lazily

- Changes.md
- lib/sidekiq/scheduled.rb
> Get scheduled jobs in batches before pushing into specific queues

- Changes.md
- lib/sidekiq.rb
- lib/sidekiq/job_logger.rb
- lib/sidekiq/logger.rb
- lib/sidekiq/processor.rb
- test/test_job_logger.rb
> Support job-specific log levels

- lib/sidekiq/web/application.rb
- test/test_web.rb
> Call run_afters even if throwing from run_befores

- .circleci/config.yml
- README.md
Only `CC_TEST_REPORTER_ID` is missing here to finally get it to work.
https://docs.codeclimate.com/docs/finding-your-test-coverage-token
> Add test coverage badge to README.md

- lib/sidekiq/fetch.rb
- test/test_fetch.rb
It was written that way (skipping possible namespace before `queue:` prefix) because back then redis-namespace for `brpop` command was not returning unnamespaced queue names 
https://github.com/resque/redis-namespace/blob/2222455b247a66ab63b2e163f479f40cf50d716b/lib/redis/namespace.rb#L54
That was changed long time ago https://github.com/resque/redis-namespace/blob/e7da8a2bc63f27cccb4bda70bb580d470212d39d/lib/redis/namespace.rb#L62
So looks like this is a safe change.
Closes #4298
> Speedup UnitOfWork#queue_name

- lib/sidekiq/testing.rb
> Require extensions in lib/testing.rb

- test/test_redis_connection.rb
https://circleci.com/gh/mperham/sidekiq/358
> Fix flaky test

- lib/sidekiq/api.rb
- test/test_api.rb
https://github.com/mperham/sidekiq/pull/4306#issuecomment-542779209
> Fix SortedEntry#reschedule when called with non float as time

- lib/sidekiq/redis_connection.rb
- test/test_redis_connection.rb
> Redact sentinel passwords in redis options

- lib/sidekiq/redis_connection.rb
Sorry there was a small bug in my last PR.
> Fix sentinel password redaction presence check

- Ent-Changes.md
> Fix issue link in ent changelog

- lib/sidekiq/cli.rb
- test/test_cli.rb
> Print Rails info at startup

- web/locales/ja.yml
Hi, I added Japanese locale texts for pause / unpause for the Web UI button introduced in #4374.
> Add Japanese locale texts for pause / unpause

- lib/sidekiq/middleware/server/active_record.rb
> Fix Rails::VERSION check for sinatra and ActiveRecord

- web/assets/javascripts/application.js
Use of setInterval can lead to thundering herd under heavily loaded
conditions, fixes #4480.
> Remove usage of setInterval

- lib/sidekiq.rb
- lib/sidekiq/web/router.rb
- lib/sidekiq/worker.rb
+ Uses `Hash#transform_keys` to stringify.
+ Uses `Regex#named_captures` to get hash of captured data.
> Prefer Hash#transform_keys & Regex#named_captures

- test/test_web_helpers.rb
+ Add newly added **lt** locale to test cases
> Add missing lt locale to test cases

- Changes.md
- Gemfile.lock
- lib/sidekiq.rb
- lib/sidekiq/sd_notify.rb
- lib/sidekiq/systemd.rb
- test/test_systemd.rb
> systemd notification integration

- Changes.md
- lib/sidekiq/cli.rb
> Check RAILS_ENV before RACK_ENV

- web/assets/stylesheets/application-dark.css
- web/views/layout.erb
Use the media attribute of the link element for prefer-color-scheme. This will reduce unnecessary HTTP requests.
see https://web.dev/prefers-color-scheme/
> Use media attribute for prefers-color-scheme

- web/locales/fr.yml
> fix french clôturer to clôre

- lib/sidekiq/extensions/action_mailer.rb
- lib/sidekiq/extensions/active_record.rb
This PR improves documentation using YARD annotations.
- Use Example functionality for syntax highlighting
- Wrap the text with + for highlighting methods
> Document update using YARD annotation

- web/locales/ru.yml
Hello.
I noticed some keys in Russian were missing translations.
> Add missing keys to ru locale

- web/locales/fr.yml
> Typo in French: intervalle

- examples/systemd/sidekiq.service
> spell corrected - with

- lib/sidekiq/web/helpers.rb
> Don't hardcode URI scheme of redis connection url

- lib/sidekiq/middleware/chain.rb
I'm a big fan of sidekiq and was looking through the sidekiq middleware for inspiration.  I noticed a few areas that could be optimized, if you're open to it?
```ruby
remove(klass) if exists?(klass)
```
seems redundant, since each do an O(n) check for the existence of klass
```ruby
retrieve.dup
```
also seems redundant, since each call to `retrieve` will create brand new Entry instances
> middleware upgrade

- lib/sidekiq/testing.rb
So we're using `Sidekiq::Testing.inline!` for some interesting things @wistia - I'd love to be able to suppress the `puts` statements since we now require this file in development + staging environments. 🙏🏼
> Prefer warn over puts so these can be suppressed

- .github/workflows/ci.yml
Add ruby 3 to the build matrix
> Add ruby3 to build matrix

- web/locales/ja.yml
Hi @mperham, thanks for providing such nice gems.
I noticed that some Japanese translations were missing, so I added them.
> Add missing japanese locales

- web/locales/ar.yml
This PR adds some missing translations to `ar.yml`.
> Add missing Arabic translations

- lib/sidekiq/scheduled.rb
- test/test_scheduled.rb
This is another attempt to further improve scheduled jobs' enqueue latency. This does 2 changes:
1. It terminates the scheduler gracefully inside the `enqueue_jobs` loop and does not wait for the current poll to complete.
This is important when the scheduled jobs backlog is high and it takes a long time to go through them. We could go over the graceful timeout and lose jobs if we're in the middle of enqueuing them. I think this is a rare case but I also needed this for the next change below.
1. This makes the scheduler keep on scheduling as long as there are jobs that are due instead of waiting for the next poll.
This is useful when there are a lot of scheduled jobs where each poll could take a few seconds. By the time the poller is done, there are usually more jobs that are due. With the …
> Continue scheduling jobs when backlog jobs exist

- Pro-Changes.md
Thanks for the new feature! (from https://github.com/mperham/sidekiq/issues/5037)
The example text in `Pro-Changes.md` is just slightly wrong.
> Fix "Statsd.options" example

- web/assets/stylesheets/application-dark.css
> Dark Mode Improvements

- lib/sidekiq/api.rb
- test/test_extensions.rb
> Add keyword arguments handler in Sidekiq::JobRecord#display_args

- lib/sidekiq/api.rb
- lib/sidekiq/web/action.rb
- lib/sidekiq/web/application.rb
- test/test_api.rb
- test/test_web.rb
This was implemented because of the discussion in #5151
Original commit message:
Validate days parameter to avoid possible DoS in Web UI
Thank you to Sergey Shpakov of http://tutum.space for reporting.
Signed-off-by: Sven Marquardt <dev@mail.smarquardt.space>
> Backport 7785ac1399f1b28992adb56055f6acd88fd1d956

- .github/contributing.md
- README.md
> Add better contributing guidelines

- examples/por.rb
I was checking the README and the "Getting started" page in the wiki and stumbled across this one.
IMO, the "Getting started" page should probably be updated, too. But there were concerns about confusion for people using older versions, see #5172. So I held off on that for now.
> Use new terminology in examples

- test/test_scheduling.rb
It would be good to fix the build on `main` at some point, but sometimes you need to take a step back to move forward 😆 There are two commits in this PR and they should be reviewed separately.
> Further improve tests related to bulk scheduling of jobs

- lib/sidekiq/client.rb
- lib/sidekiq/job_util.rb
- lib/sidekiq/worker.rb
> Remove parallel code paths caused by "push" and "push_bulk"

- lib/sidekiq/cli.rb
Before :
```sh
17:25:08 sidekiq_fifo.1  | -----
17:25:08 sidekiq_fifo.1  | BEFORE SIDEKIQ PARSE
17:25:08 sidekiq_fifo.1  | ---
17:25:08 sidekiq_fifo.1  | - "-C"
17:25:08 sidekiq_fifo.1  | - config/sidekiq/sidekiq_fifo.yml
17:25:08 sidekiq_fifo.1  | ---
17:25:08 sidekiq_fifo.1  | - "-C"
17:25:08 sidekiq_fifo.1  | - config/sidekiq/sidekiq_fifo.yml
17:25:08 sidekiq_fifo.1  | -----
17:25:08 sidekiq_fifo.1  | AFTER SIDEKIQ PARSE
17:25:08 sidekiq_fifo.1  | --- []
17:25:08 sidekiq_fifo.1  | --- []
```
After :
```sh
17:25:33 sidekiq_fifo.1  | -----
17:25:33 sidekiq_fifo.1  | BEFORE SIDEKIQ PARSE
17:25:33 sidekiq_fifo.1  | ---
17:25:33 sidekiq_fifo.1  | - "-C"
17:25:33 sidekiq_fifo.1  | - config/sidekiq/sidekiq_fifo.yml
17:25:33 sidekiq_fifo.1  | ---
17:25:33 sidekiq_fifo.1  | - "-C"
17:25:33 …
```
> Avoid mutating ARGV

- Gemfile.lock
This option is only annoying for a library development
> Remove BUNDLED_WITH from 7-0 branch

- lib/sidekiq/web/csrf_protection.rb
This PR addresses issue #5273.
> Use Base64.urlsafe_* like Rake::Protection::AuthenticityToken

- web/locales/pt-br.yml
Updating the `pt-br` language support. I added the missing keys and updated an outdated phrase.
> Update pt-br i18n language file

- lib/sidekiq/client.rb
- test/test_client.rb
https://github.com/mperham/sidekiq/issues/5311
---
v6.4.2 introduced breaking changes to the argument types of the middleware client.
> Middleware Argument type

- .github/contributing.md
Added a line to the contributing doc, making sure that new contributors know how to stay up to date with main in the original repository
> Update contributing doc

- .gitignore
- .yardopts
- Gemfile
- Rakefile
- docs/menu.md
- lib/sidekiq/api.rb
- lib/sidekiq/middleware/chain.rb
Improve the RDoc for "sidekiq/api".
A good cheatsheet for YARD syntax:
https://gist.github.com/donnoman/562875
cc @SamArdrey
> Better rdoc for public APIs

- web/assets/javascripts/application.js
- web/views/_nav.erb
- web/views/queue.erb
> Fix broken hamburger toggle.

- lib/sidekiq/scheduled.rb
- test/test_scheduled.rb
We should not memoize the value of `scaled_poll_interval` because this changes based on the number of Sidekiq processes.
Previously, at every poll, we check the process count to determine the formula for computing the random interval. But the `poll_interval_average` was still using a value computed from the first poll.
> Fix poll interval not changing based on process count

- web/locales/ja.yml
Added some missing translations which were found during working on #5532.
> Add missing translations for ja

- web/assets/javascripts/base-charts.js
- web/assets/javascripts/dashboard-charts.js
- web/assets/stylesheets/application-rtl.css
- web/assets/stylesheets/application.css
- web/views/dashboard.erb
This is not yet working.
The intention is to have a vertical line on the chart corresponding to the currently shown "tooltip" info in the legend below the chart. This is the behavior of Sidekiq 6.
> render a "cursor" that follows the tooltip

- docs/7.0-Upgrade.md
While going through the 7.0-Upgrade file, I noticed a grammatical error, so I used Grammarly and LanguageTool to double-check the content. I made a few minor changes to the 7.0-Upgrade file based on Grammarly's suggestions.
> Minor grammatical changes

- lib/sidekiq/api.rb
> Speedup iterating over `WorkSet`

- web/locales/zh-cn.yml
Fix wrong translation to simplified Chinese.
And add missing translation to Chinese, for metric page.
> Fix wrong translation. And add missing translation for metric page

- lib/sidekiq/web/helpers.rb
- web/views/_poll_link.erb
> Metrics: Removes polling button

- lib/sidekiq/web/helpers.rb
- test/web_helpers_test.rb
Just noticed this failing in the sidekiq-scheduler test suite https://github.com/sidekiq-scheduler/sidekiq-scheduler/actions/runs/3399698575/jobs/5653621656#step:5:52
https://github.com/mperham/sidekiq/commit/2bfe30667a6be18a9bdce6415ee5ec3c4bf1a6de
> Use start_with? instead of starts_with? which is only available on Rails

- docs/7.0-Upgrade.md
> Add note to the 7.0 upgrade document re rediscloud support

- lib/sidekiq/api.rb
- lib/sidekiq/launcher.rb
- lib/sidekiq/web/application.rb
- test/api_test.rb
- test/helper.rb
- test/web_test.rb
- web/views/busy.erb
- add embedded to Process
- don't allow quiet! or stop! 
- show in the Web UI as embedded 
- don't show the buttons to quiet or stop for embedded
Fixes #5714
> Don't allow quiet or stop on embedded processes

- web/locales/da.yml
**Changes**
Wording:
- Actions => Handlinger
- Real-time => Realtid
Grammar:
- Fejl klasse => Fejlklasse
- Fejl besked => Fejlbesked
And added execution time, name etc. for the Metrics page.
> Update Danish (da.yml) translations for Sidekiq 7.0

- Pro-Changes.md
"master" branch has been renamed to "main".
> Fix branch name in Pro-Changes.md

- web/locales/ja.yml
Hello, I added Japanese locale texts for updated metrics page.
Thanks.
> Update Japanese translations for updated metrics page

- docs/7.0-API-Migration.md
Adds clarifications for updating to v7 about:
- custom logger formatter
- redis sentinel configuration
Issues:
- https://github.com/sidekiq/sidekiq/issues/5603
> Fix docs for update to v7

- docs/middleware.md
> Change job params to match changed params in wiki

- web/locales/fr.yml
> Add french translation

- lib/sidekiq/processor.rb
While reviewing different uses of `Thread.handle_interrupt`, I observed that Sidekiq's usage does not fully guarantee that job acknowledgement will happen once the `ensure` block is reached.  It's possible that an interrupt exception could be raised between `ensure` and `Thread.handle_interrupt`. Similar to the issue written about here: 
https://itnext.io/why-puma-workers-constantly-hung-and-how-we-fixed-by-discovering-the-bug-of-ruby-v2-5-8-and-v2-6-6-7fa0fd0a1958
This is arguably not a problem if the intent was only to guard the job acknowledgement once invoked but not ensure it takes place. I also allowed the `rescue` statements to be interruptible, but maybe they also should be moved into the non-interruptable block.
Hope this is helpful and I'm also open to the possibility I'm …
> Have `Thread.handle_interrupt` wrap the entire `ensure` block for job acknowledgement

- Changes.md
- lib/sidekiq/config.rb
- lib/sidekiq/rails.rb
- test/exception_handler_test.rb
> Remove config from logged context, fixes #6047

- README.md
1. Update README.MD to reflect new links to social media accounts.
> Update author and project social media links.

- lib/sidekiq/rails.rb
Rails actually improved configuring logging broadcasting - https://github.com/rails/rails/pull/49417.
> Change rails logger broadcasting configuration

- web/assets/javascripts/application.js
- web/assets/javascripts/metrics.js
- web/views/_metrics_period_select.erb
I noticed that on /metrics, there's an `unsafe-inline` error triggered by the [new csp](#6074). This moves the functionality out of the page.
> CSP fix for metric period.

- myapp/config/application.rb
- myapp/config/environments/development.rb
- myapp/config/environments/production.rb
- myapp/config/environments/test.rb
This fixes some styles by `rake standard:fix_unsafely`.
Ref: https://github.com/sidekiq/sidekiq/actions/runs/6817192931/job/18540155962#step:6:14
> Fix broken CI by standard style sheck

- lib/sidekiq/api.rb
Fixes Issue https://github.com/sidekiq/sidekiq/issues/6281
> Fix redefined `respond_to_missing?` method signature

- test/processor_test.rb
These are the same as in the block below them.
> Delete duplicate tests

- lib/sidekiq/web.rb
- lib/sidekiq/web/application.rb
Hello! This is a very minor change but a security scanner flagged this header as missing and even if there's no real security risk I figured it was easy enough to add to get a clean scan result on our application. ;)
> Add X-Content-Type-Options header

- lib/sidekiq/api.rb
Adds a new option `ex` to `DeadSet#kill` which will allow passing a custom exception instead of the generic RuntimeError.  My specific use-case is doing some custom error handling for errors that shouldn't be retried but should go to the DLQ and I want to have access to the original error.
This will change this code from:
```rb
module SidekiqMiddleware
class ErrorHandler
include Sidekiq::ServerMiddleware
def call(_job_instance, job_payload, _queue)
yield
rescue NonRetryableError => e
message = job_payload.merge(
{
error_message: e.message,
error_class: e.class,
},
).to_json
Sidekiq::DeadSet.new.kill(message, notify_failure: false)
Sidekiq.default_configuration.death_handlers.each do |handle|
job = Sidekiq.load_json(message)
handle.call(job, e)
end
end
end
end
```
to 
```rb
module …
```
> Allow exception to be passed via opts to DeadSet#kill

- lib/sidekiq/metrics/tracking.rb
- test/metrics_test.rb
> Do not track iterable jobs interruptions as failures

- lib/active_job/queue_adapters/sidekiq_adapter.rb
- lib/sidekiq/api.rb
- lib/sidekiq/rails.rb
- test/active_job_adapter_test.rb
- test/api_test.rb
- test/client_test.rb
- test/dummy/config/application.rb
- test/exception_handler_test.rb
- test/helper.rb
- test/rails_test.rb
- test/retry_test.rb
- test/transaction_aware_client_test.rb
> Add Active Job adapter

- lib/active_job/queue_adapters/sidekiq_adapter.rb
- test/active_job_adapter_test.rb
- test/retry_test.rb
> Stick with old ActiveJob adapter name

- web/views/metrics.erb
This is already localized in other places, for example https://github.com/sidekiq/sidekiq/blob/61aaffabed72ee8a7d9bc53f38710d955d17b0b7/web/views/metrics_for_job.erb#L44 except this one
> Add missing 'Seconds' localization

- lib/sidekiq/web/application.rb
- lib/sidekiq/web/router.rb
- test/filtering_test.rb
Closes #6187.
I added missing tests and also took an opportunity to do a small cleanup of route definitions.
> DRY filtering routes definitions

- lib/sidekiq/metrics/shared.rb
- sidekiq.gemspec
> Remove `concurrent-ruby` gem dependency

- lib/sidekiq/middleware/current_attributes.rb
See https://github.com/rails/rails/pull/53440 for the problem description.
> Dup current attributes on saving

- web/locales/it.yml
> Add missing Italian translations

- Changes.md
- Gemfile
- lib/sidekiq/api.rb
- lib/sidekiq/processor.rb
- lib/sidekiq/profiler.rb
- lib/sidekiq/web.rb
- lib/sidekiq/web/action.rb
- lib/sidekiq/web/application.rb
- myapp/Gemfile
- test/api_test.rb
- test/profiling_test.rb
- web/locales/en.yml
- web/views/profiles.erb
Work in progress. Needs web testing and integration with the Firefox viewer.
See https://github.com/sidekiq/sidekiq/wiki/Profiling for usage.
> Production job profiling with Vernier

- web/assets/stylesheets/style.css
- web/locales/en.yml
- web/views/_footer.erb
- web/views/dashboard.erb
- web/views/queue.erb
I work at GitLab and we have been looking into some accessibility improvements. As we use the Sidekiq Web UI, we had a look at the Sidekiq repo as well, and found a few improvements that we can make.
In this PR I've added a few ARIA labels and a missing table header.
> Add ARIA labels and other accessibility fixes

- web/locales/es.yml
Update token for Spanish translations
> update es translations

- web/assets/javascripts/dashboard-charts.js
- web/assets/javascripts/dashboard.js
- web/locales/en.yml
- web/views/_footer.erb
- web/views/dashboard.erb
- web/views/queue.erb
This PR backports the accessibility changes I made in earlier PRs to the 7-x branch
> Backport accessibility changes to 7-x branch

- Changes.md
- lib/sidekiq/web/action.rb
- web/assets/stylesheets/style.css
- web/views/_flash.erb
- web/views/layout.erb
> feat: Implement flash messages

- lib/sidekiq/web/application.rb
fixes #6684 
change from HTTP.post to HTTP.new activates build-in proxy support in library
> add proxy support for http

- lib/sidekiq/job/iterable.rb
- test/iterable/iterable_jobs.rb
- test/iterable/iterable_test.rb
Fix https://github.com/sidekiq/sidekiq/issues/6596#issuecomment-2872430130
> Flush iterable cursor when exception raised

- lib/sidekiq/transaction_aware_client.rb
At @amplemarket, we have several databases, and the existing AfterCommitEverywhere only supports transactions on one database at a time. Additionally, with the default configuration of the transactional client, only transactions in the default database are honored.
Since ActiveRecord 7.2, there is a hook that waits for all databases. Here is an alternative client that mimics exactly the existing one, but using ActiveRecord tooling instead of an external library.
> Introduce transactional client with AR tooling

- lib/sidekiq/transaction_aware_client.rb
This take's @rewritten's Rails 7.2+ compatible fix from sidekiq/sidekiq#6765 and brings it to the **7-x** branch to avoid using `ActiveRecord::Base.connection` (used internally by after_commit_everywhere).
This will provide a first-party solution for Sidekiq 7.x users who need Rails 7.2 support while moving off of Rails 7.1 which is EOL at the beginning of next month. In our case, upgrading to rack 3 is non-trivial and this helps buy us some breathing room. Hopefully it can also help others.
> Use ActiveRecord transaction tooling in Sidekiq 7
